Ott 88
PubMatic-OpenWrap/prebid-server pull request #106
Opened 2021-01-18 14:57 UTC by ShriprasadM

2021-01-20 15:11 UTC, ShriprasadM commented on adapters/vastbidder/bidder_macro.go
> +	impReqHeaders http.Header
Holds the impression level request headers to be sent in the VAST bidder request

2021-01-20 15:13 UTC, ShriprasadM commented on adapters/vastbidder/bidder_macro.go
> +//Override this method if your Vast bidder needs custom  request headers
GetHeaders will be used to accept a list of custom request headers that VAST bidder may expect in the request

2021-01-20 15:14 UTC, ShriprasadM commented on adapters/vastbidder/bidder_macro.go
> +func setDefaultHeaders(tag *BidderMacro) {
set default headers will populate the list of default request headers for any given VAST bidder

2021-01-20 15:17 UTC, ShriprasadM commented on adapters/vastbidder/bidder_macro.go
> +	}
hasVast4 - will be set to true, if VAST4 or VAST4-wrapper is expected
hasPriorVastVersions - will be set to true, if VAST 3.0 or lesser or VAST-3.0-wrapper is expected.

Use these flags, request headers will be conditionally populated. The following table shows how headers will be populated


When Vast version is | Send headers | DO NOT send these headers
-- | -- | --
4.04.0 Wrapper | X-device-IPX-Device-User-AgentX-Device-RefererX-device-Accept-Language | X-Forwarded-ForUser-Agent
Any other following vast version VAST 1.0 VAST 2.0 VAST 3.0 VAST 1.0 Wrapper VAST 2.0 Wrapper VAST 3.0 Wrapper | X-Forwarded-ForUser-Agent | X-device-IPX-Device-User-AgentX-Device-RefererX-device-Accept-Language


When Vast version is | Send headers | DO NOT send these headers
-- | -- | --
4.04.0 Wrapper | X-device-IPX-Device-User-AgentX-Device-RefererX-device-Accept-Language | X-Forwarded-ForUser-Agent
Any other following vast version VAST 1.0 VAST 2.0 VAST 3.0 VAST 1.0 Wrapper VAST 2.0 Wrapper VAST 3.0 Wrapper | X-Forwarded-ForUser-Agent | X-device-IPX-Device-User-AgentX-Device-RefererX-device-Accept-Language

2021-01-20 15:19 UTC, ShriprasadM commented on adapters/vastbidder/bidder_macro.go
> +func (tag *BidderMacro) getAllHeaders() http.Header {
getAllHeaders - The private method internally used to combine a list of default headers along with a list of custom headers if any. 
After calling this method, the final list of headers is passed to VAST Bidder

2021-01-20 15:20 UTC, ShriprasadM commented on adapters/vastbidder/bidder_macro_test.go
> +	tests := []struct {
Testcases
1. check all default headers
2. nil bid request
3. no headers set
4. vast 4 protocol
5. < vast 4

2021-01-20 15:21 UTC, ShriprasadM commented on adapters/vastbidder/tagbidder.go
> +		headers := bidderMacro.getAllHeaders()
Get the list of default and combine headers

2021-01-20 15:21 UTC, ShriprasadM commented on adapters/vastbidder/tagbidder_test.go
> +	tests := []struct {
1. multi_impression_req

2021-01-20 15:22 UTC, ShriprasadM commented on exchange/bidder.go
> +			RequestHeaders: httpInfo.request.Headers,
Log Request Headers when this is no error

2021-01-20 15:22 UTC, ShriprasadM commented on exchange/bidder.go
> +			RequestHeaders: httpInfo.request.Headers,
Log Request Headers when there is error

2021-01-20 15:22 UTC, ShriprasadM commented on exchange/bidder_test.go
> +	}
Verify, in case of Bad request Request Headers are not logged

2021-01-20 15:22 UTC, ShriprasadM commented on exchange/bidder_test.go
> +			},
Simulation of request headers set

2021-01-20 15:22 UTC, ShriprasadM commented on exchange/bidder_test.go
> +	assert.Equal(t, info.request.Headers, http.Header(ext.RequestHeaders), "The request headers should be \"header-1:value-1\"")
Verify Request headers are logged when there is a bad response

2021-01-20 15:23 UTC, ShriprasadM commented on exchange/bidder_test.go
> +			},
Simulation of request headers set

2021-01-20 15:23 UTC, ShriprasadM commented on exchange/bidder_test.go
> +	assert.Equal(t, info.request.Headers, http.Header(ext.RequestHeaders), "The request headers should be \"%s\". Got %s", info.request.Headers, ext.RequestHeaders)
Verify Request headers are logged when there is a bad response

2021-01-20 15:23 UTC, ShriprasadM commented on exchange/exchangetest/request-multi-bidders-debug-info.json
> +            "requestheaders": null
Added new parameter to satisfy the unit test

2021-01-20 15:23 UTC, ShriprasadM commented on exchange/exchangetest/request-multi-bidders-debug-info.json
> +            "requestheaders": null
Added new parameter to satisfy the unit test

2021-01-20 15:23 UTC, ShriprasadM commented on exchange/exchangetest/request-multi-bidders-debug-info.json
> +              "requestheaders": null
Added new parameter to satisfy the unit test

2021-01-20 15:23 UTC, ShriprasadM commented on exchange/exchangetest/request-multi-bidders-debug-info.json
> +              "requestheaders": null
Added new parameter to satisfy the unit test

2021-01-20 15:24 UTC, ShriprasadM commented on openrtb_ext/response.go
> +	RequestHeaders map[string][]string `json:"requestheaders"`
The new parameter RequestHeaders will contain the header key and multiple values associated with it.
We have kept value as an array of strings because one header can have multiple values.
Also, this data structure is inline with http/Header
requestheaders is the key used while forming the JSON

2021-01-21 05:54 UTC, ShriprasadM commented on adapters/vastbidder/bidder_macro.go
> +	hasPriorVastVersions := false
Check if we can use one single flag instead of 2 flags

2021-01-21 06:21 UTC, pm-viral-vala requested changes

2021-01-21 06:21 UTC, pm-viral-vala commented on adapters/vastbidder/bidder_macro.go
> +	ip := tag.MacroIP("")
use tag.IBidderMacro.MacroIP and pass constant.MacroIP key to function

2021-01-21 06:21 UTC, pm-viral-vala commented on adapters/vastbidder/bidder_macro.go
> +	userAgent := tag.MacroUserAgent("")
use tag.IBidderMacro.MacroUserAgent and pass constant.MacroUserAgent key to function

2021-01-21 06:21 UTC, pm-viral-vala commented on adapters/vastbidder/bidder_macro.go
> +			hasVast4 = hasVast4 || (protocol == openrtb.ProtocolVAST40 || protocol == openrtb.ProtocolVAST40Wrapper)
we can break the loop once we found VAST4 version.

2021-01-21 06:21 UTC, pm-viral-vala commented on adapters/vastbidder/bidder_macro.go
> +	if nil != tag.Imp && nil != tag.Imp.Video && nil != tag.Imp.Video.Protocols && len(tag.Imp.Video.Protocols) > 0 {
we can remove empty check for tag.Imp,

2021-01-25 07:37 UTC, pm-viral-vala approved these changes
LGTM

2021-01-27 07:40 UTC, PubMatic-OpenWrap approved these changes
LGTM

2021-01-27 09:46 UTC, pm-viral-vala approved these changes
LGTM

2021-01-27 09:51 UTC, merged