OTT-130: Injecting Video Tracking Events in VAST
PubMatic-OpenWrap/prebid-server pull request #130
Opened 2021-03-04 09:32 UTC by ShriprasadM

2021-03-05 07:18 UTC, ShriprasadM commented on endpoints/events/vtrack.go
> +		eventURL = replaceMacro(eventURL, VASTAdTypeMacro, "")
Done

2021-03-05 07:20 UTC, ShriprasadM commented on endpoints/events/vtrack.go
> +	for _, event := range []string{"firstQuartile", "midpoint", "thirdQuartile", "complete"} {
Done

2021-03-05 08:40 UTC, ShriprasadM commented on endpoints/events/vtrack_test.go
> +					"firstQuartile": []string{"http://something.com", "http://company.tracker.com?eventId=1004&appbundle=abc"},
Done. added required assertions

2021-03-17 09:42 UTC, ShriprasadM commented on exchange/events.go
> +		fmt.Println(bid.AdM)
Done

2021-03-17 09:42 UTC, ShriprasadM commented on endpoints/events/vtrack_test.go
> +		},
Done

2021-03-18 04:58 UTC, pm-viral-vala requested changes
Once changes are done, Please go ahead with QADrop.

2021-03-18 04:58 UTC, pm-viral-vala commented on endpoints/events/vtrack.go
> +	if "" == strings.Trim(bid.AdM, " ") || strings.HasPrefix(strings.TrimLeft(strings.TrimRight(bid.AdM, "]]>"), "<![CDATA["), "http") {
* use strings.TrimSpace() instead of strings.Trim()
* bid.AdM never comes inside CDATA Tag if it is returning VAST Tag URL. check trimmed bid.AdM starts with http
*

2021-03-18 04:58 UTC, pm-viral-vala commented on endpoints/events/vtrack.go
> +		return []byte(vastXML), false, errors.New(err) // false indicates events trackers are not injected
return err itself

2021-03-18 04:58 UTC, pm-viral-vala commented on endpoints/events/vtrack.go
> +		err := fmt.Sprintf("Error parsing VAST XML. '%v'", err.Error())
fmt.Errorf use instead Sprintf

2021-03-18 04:58 UTC, pm-viral-vala commented on endpoints/events/vtrack.go
> +//InjectVideoEventTrackers injects the video tracking events
return parameter single line description

2021-03-18 04:58 UTC, pm-viral-vala commented on endpoints/events/vtrack.go
> +			eventURL = replaceMacro(eventURL, VASTAppBundleMacro, req.App.Bundle)
Check Macro here, Domain or Bundle

2021-03-18 04:58 UTC, pm-viral-vala commented on endpoints/events/vtrack.go
> +	if strings.HasPrefix(macro, "[") && strings.HasSuffix(macro, "]") && len(strings.Trim(value, " ")) > 0 {
will it replace "  [MACRO]  "? Check with trimmed value.

2021-03-18 04:58 UTC, pm-viral-vala commented on exchange/auction.go
> +	if strings.HasPrefix(adm, "<![CDATA[") {
adm won't have CDATA

2021-03-18 05:40 UTC, ShriprasadM commented on exchange/auction.go
> +	if strings.HasPrefix(adm, "<![CDATA[") {
Removed the block

2021-03-18 05:41 UTC, ShriprasadM commented on endpoints/events/vtrack.go
> +	if strings.HasPrefix(macro, "[") && strings.HasSuffix(macro, "]") && len(strings.Trim(value, " ")) > 0 {
Added TrimSpace

2021-03-18 05:41 UTC, ShriprasadM commented on endpoints/events/vtrack.go
> +			eventURL = replaceMacro(eventURL, VASTAppBundleMacro, req.App.Bundle)
[DOMAIN] will be req.App.Bundle in case of Apps

2021-03-18 05:41 UTC, ShriprasadM commented on endpoints/events/vtrack.go
> +//InjectVideoEventTrackers injects the video tracking events
Done

2021-03-18 05:41 UTC, ShriprasadM commented on endpoints/events/vtrack.go
> +		err := fmt.Sprintf("Error parsing VAST XML. '%v'", err.Error())
Done

2021-03-18 05:41 UTC, ShriprasadM commented on endpoints/events/vtrack.go
> +		return []byte(vastXML), false, errors.New(err) // false indicates events trackers are not injected
Done

2021-03-18 05:41 UTC, ShriprasadM commented on endpoints/events/vtrack.go
> +	if "" == strings.Trim(bid.AdM, " ") || strings.HasPrefix(strings.TrimLeft(strings.TrimRight(bid.AdM, "]]>"), "<![CDATA["), "http") {
Done

2021-03-18 11:57 UTC, pm-viral-vala approved these changes
👍

2021-03-18 11:58 UTC, merged