OTT-183: Fixed the issue of operId=8 must be first query param
PubMatic-OpenWrap/prebid-server pull request #141
Opened 2021-04-26 09:59 UTC by ShriprasadM

2021-04-26 10:57 UTC, pm-viral-vala requested changes

2021-04-26 10:57 UTC, pm-viral-vala commented on endpoints/openrtb2/ctv_auction.go
> +					//OTT-183: Fix
can we just search and replace, "bidid=original-imp-id" to "bidid=new-imp-id"

2021-04-27 06:57 UTC, pm-viral-vala approved these changes

2021-04-27 06:58 UTC, ShriprasadM commented on endpoints/openrtb2/ctv_auction.go
> +					//OTT-183: Fix
As discussed with @pm-viral-vala we can keep the current implementation as this is temporary function

2021-04-27 06:59 UTC, merged