OTT-217 - Remove logger for excluded VASTTags
PubMatic-OpenWrap/prebid-server pull request #175
Opened 2021-07-02 02:59 UTC by PubMatic-OpenWrap

2021-07-02 06:27 UTC, PubMatic-OpenWrap commented on endpoints/openrtb2/ctv_auction.go
>  				continue
Move this to `readExtensions` method

2021-07-02 06:30 UTC, PubMatic-OpenWrap commented on endpoints/openrtb2/ctv_auction.go
> +					impPartnerTagNamesMap[originalImpID][partnerName] = append(impPartnerTagNamesMap[originalImpID][partnerName], vastTag["tagid"].(string))
```suggestion
					impPartnerTagIDMap[originalImpID][partnerName] = append(impPartnerTagIDMap[originalImpID][partnerName], vastTag["tagid"].(string))
```

2021-07-05 07:06 UTC, pm-viral-vala requested changes

2021-07-05 07:06 UTC, pm-viral-vala commented on endpoints/openrtb2/ctv_auction.go
> +	deps.impPartnerTagIDMap = make(map[string]map[string][]string)
you can use something like impPartnerMap:= map[string]map[string]*openrtb_ext.ExtImpVASTBidder

2021-07-05 09:55 UTC, pm-viral-vala approved these changes

2021-07-05 09:56 UTC, merged