UOE-7610: Add upgrade script
PubMatic-OpenWrap/prebid-server pull request #284
Opened 2022-05-04 04:13 UTC by pm-nilesh-chate

# Description

Please add change description or link to ticket, docs, etc.

# Checklist:

- [ ] PR commit list is unique (rebase/pull with the origin branch to keep master clean).
- [ ] JIRA number is added in the PR title and the commit message.
- [ ] Updated the `header-bidding` repo with appropiate commit id.
- [ ] Documented the new changes.

For Prebid upgrade, refer: https://inside.pubmatic.com:8443/confluence/display/Products/Prebid-server+upgrade

2022-05-04 08:42 UTC, pm-nilesh-chate commented on upgrade/upgrade-pbs.sh
> +#!/bin/bash -e
move this file to scripts dir

2022-05-04 09:04 UTC, pm-nilesh-chate commented on upgrade/upgrade-pbs.sh
> +    checkpoint_run "./validate.sh"
set go race for validate.sh

2022-05-05 08:08 UTC, ShriprasadM requested changes

2022-05-05 08:08 UTC, ShriprasadM commented on validate.sh
> +RACE=5
Can't we  introduce this change temporarily while running `upgrade-pbs.sh` and then revert `validate.sh` back to original state. It will ensure `validate.sh` is always inline with PBS vanilla code

2022-05-05 08:12 UTC, pm-nilesh-chate commented on validate.sh
> +RACE=5
done

2022-05-05 09:41 UTC, ShriprasadM requested changes

2022-05-05 09:55 UTC, pm-nilesh-chate commented on scripts/upgrade-pbs.sh
> +#!/bin/bash -e
done

2022-05-05 10:04 UTC, ShriprasadM approved these changes
LGTM.  As discussed we will be intentionally merging it to `master`, because - `This script needs master branch to work as vanilla does not have ci branch`

2022-05-05 10:54 UTC, merged