OTT-475, OTT-476:  Implementation of Floor Signalling based on give floor json and rules selection process
PubMatic-OpenWrap/prebid-server pull request #285
Opened 2022-05-05 03:38 UTC by pm-jaydeep-mohite

# Description

Please add change description or link to ticket, docs, etc.

# Checklist:

- [ ] PR commit list is unique (rebase/pull with the origin branch to keep master clean).
- [ ] JIRA number is added in the PR title and the commit message.
- [ ] Updated the `header-bidding` repo with appropiate commit id.
- [ ] Documented the new changes.

For Prebid upgrade, refer: https://inside.pubmatic.com:8443/confluence/display/Products/Prebid-server+upgrade

2022-05-05 05:26 UTC, Pubmatic-Dhruv-Sonone commented on exchange/exchange.go
> +		floor:          &floorConfig{cfg.PriceFloors.Enabled},
Do we need a floor Config Here?   Can we just use floorEnable boolean key and set it using config?

2022-05-05 09:54 UTC, pm-nikhil-vaidya commented on floors/resolve_floor.go
> +	} else {
Else can be removed 
if skipRate > 0 && skipRate > rand.Intn(SKIP_RATE_MAX) {
 		return true
 }
 
 return false

2022-05-05 09:56 UTC, pm-nikhil-vaidya commented on floors/resolve_floor.go
> +	} else {
Else can be eliminated 

if requestExt.Prebid.Floors != nil && requestExt.Prebid.Floors.Enabled != nil && *requestExt.Prebid.Floors.Enabled == true {
 		                  return true
 }
 return false

2022-05-05 10:07 UTC, pm-nikhil-vaidya commented on floors/resolve_floor.go
> +	var skipRate int
If we have `floorData.SkipRate` value always available then below code can be modified as

`skipRate := floorData.SkipRate`
 `if floorData.ModelGroups[0].SkipRate > 0 {
 		skipRate = floorData.ModelGroups[0].SkipRate
 	}`

2022-05-06 08:18 UTC, pm-viral-vala requested changes

2022-05-06 08:18 UTC, pm-viral-vala commented on floors/resolve_floor.go
> +	if len(bidRequest.Ext) > 0 {
can we remove this unmarshal function?

2022-05-09 03:26 UTC, pm-jaydeep-mohite commented on exchange/exchange.go
> +
moved

2022-05-09 03:26 UTC, pm-jaydeep-mohite commented on exchange/exchange.go
> +		floor:          &floorConfig{cfg.PriceFloors.Enabled},
We need structure for future scope

2022-05-09 03:53 UTC, pm-nilesh-chate commented on floors/resolve_floor.go
> +
Would it be better to use intuitive name `floor.go` and `floor_test.go`?

2022-05-09 04:00 UTC, pm-nilesh-chate commented on floors/resolve_floor.go
> +	} else {
also, `if else` is not needed

2022-05-09 04:01 UTC, pm-jaydeep-mohite commented on floors/resolve_floor.go
> +		selectFloorModelGroup(floorData.ModelGroups)
As per PRD document https://docs.google.com/document/d/1YAt00RfQaU2Ugciqw1LnirLgjyUz9ibfyjfxWUHR_P0, ext.prebid.floors.data.modelGroups[0]  is the only entry of the original modelGroups array that should be seen by downstream code and analytics adaptor.

2022-05-09 04:02 UTC, pm-nilesh-chate commented on floors/resolve_floor.go
> +	if shouldSkipFloors(floorData) == true {
`shouldSkipFloors` returns boolean, no need to compare it with `true` here.

2022-05-09 04:05 UTC, pm-nilesh-chate commented on floors/resolve_floor.go
> +		if matchedRule == "" {
use `default` variable approach. This reduces branching of `else` and easy to cover unit test scenarios

2022-05-09 04:05 UTC, pm-nilesh-chate commented on floors/resolve_floor.go
> +		if floorExt.FloorMin != 0.0 && floorVal < floorExt.FloorMin {
use `default` variable approach. This reduces branching of `else` and easy to cover unit test scenarios

2022-05-09 04:08 UTC, pm-nilesh-chate commented on floors/resolve_floor.go
> +	var floorModelErrList []error
Why not use `errs` instead of `floorModelErrList` ?. `errs` is more go idiomatic

2022-05-09 04:11 UTC, pm-nilesh-chate commented on floors/resolve_floor.go
> +			floorModelErrList = append(floorModelErrList, fmt.Errorf("Invalid Floor Model = '%v' due to ModelWeight = '%v'", modelGroup.ModelVersion, modelGroup.ModelWeight))
Should we use error codes for such filtering based on SkipRate and ModelWeight for?

2022-05-09 04:15 UTC, pm-nilesh-chate commented on floors/resolve_floor.go
> +			modelGroups = append([]openrtb_ext.PriceFloorModelGroup{modelGroup}, append((modelGroups)[:i], (modelGroups)[i+1:]...)...)
Does this move the current item to index 0?. Can we just swap the `arr[0]` with `arr[i]`. `append()` would be expensive

2022-05-09 04:15 UTC, pm-jaydeep-mohite commented on floors/resolve_floor.go
> +	sort.SliceStable(modelGroups, func(i, j int) bool {
sorting is required. If we remove sorting model group with less weight at last position in array would not get selected.

2022-05-09 04:16 UTC, pm-nilesh-chate commented on floors/resolve_floor.go
> +func selectFloorModelGroup(modelGroups []openrtb_ext.PriceFloorModelGroup) {
Please add unit tests for the functions covering all the scenarios. Test cases would help a lot to understand the scenarios and choices, etc.

2022-05-09 04:16 UTC, pm-jaydeep-mohite commented on floors/resolve_floor.go
> +func extractChanelNameFromBidRequestExt(bidRequest *openrtb2.BidRequest) string {
Openrtb_ext.RequestWrapper  is not passed into auction request

2022-05-09 04:18 UTC, pm-jaydeep-mohite commented on openrtb_ext/request.go
> +type PriceFloorModelGroup struct {
Done

2022-05-09 04:19 UTC, pm-jaydeep-mohite commented on exchange/exchange.go
> +type Floor interface {
Done

2022-05-09 04:20 UTC, pm-nilesh-chate commented on floors/resolve_floor.go
> +func validateFloorRules(Schema openrtb_ext.PriceFloorSchema, delimiter string, RuleValues map[string]float64) []error {
Can we have structure similar to other prebid features, Ex:
`floors/core.go` -> all pkg level declarations
`floors/floors.go` -> primary feature driver
`floors/validation.go` -> all validation stuff
...

2022-05-09 04:21 UTC, pm-nilesh-chate commented on floors/resolve_floor.go
> +	schemaLen := len(Schema.Fields)
`schemaLen` is not needed

2022-05-09 04:23 UTC, pm-nilesh-chate commented on floors/resolve_floor.go
> +	if width != 0 && height != 0 {
Use  `size := CATCH_ALL`. `else` not needed

2022-05-09 04:23 UTC, pm-nilesh-chate commented on floors/resolve_floor.go
> +	var size string
Use  `size := CATCH_ALL`. `else` not needed

2022-05-09 04:24 UTC, pm-nilesh-chate commented on floors/resolve_floor.go
> +	if requestExt.Prebid.Channel != nil {
same, else not required.

2022-05-09 04:25 UTC, pm-nilesh-chate commented on floors/resolve_floor.go
> +	if err == nil {
same, else not required.

2022-05-09 04:27 UTC, pm-nilesh-chate commented on floors/resolve_floor.go
> +	for key, _ := range RuleValues {
`RuleValues` is map. No need of `_`. Use `for key := range RuleValues {`

2022-05-09 04:28 UTC, pm-nilesh-chate commented on floors/resolve_floor.go
> +	} else {
Value of `requestExt.Prebid.Floors.Enabled` is boolean. No need to compare it to `true`

2022-05-09 04:32 UTC, pm-nilesh-chate commented on floors/resolve_floor.go
> +			if imp.Banner != nil {
- Would it be wise to move the code of each case to a separate function?. Covering and maintaining all the unit test scenarios of all these cases in `CreateRuleKey` would be pain
- `value = CATCH_ALL` Seems to be default for most of the cases. Set `value := CATCH_ALL` accordingly for fewer branching.

2022-05-09 04:33 UTC, pm-nilesh-chate commented on floors/resolve_floor.go
> +			if imp.Banner != nil {
Ex.
```
case "size":
           value = getSizeValue(imp)
```
Looks clean

2022-05-09 04:41 UTC, pm-jaydeep-mohite commented on floors/resolve_floor.go
> +	floorModelErrList := validateFloorModelGroups(floorData.ModelGroups)
Done

2022-05-09 04:41 UTC, pm-jaydeep-mohite commented on floors/resolve_floor.go
> +	if shouldSkipFloors(floorData) == true {
Done

2022-05-09 04:42 UTC, pm-jaydeep-mohite commented on floors/resolve_floor.go
> +	} else {
Done

2022-05-09 04:46 UTC, pm-jaydeep-mohite commented on floors/resolve_floor.go
> +	floorErrList = validateFloorRules(floorData.ModelGroups[0].Schema, floorData.ModelGroups[0].Schema.Delimiter, floorData.ModelGroups[0].Values)
Caching shall be done after validation of model groups. 
If we validate floor rules as well then we have to validate all the model groups and at the end we would be using only one model group. 
Hence validation is done into 2 separate phases.

2022-05-09 04:50 UTC, pm-jaydeep-mohite commented on floors/resolve_floor.go
> +		updateImpExtWithFloorDetails(matchedRule, request, i)
Done

2022-05-09 04:55 UTC, pm-jaydeep-mohite commented on floors/resolve_floor.go
> +	request.Imp[i].Ext, _ = jsonparser.Set(request.Imp[i].Ext, []byte(`"`+matchedRule+`"`), "prebid", "floors", "floorRule")
imp.Ext is update for information about which floor rule is selected, this is not mandatory step hence error check is not done

2022-05-09 04:59 UTC, pm-jaydeep-mohite commented on floors/resolve_floor.go
> +			floorModelErrList = append(floorModelErrList, fmt.Errorf("Invalid Floor Model = '%v' due to ModelWeight = '%v'", modelGroup.ModelVersion, modelGroup.ModelWeight))
Along with error code we need to provide invalid value provide into floors data as well

2022-05-09 05:28 UTC, pm-jaydeep-mohite commented on floors/resolve_floor.go
> +	schemaLen := len(Schema.Fields)
Is required to check number of fields in each rule

2022-05-09 08:12 UTC, pm-jaydeep-mohite commented on floors/resolve_floor.go
> +func selectFloorModelGroup(modelGroups []openrtb_ext.PriceFloorModelGroup) {
testcases are added for UpdateImpsWithFloors()

2022-05-09 08:26 UTC, pm-nilesh-chate commented on floors/resolve_floor.go
> +	schemaLen := len(Schema.Fields)
I mean, a new why create a new variable?

2022-05-09 08:41 UTC, pm-jaydeep-mohite commented on floors/resolve_floor.go
> +	schemaLen := len(Schema.Fields)
to avoid calling len() in loop

2022-05-09 13:24 UTC, merged