Supported price floor feature
PubMatic-OpenWrap/prebid-server pull request #302
Opened 2022-05-24 12:11 UTC by pm-nikhil-vaidya

# Description

Please add change description or link to ticket, docs, etc.

# Checklist:

- [ ] PR commit list is unique (rebase/pull with the origin branch to keep master clean).
- [ ] JIRA number is added in the PR title and the commit message.
- [ ] Updated the `header-bidding` repo with appropiate commit id.
- [ ] Documented the new changes.

For Prebid upgrade, refer: https://inside.pubmatic.com:8443/confluence/display/Products/Prebid-server+upgrade

2022-05-24 16:04 UTC, Pubmatic-Dhruv-Sonone commented on floors/floors.go
> +	var floorErrList []error
Can we combine this in single var block?

2022-05-26 06:15 UTC, pm-nikhil-vaidya commented on config/config.go
> +	v.SetDefault("price_floors.enabled", false)
Add warning in validate function if floors is enabled

2022-05-26 06:24 UTC, pm-viral-vala requested changes

2022-05-26 06:24 UTC, pm-nikhil-vaidya commented on exchange/enforce_floors.go
> +package exchange
rename file to floors.go

2022-05-26 06:27 UTC, pm-nikhil-vaidya commented on floors/rule.go
> +	if isMobileDevice(request.Device.UA) == true {
remove comparison with true

2022-05-26 08:54 UTC, pm-nikhil-vaidya commented on exchange/enforce_floors.go
> +package exchange
done

2022-05-26 08:55 UTC, pm-nikhil-vaidya commented on config/config.go
> +	v.SetDefault("price_floors.enabled", false)
PriceFloors.Enabled will enforce floor feature which is still under development.

2022-05-26 08:55 UTC, pm-nikhil-vaidya commented on config/config.go
> +	v.SetDefault("price_floors.enabled", false)
Added the message

2022-05-26 08:56 UTC, pm-nikhil-vaidya commented on exchange/exchange.go
> +
Done

2022-05-26 08:56 UTC, pm-nikhil-vaidya commented on exchange/exchange.go
> +		floor: &floors.FloorConfig{
Done

2022-05-26 08:58 UTC, pm-nikhil-vaidya commented on exchange/exchange.go
> +
Done

2022-05-26 10:46 UTC, pm-nikhil-vaidya commented on floors/rule.go
> +	if isMobileDevice(request.Device.UA) == true {
done

2022-05-26 11:14 UTC, pm-nikhil-vaidya commented on exchange/exchange.go
> +
Done

2022-05-26 11:15 UTC, pm-nikhil-vaidya commented on floors/floors.go
> +	var floorErrList []error
done

2022-05-26 11:26 UTC, pm-nikhil-vaidya commented on exchange/exchange.go
> +
Will fix this with another refactoring ticket

2022-05-26 11:26 UTC, pm-nikhil-vaidya commented on exchange/exchange.go
> +
We will fix this with another refactoring ticket

2022-05-26 12:48 UTC, merged