Ott 696 master
PubMatic-OpenWrap/prebid-server pull request #362
Opened 2022-09-16 11:48 UTC by Pubmatic-Dhruv-Sonone

# Description

Please add change description or link to ticket, docs, etc.

# Checklist:

- [ ] PR commit list is unique (rebase/pull with the origin branch to keep master clean).
- [ ] JIRA number is added in the PR title and the commit message.
- [ ] Updated the `header-bidding` repo with appropiate commit id.
- [ ] Documented the new changes.

For Prebid upgrade, refer: https://inside.pubmatic.com:8443/confluence/display/Products/Prebid-server+upgrade

2022-09-20 05:50 UTC, ShriprasadM requested changes

2022-09-20 05:50 UTC, ShriprasadM commented on config/macro_processor.go
> +var once sync.Once
why we need sync.Once

2022-09-20 06:00 UTC, Pubmatic-Dhruv-Sonone commented on config/macro_processor.go
> +var once sync.Once
To have a singleton instance of macroProcessor. As the template as stored inside the macroProcessor struct, we will only need single instance of the process.

2022-09-20 09:11 UTC, ShriprasadM approved these changes
LGTM

2023-03-17 08:59 UTC, Pubmatic-Dhruv-Sonone commented
Closing this pr as changes are already merged to vanilla prebid https://github.com/prebid/prebid-server/pull/2440

2023-03-17 08:59 UTC, closed without merging