OTT:785 Logging bids rejected due to floors, advertiser and category exclusion.
PubMatic-OpenWrap/prebid-server pull request #394
Opened 2022-12-05 05:32 UTC by Pubmatic-Dhruv-Sonone

# Description

Please add change description or link to ticket, docs, etc.

# Checklist:

- [ ] PR commit list is unique (rebase/pull with the origin branch to keep master clean).
- [ ] JIRA number is added in the PR title and the commit message.
- [ ] Updated the `header-bidding` repo with appropiate commit id.
- [ ] Documented the new changes.

For Prebid upgrade, refer: https://inside.pubmatic.com:8443/confluence/display/Products/Prebid-server+upgrade

2022-12-06 10:36 UTC, Pubmatic-Dhruv-Sonone commented on exchange/exchange_test.go
> +		ctx := context.Background()
Revert the changes

2022-12-07 03:28 UTC, pm-jaydeep-mohite commented on endpoints/openrtb2/ctv_auction.go
> +		BidRequestWrapper: &openrtb_ext.RequestWrapper{BidRequest: request},
Check if we need to to add below params:

		`Warnings:                    ,
		GlobalPrivacyControlHeader:  ,
		ImpExtInfoMap:               ,
		StoredAuctionResponses:      ,
		StoredBidResponses:          ,
		BidderImpReplaceImpID:       ,`

2022-12-07 03:31 UTC, pm-jaydeep-mohite commented on exchange/floors.go
> -							RejectionReason: errortypes.BidRejectionFloorsErrorCode,
can we remove  errortypes.BidRejectionFloorsErrorCode ?

2022-12-07 03:32 UTC, ShriprasadM requested changes

2022-12-07 03:32 UTC, ShriprasadM commented on exchange/floors.go
> -							RejectionReason: errortypes.BidRejectionFloorsErrorCode,
Why have we introduced  `BidderName` ? Doesn't  `Seat` satisfies the use case?

2022-12-07 03:32 UTC, ShriprasadM commented on exchange/exchange.go
>  				}
Why we are recoding rejected bids only in case of `floors` ?  We should record rejections in other cases too
1. Advertiser Blocking
2. Category Mapping
We can create another ticket/ story (https://inside.pubmatic.com:9443/jira/browse/OTT-811)  for recording other rejections,  If this recorder was introduced as a part of floors Development and we have modified it as per need of this story.

Ideally, we should record the rejections after all pre-filtering
```
 pre-filter
 auction
 Record rejections at account / pub level
 Record rejections at account/pub and partner/bidder level
```

2022-12-07 03:32 UTC, ShriprasadM commented on exchange/exchange.go
> +	)
It's good approach. But do we really need this. It may contribute it Prebid-server upgrade conflict

2022-12-07 03:32 UTC, ShriprasadM commented on exchange/exchange.go
> +							BidderName:      string(bidderName),
Biddername vs Seat ? Why we need Biddername here?

2022-12-07 03:32 UTC, ShriprasadM commented on exchange/exchange_test.go
> +		ctx := context.Background()
Please check if exchange/exchange_test.go reverted as required

2022-12-07 03:32 UTC, ShriprasadM commented on exchange/targeting_test.go
> +	bidResp, err := ex.HoldAuction(ctx, auctionRequest, &debugLog)
assuming revert is inline with Prebid original code

2022-12-07 04:28 UTC, Pubmatic-Dhruv-Sonone commented on analytics/core_ow.go
> +	"github.com/mxmCherry/openrtb/v16/openrtb3"
Prebid Upgrade should cover those changes. The base branch does not have those changes yet.

2022-12-07 04:28 UTC, Pubmatic-Dhruv-Sonone commented on endpoints/openrtb2/auction.go
> +
Yes. This will me removed later.

2022-12-07 04:29 UTC, Pubmatic-Dhruv-Sonone commented on endpoints/openrtb2/ctv_auction.go
> +		BidRequestWrapper: &openrtb_ext.RequestWrapper{BidRequest: request},
Just moved the struct from holdAuction to here. These params are not needed.

2022-12-07 04:43 UTC, Pubmatic-Dhruv-Sonone commented on exchange/exchange.go
>  				}
@pm-jaydeep-mohite  Can you please answer, why we are recording rejected bids for floors and can we extends this to other rejections?

2022-12-07 04:44 UTC, Pubmatic-Dhruv-Sonone commented on exchange/floors.go
> -							RejectionReason: errortypes.BidRejectionFloorsErrorCode,
Will check if we can remove errortypes.BidRejectionFloorsErrorCode and create a separate story for this.

2022-12-07 07:06 UTC, Pubmatic-Dhruv-Sonone commented on exchange/exchange.go
> +	)
Reverted

2022-12-07 08:19 UTC, merged