OTT-485: Macro Replacement framework
PubMatic-OpenWrap/prebid-server pull request #432
Opened 2023-02-14 16:53 UTC by Pubmatic-Dhruv-Sonone

# Description

Please add change description or link to ticket, docs, etc.

# Checklist:

- [ ] PR commit list is unique (rebase/pull with the origin branch to keep master clean).
- [ ] JIRA number is added in the PR title and the commit message.
- [ ] Updated the `header-bidding` repo with appropiate commit id.
- [ ] Documented the new changes.

For Prebid upgrade, refer: https://inside.pubmatic.com:8443/confluence/display/Products/Prebid-server+upgrade

2023-02-15 10:52 UTC, Pubmatic-Dhruv-Sonone commented on exchange/events.go
> +			ev.macrosBuilder.WithBidRequest(requestWrapper)
Move this to exchange

2023-02-15 11:50 UTC, pm-viral-vala requested changes

2023-02-15 11:50 UTC, pm-viral-vala commented on macros/builder.go
> +	b.requestMacros["PBS-APPBUNDLE"] = reqWrapper.App.Bundle
Please use constants for macro names

2023-02-15 11:50 UTC, pm-viral-vala commented on macros/builder.go
> +	macros := map[string]string{}
Try to have single map

2023-02-16 06:06 UTC, Pubmatic-Dhruv-Sonone commented on macros/builder.go
> +	b.requestMacros["PBS-APPBUNDLE"] = reqWrapper.App.Bundle
Done

2023-02-16 06:06 UTC, Pubmatic-Dhruv-Sonone commented on macros/builder.go
> +	macros := map[string]string{}
Done

2023-02-16 06:07 UTC, Pubmatic-Dhruv-Sonone commented on macros/builder.go
> +	if reqWrapper.App.Domain != "" {
App and Site cannot be nil. Not needed

2023-02-21 12:03 UTC, pm-viral-vala requested changes

2023-02-21 12:03 UTC, pm-viral-vala commented on macros/processor/string_index_cached.go
> +	tmplt := processor.templates[url]
We can have processor.getTemplate(url) which will create a new template if not present.

2023-02-21 12:03 UTC, pm-viral-vala commented on macros/processor/string_index_cached.go
> +func (processor *stringIndexCachedProcessor) addTemplate(url string) {
rename to getTemplate() if found return that template otherwise add construct

2023-02-21 12:03 UTC, pm-viral-vala commented on macros/processor/templateBasedcached.go
> +func (processor *templateBasedCached) addTemplates(url string) {
We can have getTemplate() which will add new one if not present

2023-02-21 12:13 UTC, Pubmatic-Dhruv-Sonone commented on macros/builder.go
> +	b.macros = map[string]string{}
Outdated code. Already taken care in new code.

2023-02-21 12:13 UTC, Pubmatic-Dhruv-Sonone commented on macros/processor.go
> +
Outdated code. Already handled

2023-02-21 12:14 UTC, Pubmatic-Dhruv-Sonone commented on macros/processor.go
> +	}
Done.

2023-02-21 12:15 UTC, ShriprasadM requested changes

2023-02-21 12:15 UTC, ShriprasadM commented on exchange/events.go
> +		enabledForAccount:  account.Events.Enabled,
`account.EventsEnabled` - We are changing this to `account.Events.Enabled`

1. Have we checked its implications. account.EventsEnabled is existing flag in the prebid system

2023-02-21 12:15 UTC, ShriprasadM commented on go.mod
> +	golang.org/x/exp v0.0.0-20230213192124-5e25df0256eb
Why this module is imported?

2023-02-21 12:15 UTC, ShriprasadM commented on macros/processor/emtpyProcessor.go
> +type emptyProcessor struct{}
Add the need of this emptyProcess and some code documentation

2023-02-21 12:15 UTC, ShriprasadM commented on macros/processor/provider.go
> +		maps.Copy(b.macros, reqExt.GetPrebid().Macros)
Should we ensure there the custom key and value are honouring the length constraints defined in the PRD?

2023-02-21 12:18 UTC, Pubmatic-Dhruv-Sonone commented on exchange/events.go
> +			ev.macroProvider.UnsetContext()
Done

2023-02-21 16:34 UTC, Pubmatic-Dhruv-Sonone commented on exchange/events.go
> +	macroProcessor := processor.GetMacroProcessor()
This print function is temporary, will be removed later. We can make these changes while implementing tracking injection.

2023-02-21 16:34 UTC, Pubmatic-Dhruv-Sonone commented on macros/processor/processor.go
> +	}
Changed to NewProcessor(config) and config contains type parameter.

2023-02-21 16:35 UTC, Pubmatic-Dhruv-Sonone commented on macros/processor/processor.go
> +	}
Done

2023-02-21 16:36 UTC, Pubmatic-Dhruv-Sonone commented on go.mod
> +	golang.org/x/exp v0.0.0-20230213192124-5e25df0256eb
for go map copy function

2023-02-21 17:29 UTC, Pubmatic-Dhruv-Sonone commented on macros/processor/provider.go
> +	return b.GetAllMacros([]string{key})[key]
Done

2023-02-21 17:29 UTC, Pubmatic-Dhruv-Sonone commented on macros/processor/provider.go
> +		}
Done

2023-02-21 17:29 UTC, Pubmatic-Dhruv-Sonone commented on macros/processor/string_index_cached.go
> +	tmplt := processor.templates[url]
Done

2023-02-21 17:29 UTC, Pubmatic-Dhruv-Sonone commented on macros/processor/string_index_cached.go
> +func (processor *stringIndexCachedProcessor) addTemplate(url string) {
Done

2023-02-21 17:29 UTC, Pubmatic-Dhruv-Sonone commented on macros/processor/templateBasedcached.go
> +func (processor *templateBasedCached) addTemplates(url string) {
Done

2023-02-21 17:32 UTC, Pubmatic-Dhruv-Sonone commented on exchange/events.go
> +		enabledForAccount:  account.Events.Enabled,
Reverted to account.EventsEnabled for now.

2023-02-21 17:33 UTC, Pubmatic-Dhruv-Sonone commented on macros/processor/provider.go
> +			macroValues[key] = b.macros[key]
Refactored to use macros map here. Yes if key is not present , macro will be empty

2023-02-22 05:31 UTC, Pubmatic-Dhruv-Sonone commented on macros/processor/provider.go
> +		maps.Copy(b.macros, reqExt.GetPrebid().Macros)
done

2023-02-22 05:34 UTC, Pubmatic-Dhruv-Sonone commented on macros/processor/emtpyProcessor.go
> +type emptyProcessor struct{}
Done

2023-02-22 05:34 UTC, Pubmatic-Dhruv-Sonone commented on macros/processor/provider.go
> +}
Done

2023-02-22 05:34 UTC, Pubmatic-Dhruv-Sonone commented on macros/processor/provider.go
> +	b.imp = nil
Done

2023-02-22 05:41 UTC, ShriprasadM commented on exchange/events.go
> +		enabledForAccount:  account.Events.Enabled,
I hope, we are still referring to `account.events.enabled` in our implementation
and not `account.eventsenabled`

2023-02-22 05:42 UTC, ShriprasadM commented on go.mod
> +	golang.org/x/exp v0.0.0-20230213192124-5e25df0256eb
Have we checked the vulnerability and its performance? Prebid team may have the same question

2023-02-22 05:48 UTC, Pubmatic-Dhruv-Sonone commented on go.mod
> +	golang.org/x/exp v0.0.0-20230213192124-5e25df0256eb
It's an official golang implementation. I have removed it now as implementation has changed a bit.

2023-02-22 05:54 UTC, Pubmatic-Dhruv-Sonone commented on macros/processor.go
> +type Config struct {
done

2023-02-22 05:54 UTC, Pubmatic-Dhruv-Sonone commented on macros/string_based.go
> +func (processor *stringBased) Replace(str string, macroValues map[string]string) (string, error) {
done

2023-02-22 05:54 UTC, Pubmatic-Dhruv-Sonone commented on macros/templateBased.go
> +	re := regexp.MustCompile(regex)
done

2023-02-22 05:56 UTC, ShriprasadM commented on macros/processor/provider.go
> +		maps.Copy(b.macros, reqExt.GetPrebid().Macros)
https://github.com/PubMatic-OpenWrap/prebid-server/blob/OTT-485/macros/processor/provider.go#L51 - I could see we are checking length of the macro key > 110

Here I could see, implementation is not inline with PRD for custom macros - https://docs.google.com/document/d/1a-U1DytiCTtacM27qH3OZwhPa7bDwQzfpVRHDhyikWw/edit?usp=sharing

1. It is not expected that `reqExt.Prebid` will contain macros with `PBS-MACRO-` prefix. So, if I want to populate value of colour as red inside events url then
> events url  = http://someurl.com?clr=##PBS-MACRO-colour##
> reqExt.prebid.macros = { "colour" : "red" }
2. So, while scanning events url - take off the first 10 chars and consider the remaining chars to be the attribute name.  PBS-MACRO-colour => colour
3.  We are not truncating on value part as per PRD - Look for this attribute in ext.prebid.macros.ATTR, truncate the value at 100 chars,
4. URL-encode the value - We are not url -encoding the value
5. If the value is not present, replace the value with an empty string. (I think its handled)

2023-02-22 06:11 UTC, Pubmatic-Dhruv-Sonone commented on macros/processor/provider.go
> +		maps.Copy(b.macros, reqExt.GetPrebid().Macros)
@ShriprasadM  I don't its possible to implement 2nd point with the template based approach, as we don't scan the url.
One way to handle this would be to add prefix **##PBS-Macro-**  to the custom macro, while adding it to the macro map, this way we can have a exact match of url and custom macros.

2023-02-22 06:18 UTC, Pubmatic-Dhruv-Sonone commented on macros/processor/provider.go
> +		maps.Copy(b.macros, reqExt.GetPrebid().Macros)
PRD says `Look for this attribute in ext.prebid.macros.ATTR, truncate the value at 100 chars` so do we need to only limit the custom macro value to 100 chars or do we need this check for all the values?

2023-02-22 06:24 UTC, ShriprasadM commented on macros/processor/provider.go
> +		maps.Copy(b.macros, reqExt.GetPrebid().Macros)
@Pubmatic-Dhruv-Sonone : Yes, I feel, we can handle it, in the way you have mentioned, in general for any approach,  unless and until its not impacting the performance and expectations that PRD have set in terms of user input ( #1)

2023-02-22 06:26 UTC, ShriprasadM commented on macros/processor/provider.go
> +		maps.Copy(b.macros, reqExt.GetPrebid().Macros)
> PRD says `Look for this attribute in ext.prebid.macros.ATTR, truncate the value at 100 chars` so do we need to only limit the custom macro value to 100 chars or do we need this check for all the values?

at least as per PRD its only for custom macros. May be you can put this question in upcoming Prebid Syncup

2023-02-22 08:57 UTC, Pubmatic-Dhruv-Sonone commented on exchange/events.go
> +		enabledForAccount:  account.Events.Enabled,
@ShriprasadM macro processing related code refers to `accounts.events.enabled` now. But the existing events endpoints still uses `account.eventsenabled`. We can check with prebid-team if that also needs to be changed.

2023-02-22 08:57 UTC, Pubmatic-Dhruv-Sonone commented on macros/builder.go
> +	if reqWrapper.App.Domain != "" {
Done

2023-02-22 08:57 UTC, Pubmatic-Dhruv-Sonone commented on macros/processor.go
> +type Type int
Done

2023-02-22 08:59 UTC, Pubmatic-Dhruv-Sonone commented
@pm-viral-vala @ShriprasadM Addressed the above review comments and added benchmark. Will add test cases once the implementation is approved.

2023-02-22 09:49 UTC, pm-viral-vala requested changes

2023-02-22 17:11 UTC, Pubmatic-Dhruv-Sonone commented on macros/processor/templateBasedcached.go
> +		tmplate = tmplWrapper
Done

2023-02-28 05:44 UTC, ShriprasadM commented on exchange/events.go
> +		enabledForAccount:  account.Events.Enabled,
@Pubmatic-Dhruv-Sonone , this is already been discussed with Prebid team. The plan here is to deprecate `account.eventsenabled` and move on to `accounts.events.enabled`. As per as we are using new flag in Video Events modules, its fine for now

2023-02-28 05:47 UTC, ShriprasadM approved these changes
LGTM

2023-03-06 11:33 UTC, merged