OTT-423: Deprecate events_enabled field
PubMatic-OpenWrap/prebid-server pull request #447
Opened 2023-03-13 03:57 UTC by ashishshinde-pubm

2023-03-17 07:45 UTC, ShriprasadM requested changes
Check review comments

2023-03-17 07:45 UTC, ShriprasadM commented on config/config.go
> -	}
Stop server if events has vast events configured or default url is set

2023-03-17 07:45 UTC, ShriprasadM commented on config/config.go
> +	c.AccountDefaults.Events.Enabled = nil
Check if this is required

2023-03-17 07:45 UTC, ShriprasadM commented on config/config_test.go
> +			description: "only newField is set",
old field is not set, use new field value

2023-03-17 07:45 UTC, ShriprasadM commented on config/config_test.go
> +			description: "oldField and newField both are set",
override old Field value with new field value

2023-03-17 07:45 UTC, ShriprasadM commented on config/events.go
> +	Enabled    *bool       `mapstructure:"enabled" json:"enabled"`
Assuming pointer introduction is temporary. Once we move away from deprecation of `events_enabled`, we should remove pointer here

2023-03-17 07:45 UTC, ShriprasadM commented on exchange/events.go
> +		enabledForAccount:  account.Events.Enabled != nil && *account.Events.Enabled,
What if we add the isEnabled method instead

2023-03-17 07:45 UTC, ShriprasadM commented on exchange/exchange_test.go
> +	EventsEnabled              *bool                  `json:"events_enabled,omitempty"`
Why we need this change? events_enabled is not pointer

2023-03-17 09:26 UTC, ashishshinde-pubm commented on account/account.go
> +	if account.Events.Enabled == nil {
Done

2023-03-17 09:28 UTC, ashishshinde-pubm commented on account/account_test.go
> +	boolTrue := true
Done

2023-03-17 09:29 UTC, ashishshinde-pubm commented on account/account_test.go
> +				EventsEnabled: true,
Done

2023-03-17 10:54 UTC, ashishshinde-pubm commented on config/config.go
> +	c.AccountDefaults.Events.Enabled = nil
Yes, it is required so explicitly set the value to nil.
Example :
host-level events_enabled : false
host-level events.enabled : true 
account-level events_enabled : false 
account-level events.enabled : not-set  ---> in account Json there will be no entry for this field.
Hence, merged Json will consider the final  events.enabled as true from host-level events.enabled. 
But as per precedence we should honour account-level events_enabled field prior to host-level events.enabled

2023-03-17 10:56 UTC, ashishshinde-pubm commented on config/config_test.go
> +			description: "only newField is set",
changed the description

2023-03-17 11:14 UTC, ashishshinde-pubm commented on config/events.go
> +	Enabled    *bool       `mapstructure:"enabled" json:"enabled"`
noted.

2023-03-17 11:19 UTC, ashishshinde-pubm commented on exchange/events.go
> +		enabledForAccount:  account.Events.Enabled != nil && *account.Events.Enabled,
okay

2023-03-17 11:32 UTC, ashishshinde-pubm commented on exchange/exchange_test.go
> +	EventsEnabled              *bool                  `json:"events_enabled,omitempty"`
kept it as it is.

2023-03-17 11:35 UTC, ashishshinde-pubm commented on account/account.go
will check the comment of Prebid-team, accordingly will make the changes.

2023-03-20 03:39 UTC, ashishshinde-pubm commented on config/config.go
> -	}
ok

2023-03-27 04:01 UTC, ashishshinde-pubm commented on account/account.go
As per prebid teams comment, we will not add the prometheus metric since they are going to change the design of fetcher, also it is good to have feature and not mandatory feature.

2023-03-27 07:12 UTC, ShriprasadM approved these changes
LGTM

2023-03-27 09:58 UTC, merged