OTT-1007: As a OpenWrap Server user, I should be able to log floor de…
PubMatic-OpenWrap/prebid-server pull request #478
Opened 2023-04-24 11:38 UTC by Pubmatic-Supriya-Patil

…tails with soft floor type

# Description

Please add change description or link to ticket, docs, etc.

# Checklist:

- [ ] PR commit list is unique (rebase/pull with the origin branch to keep master clean).
- [ ] JIRA number is added in the PR title and the commit message.
- [ ] Updated the `header-bidding` repo with appropiate commit id.
- [ ] Documented the new changes.

For Prebid upgrade, refer: https://inside.pubmatic.com:8443/confluence/display/Products/Prebid-server+upgrade

2023-04-25 06:10 UTC, pm-nilesh-chate commented on exchange/floors.go
> +func updateBidExt(bidRequestWrapper *openrtb_ext.RequestWrapper, seatBids map[openrtb_ext.BidderName]*entities.PbsOrtbSeatBid) {
Add UT for this function

2023-04-25 06:23 UTC, pm-nilesh-chate requested changes

2023-04-25 06:23 UTC, pm-nilesh-chate commented on exchange/floors.go
> +	updateBidExt(r.BidRequestWrapper, seatBids)
Update UT for this function w.r.t to `updateBidExt ` changes.

2023-04-25 06:23 UTC, pm-nilesh-chate commented on exchange/floors.go
> +			}
This logic contradicts with request parsing logic in header-bidding (`updateImpFloorDefaultCurrency`).
1. Header-bidding sets default request to `USD`
2. OW-PBS sets default request to `request.Cur[0]`
Please address the same and do the needful.

2023-04-25 06:23 UTC, pm-nilesh-chate commented on exchange/floors.go
> +			if reqImpCur == "" {
request/floor currency is already decided at request parsing. We can omit this duplicate logic

2023-04-25 12:03 UTC, pm-jaydeep-mohite commented on exchange/floors_test.go
> +		t.Run(tt.name, func(t *testing.T) {
Remove t.Run(tt.name, func(t *testing.T) {}

2023-04-26 09:32 UTC, pm-jaydeep-mohite approved these changes
LGTM

2023-04-26 09:32 UTC, merged

2023-04-27 06:53 UTC, pm-nilesh-chate commented on exchange/floors.go
> +			}
@pm-jaydeep-mohite please address this comment