OTT-1043: fv key passing with incorrect value in logger when no rule …
PubMatic-OpenWrap/prebid-server pull request #479
Opened 2023-04-27 09:34 UTC by Pubmatic-Supriya-Patil

…is matched and default value of model is selected as bidfloor.

# Description

Please add change description or link to ticket, docs, etc.

# Checklist:

- [ ] PR commit list is unique (rebase/pull with the origin branch to keep master clean).
- [ ] JIRA number is added in the PR title and the commit message.
- [ ] Updated the `header-bidding` repo with appropiate commit id.
- [ ] Documented the new changes.

For Prebid upgrade, refer: https://inside.pubmatic.com:8443/confluence/display/Products/Prebid-server+upgrade

2023-05-04 05:35 UTC, pm-nilesh-chate requested changes
nitpick: Title should be short and descriptive.
Ex. OTT-1043: fix fv in logger when floor rule not found

2023-05-04 05:35 UTC, pm-nilesh-chate commented on floors/rule.go
>  		FloorValue:     floorVal,
should add test case to assert this behaviour for future changes. This applies for the above file changes as well.

2023-05-04 05:42 UTC, pm-nilesh-chate commented on exchange/floors.go
> -			}
update tests for this change. Ex. `TestUpdateBidExt`

2023-05-04 08:48 UTC, pm-nilesh-chate approved these changes
Approved. do not merge until master drop is finalised

2023-05-25 03:43 UTC, Pubmatic-Supriya-Patil commented on floors/rule.go
>  		FloorValue:     floorVal,
Added UT's.

2023-05-25 08:09 UTC, pm-nilesh-chate commented on exchange/floors.go
> +		bid.BidFloors = &bidExtFloors
bid.BidFloors = &openrtb_ext.ExtBidFloors{
    FloorRule: prebidExt.Floors.FloorRule,
    FloorRuleValue: prebidExt.Floors.FloorRuleValue,
    FloorValue: prebidExt.Floors.FloorValue,
    FloorCurrency: floorCurrency,
}

2023-05-25 08:10 UTC, pm-nilesh-chate commented on exchange/floors.go
> +			bid.BidFloors = &bidExtFloors
```
bid.BidFloors = &openrtb_ext.ExtBidFloors{
    FloorValue: prebidExt.Floors.FloorValue,
    FloorCurrency: floorCurrency,
}
```

2023-05-25 08:26 UTC, pm-nilesh-chate commented on exchange/floors.go
> +			updateBidExtWithFloors(reqImp, bid, reqImp.BidFloorCur)
currency UT cases should be part of `updateBidExtWithFloors`. `updateBidExt` is not responsible for changes to currency. Move the test cases accordingly

2023-05-25 08:26 UTC, pm-nilesh-chate commented on exchange/floors.go
> +				continue
please cover impID to bid.impId UT cases

2023-05-25 08:26 UTC, pm-nilesh-chate commented on exchange/floors.go
> +			updateBidExtWithFloors(reqImp, bid, reqImp.BidFloorCur)
Not need to pass `reqImp.BidFloorCur` separately

2023-05-25 08:27 UTC, pm-nilesh-chate requested changes
requested minor refactor

2023-05-25 10:45 UTC, pm-viral-vala requested changes

2023-05-25 10:45 UTC, pm-viral-vala commented on exchange/floors.go
> +	} else {
There is no need to have else block as we are returning from if block as is.

2023-05-25 10:52 UTC, pm-viral-vala approved these changes

2023-05-25 11:51 UTC, merged