OTT-1009: As a Prebid Server user, pass VAST un-wrapper flag from request context to ExecuteRawBidderResponseStage()
PubMatic-OpenWrap/prebid-server pull request #480
Opened 2023-04-28 10:18 UTC by Pubmatic-Supriya-Patil

# Description

Please add change description or link to ticket, docs, etc.

# Checklist:

- [ ] PR commit list is unique (rebase/pull with the origin branch to keep master clean).
- [ ] JIRA number is added in the PR title and the commit message.
- [ ] Updated the `header-bidding` repo with appropiate commit id.
- [ ] Documented the new changes.

For Prebid upgrade, refer: https://inside.pubmatic.com:8443/confluence/display/Products/Prebid-server+upgrade

2023-05-02 07:54 UTC, pm-nilesh-chate commented on modules/pubmatic/openwrap/entryhook.go
> +	result := hookstage.HookResult[hookstage.EntrypointPayload]{}
add reject true by default

2023-05-02 08:06 UTC, pm-nilesh-chate commented on modules/pubmatic/openwrap/entryhook_test.go
> +		},
Keep scope of test data specific to that test. Ex:
```
payload : hookstage.EntrypointPayload{
          Request: func() *http.Request {
                 ctx := context.WithValue(context.Background(), "enableVastUnwrapper", false)
                 r := http.RequestWithContext(ctx)
                 return &r
          }()
},
```

2023-05-02 08:08 UTC, pm-nilesh-chate commented on modules/pubmatic/openwrap/entryhook_test.go
> +		})
Do not set `ModuleContext` here. It should be set by `handleEntrypointHook` and the want assertion should check   if formal and actual parameters are same and the `ModuleContext` is updated with `rctx` data.

2023-05-02 08:09 UTC, pm-nilesh-chate commented on modules/pubmatic/openwrap/hook_raw_bidder_response.go
> +	util.JLogf("VastUnwrapperEnable", rCtx.VastUnwrapFlag)
remove this log

2023-05-02 08:10 UTC, pm-nilesh-chate commented on modules/pubmatic/openwrap/hook_raw_bidder_response.go
> +		fmt.Printf("\n **** VAST unwrapping Disabled **** !!!! ")
Remove printf, etc logs. Dev/QA can refer module's debug messages is any info is needed.

2023-05-02 08:11 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/openwrap/hook_raw_bidder_response.go
> +	util.JLogf("VastUnwrapperEnable", rCtx.VastUnwrapFlag)
This log is required for testing this story.

2023-05-02 08:12 UTC, pm-nilesh-chate commented on modules/pubmatic/openwrap/module.go
> +}
module type declaration to new package `models`.

2023-05-02 08:12 UTC, pm-nilesh-chate commented on modules/pubmatic/openwrap/module.go
> +	return handleEntrypointHook(ctx, miCtx, payload)
Add panic recovery to all the modules. Refer https://github.com/PubMatic-OpenWrap/prebid-server/pull/453/commits/574120c59fbbbe39d4c7cdaf14beee9693e483fc

2023-05-02 08:14 UTC, pm-nilesh-chate commented on modules/pubmatic/openwrap/entryhook.go
> +	vastEnableUnwrapper, _ := ctx.Value(field).(string)
this will panic if field is not available. separate the assertion

2023-05-02 08:14 UTC, pm-nilesh-chate requested changes
Add a README to module on added hooks and their structure along with sample config file

2023-05-02 08:22 UTC, pm-nilesh-chate commented on modules/pubmatic/openwrap/hook_raw_bidder_response.go
> +	util.JLogf("VastUnwrapperEnable", rCtx.VastUnwrapFlag)
Such logs without any relevant details should not be used. Also, These changes do not look like deliverables. I would suggest to mark this as north-star and not merge the PR and give a drop once end to end use case is completed.

2023-05-02 09:17 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/openwrap/hook_raw_bidder_response.go
> +	util.JLogf("VastUnwrapperEnable", rCtx.VastUnwrapFlag)
This is north-star story

2023-05-02 09:20 UTC, Pubmatic-Supriya-Patil commented
> Add a README to module on added hooks and their structure along with sample config file

This story is just to log vastUnwrapperEnable flag inside raw bidder resp where its actually getting used. So this is just sample module that we have added. We will update it and add README and config file as part of further development stories.

2023-05-02 09:20 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/openwrap/module.go
> +	return handleEntrypointHook(ctx, miCtx, payload)
This is just sample module, we will add as part of next development stories.

2023-05-02 09:42 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/openwrap/entryhook.go
> +func getContextValueForField(ctx context.Context, field string) bool {
Change method name to getVastUnwrapperEnable

2023-05-02 09:43 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/openwrap/entryhook.go
> +		VastUnwrapFlag: getContextValueForField(payload.Request.Context(), "enableVastUnwrapper"),
Add constant for enableVastUnwrapper

2023-05-02 09:46 UTC, pm-nikhil-vaidya commented on modules/pubmatic/openwrap/entryhook.go
> +	result.ModuleContext["rctx"] = rCtx
while storing name, use vendor name openwrap as well in key

2023-05-02 09:50 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/openwrap/entryhook.go
> +	result.ModuleContext["rctx"] = rCtx
check what should be the key name for ModuleContext

2023-05-02 09:50 UTC, Pubmatic-Dhruv-Sonone requested changes

2023-05-02 09:50 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/entryhook.go
> +	if vastEnableUnwrapper == "1" || strings.ToLower(vastEnableUnwrapper) == "true" {
Use `strconv.ParseBool` instead of  `strings.ToLower(vastEnableUnwrapper) == "true"`

2023-05-02 09:50 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/entryhook.go
> +}
Remove if blocks and write as  `return vastEnableUnwrapper == "1" || strings.ToLower(vastEnableUnwrapper) == "true"`

2023-05-02 09:57 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/openwrap/entryhook_test.go
> +		t.Run(tt.name, func(t *testing.T) {
Update Test case and make its scope limited to TC only

2023-05-02 09:59 UTC, Pubmatic-Dhruv-Sonone requested changes

2023-05-02 09:59 UTC, Pubmatic-Dhruv-Sonone commented on go.mod
>  	github.com/NYTimes/gziphandler v1.1.1
Go.mod and go.sum changes don't seem  relevant to the pr can we remove this changes?

2023-05-02 09:59 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/module.go
> +// HandleBidderRequestHook updates blocking fields on the openrtb2.BidRequest.
Add comments relevant to the function

2023-05-02 10:00 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/openwrap/hook_raw_bidder_response.go
> +	rCtx, ok := moduleCtx["rctx"].(RequestCtx)
make rctx as constant

2023-05-02 10:01 UTC, Pubmatic-Dhruv-Sonone requested changes

2023-05-02 10:01 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/module.go
> +}
Add comments relevant to the functions

2023-05-02 10:06 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/openwrap/hook_raw_bidder_response.go
> +	defer func() {
remove defer part

2023-05-02 10:10 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/module.go
> +	var err error
`err` var  is not being used. Remove and return nil.

2023-05-02 10:12 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/module.go
> +}
write as `return  hookstage.HookResult[hookstage.BidderRequestPayload]{}, nil`

2023-05-02 10:13 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/module.go
> +	UA             string
Add a comment describing UA usage.

2023-05-02 10:20 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/openwrap/entryhook.go
> +	result := hookstage.HookResult[hookstage.EntrypointPayload]{}
hookstage.HookResult[hookstage.EntrypointPayload]{reject: true}

2023-05-02 10:32 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/openwrap/entryhook.go
> +	result.ModuleContext["rctx"] = rCtx
This is already done and we can use any name inside modulecontext

2023-05-02 10:32 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/openwrap/entryhook.go
> +	result.ModuleContext["rctx"] = rCtx
Already decided to have as it is

2023-05-02 10:33 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/openwrap/hook_raw_bidder_response.go
> +	defer func() {
If we are not updating rCtx then we can remove this defer

2023-05-02 10:33 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/entryhook_test.go
> +			vastUnwrapper := "0"
`vastUnwrapper` no need to set this you can directly pass the` tt.args.enableVastUnwrapper` to WithValue

2023-05-02 10:36 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/entryhook.go
> +	vastEnableUnwrapper, _ := ctx.Value(field).(string)
Context can hold boolean value. Can we store `vastEnableUnwrapper ` value as bool instead of string in ctx?

2023-05-02 10:52 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/openwrap/entryhook.go
> +	if vastEnableUnwrapper == "1" || strings.ToLower(vastEnableUnwrapper) == "true" {
strconv.ParseBool will return 2 values so its good to have strings.ToLower(vastEnableUnwrapper) == "true" to return in single statement

2023-05-02 14:33 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/openwrap/entryhook.go
> +	vastEnableUnwrapper, _ := ctx.Value(field).(string)
Updated

2023-05-02 14:33 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/openwrap/entryhook.go
> +	result := hookstage.HookResult[hookstage.EntrypointPayload]{}
Addressed

2023-05-02 14:35 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/openwrap/hook_raw_bidder_response.go
> +	defer func() {
Addressed

2023-05-02 14:36 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/openwrap/hook_raw_bidder_response.go
> +	rCtx, ok := moduleCtx["rctx"].(RequestCtx)
Updated

2023-05-02 14:36 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/openwrap/entryhook.go
> +		VastUnwrapFlag: getContextValueForField(payload.Request.Context(), "enableVastUnwrapper"),
Updated

2023-05-02 14:37 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/openwrap/entryhook.go
> +func getContextValueForField(ctx context.Context, field string) bool {
Addressed

2023-05-02 14:37 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/openwrap/module.go
> +}
Addressed

2023-05-02 14:38 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/openwrap/hook_raw_bidder_response.go
> +	util.JLogf("VastUnwrapperEnable", rCtx.VastUnwrapFlag)
Removed log statement

2023-05-02 14:38 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/openwrap/entryhook_test.go
> +		})
Updated

2023-05-02 14:38 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/openwrap/entryhook_test.go
> +		},
Updated

2023-05-02 14:38 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/openwrap/entryhook.go
> +	result := hookstage.HookResult[hookstage.EntrypointPayload]{}
Updated

2023-05-02 14:41 UTC, Pubmatic-Supriya-Patil commented on go.mod
>  	github.com/NYTimes/gziphandler v1.1.1
This is I think from ci branch only

2023-05-02 14:42 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/openwrap/entryhook.go
> +	vastEnableUnwrapper, _ := ctx.Value(field).(string)
We are using it as string from HB also so kept it as string.

2023-05-02 14:43 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/openwrap/entryhook.go
> +	vastEnableUnwrapper, _ := ctx.Value(field).(string)
Field will always be sent from header bidding side, It can be "0" or "1"

2023-05-03 04:14 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/entryhook.go
> +	if vastEnableUnwrapper == "1" || strings.ToLower(vastEnableUnwrapper) == "true" {
can be written as `if  enable, err := strconv.ParseBool(vastEnableUnwrapper) ; vastEnableUnwrapper == "1" || enable{`

Using `strings.ToLower(vastEnableUnwrapper) == "true"` will return false even incase of invalid input.

2023-05-03 04:18 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/openwrap/entryhook.go
> +	if vastEnableUnwrapper == "1" || strings.ToLower(vastEnableUnwrapper) == "true" {
I have removed check for true value as we know this will be either "0" or "1"

2023-05-03 10:04 UTC, Pubmatic-Dhruv-Sonone approved these changes

2023-05-03 10:21 UTC, pm-jaydeep-mohite approved these changes
LGTM

2023-05-03 10:22 UTC, merged