OTT-1062: Integrate vast unwrapper as library
PubMatic-OpenWrap/prebid-server pull request #503
Opened 2023-06-02 09:52 UTC by Pubmatic-Supriya-Patil

# Description

Please add change description or link to ticket, docs, etc.

# Checklist:

- [ ] PR commit list is unique (rebase/pull with the origin branch to keep master clean).
- [ ] JIRA number is added in the PR title and the commit message.
- [ ] Updated the `header-bidding` repo with appropiate commit id.
- [ ] Documented the new changes.

For Prebid upgrade, refer: https://inside.pubmatic.com:8443/confluence/display/Products/Prebid-server+upgrade

2023-06-02 11:55 UTC, pm-jaydeep-mohite commented on modules/builder.go
> +			"openwrap": vastunwrap.Builder,
Can we make it 
`"vastunwrap": vastunwrap.Builder,`

2023-06-02 11:56 UTC, pm-jaydeep-mohite commented on modules/pubmatic/vastunwrap/hook_raw_bidder_response.go
> +	fmt.Printf("\n UnWrap Done for BidId = %v Cnt = %v in %v (ms)", bidid, wrapperCnt, respTime)
add it as Debug print log

2023-06-05 06:55 UTC, Pubmatic-Supriya-Patil commented on modules/builder.go
> +			"openwrap": vastunwrap.Builder,
Done

2023-06-05 06:55 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/vastunwrap/hook_raw_bidder_response.go
> +	fmt.Printf("\n UnWrap Done for BidId = %v Cnt = %v in %v (ms)", bidid, wrapperCnt, respTime)
Updated to glog.info

2023-06-06 04:41 UTC, pm-jaydeep-mohite commented on modules/pubmatic/vastunwrap/constant.go
> +const (
Add only required constants

2023-06-06 06:39 UTC, ashishshinde-pubm commented on modules/pubmatic/vastunwrap/config.go
> +package vastunwrap
can you plz confirm , do we need this file ?

2023-06-06 08:54 UTC, Pubmatic-Dhruv-Sonone requested changes

2023-06-06 08:54 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/vastunwrap/hook_raw_bidder_response.go
> +	httpResp := httptest.NewRecorder()
Don't use httptest

2023-06-06 08:54 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/vastunwrap/module.go
> +type VastUnwrapModuleCfg struct {
Do you plan to add move config fields in this struct? Else we can remove this can move **VastUnWrapCfg unWrapCfg.VastUnWrapCfg** inside` VastUnwrapModule`

2023-06-06 10:01 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/vastunwrap/hook_raw_bidder_response.go
> +		respChan <- &models.UnwrapReq{Err: error(fmt.Errorf("Unexpected status code: %d. Run with request.debug = 1 for more info", httpResp.Code))}
we can remove error wrapping

2023-06-06 10:01 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/vastunwrap/hook_raw_bidder_response.go
> +	fmt.Printf("\n UnWrap Done for BidId = %v Cnt = %v in %v (ms)", bidid, wrapperCnt, respTime)
This is just to know details about unwrapping

2023-06-06 10:03 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/vastunwrap/hook_raw_bidder_response.go
> +func vastUnwrapCreative(input string, userAgent, bidid string, respChan chan<- *models.UnwrapReq) {
Added

2023-06-06 10:05 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/vastunwrap/module.go
> +type VastUnwrapModuleCfg struct {
This should be same as per config we are receiving from yaml

2023-06-06 10:08 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/vastunwrap/hook_raw_bidder_response_test.go
> +			}
we are just checking if error is not nil then return from the Unit test cases. we dont want to assert here

2023-06-06 10:11 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/vastunwrap/hook_raw_bidder_response.go
> +		respChan <- &models.UnwrapReq{Err: err}
I think you should end the function call after `respChan <- &models.UnwrapReq{Err: err}` else the next statement `httpReq.Header = headers` will panic

2023-06-06 10:18 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/vastunwrap/hook_raw_bidder_response_test.go
> +			}
we can use assert.Error/ assert.NoError functions, just to stay consistent with Vanilla prebid

2023-06-06 10:22 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/vastunwrap/hook_raw_bidder_response.go
> +	httpResp := httptest.NewRecorder()
Is there any way to create obj of response writer. we need to pass that to unwrap function

2023-06-06 10:23 UTC, pm-nikhil-vaidya commented on modules/pubmatic/vastunwrap/entryhook.go
>  	rCtx := models.RequestCtx{
can you please update name of rctx

2023-06-06 10:50 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/vastunwrap/entryhook.go
>  	rCtx := models.RequestCtx{
Updated

2023-06-06 15:00 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/vastunwrap/constant.go
> +const (
All of above from this file are required

2023-06-06 15:06 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/vastunwrap/hook_raw_bidder_response.go
> +		respChan <- &models.UnwrapReq{Err: err}
Yes, I will add return respChan <- &models.UnwrapReq{Err: err}

2023-06-07 01:25 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/vastunwrap/constant.go
> +	UnwrapCount            = "unwrap-count"
Yes, But in future we can use this instead of declaring new one

2023-06-07 01:36 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/vastunwrap/hook_raw_bidder_response_test.go
> +			}
Updated with assert.NoError

2023-06-07 01:38 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/vastunwrap/hook_raw_bidder_response.go
> +	fmt.Printf("\n UnWrap Done for BidId = %v Cnt = %v in %v (ms)", bidid, wrapperCnt, respTime)
Updated with glog.info

2023-06-07 01:40 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/vastunwrap/hook_raw_bidder_response.go
> +		bidMediaTypes := mediaTypesFromBid(bid)
Used as same in ortb2blocking

2023-06-07 05:45 UTC, ShriprasadM requested changes

2023-06-07 05:45 UTC, ShriprasadM commented on modules/pubmatic/vastunwrap/constant.go
> +	MediaTypeVideo         = "video"
Move to vault configuration

2023-06-07 05:45 UTC, ShriprasadM commented on modules/pubmatic/vastunwrap/entryhook.go
>  		VastUnwrapFlag: getVastUnwrapperEnable(payload.Request.Context(), VastUnwrapperEnableKey),
rename `VastUnwrapFlag` to `isVastUnwrapEnabled`. It will  be more readable.
same for function name. Rename `getVastUnwrapperEnable` to `isVastUnwrapEnabled`.

2023-06-07 05:45 UTC, ShriprasadM commented on modules/pubmatic/vastunwrap/constant.go
> +	VastUnwrapperEnableKey = "enableVastUnwrapper"
Let us keep the naming consistent. We have module name as `vastunwrap`.  
Rename `VastUnwrapperEnableKey` constant to  `isVastUnWrapEnabled`

2023-06-07 05:45 UTC, ShriprasadM commented on modules/pubmatic/vastunwrap/hook_raw_bidder_response.go
> +			go vastUnwrapCreative(bid.Bid.AdM, vastRequestContext.UA, bid.Bid.ID, responseChannel)
instead of `vastUnwrapCreative` can we rename it to `doUnwrap`. 
1. it will be readable 
2. we are in `vastunwrap` module, we can drop vast word. 
3. method is private
4. Even we are always going to `unwrap` the creative, no need to mention `creative`  in explicitly

2023-06-07 05:45 UTC, ShriprasadM commented on modules/pubmatic/vastunwrap/hook_raw_bidder_response.go
> +	responseChannel := make(chan *models.UnwrapReq, len(payload.Bids))
`responseChannel` is too generic. rename it to `unwrapRespChannel`

2023-06-07 05:45 UTC, ShriprasadM commented on modules/pubmatic/vastunwrap/hook_raw_bidder_response.go
> +		unwrapInfo := <-responseChannel
rename `unwrapInfo` to `unwrapResponse`

2023-06-07 05:45 UTC, ShriprasadM commented on modules/pubmatic/vastunwrap/hook_raw_bidder_response.go
> +func vastUnwrapCreative(input string, userAgent, bidid string, respChan chan<- *models.UnwrapReq) {
move this to separate go file, say `unwrap_service.go`. this file is responsible for intercepting raw bid response and modify it. it should maintain - `how to unwrap the vast implementation`

2023-06-07 05:45 UTC, ShriprasadM commented on modules/pubmatic/vastunwrap/hook_raw_bidder_response.go
> +	for i := 0; i < len(payload.Bids); i++ {
instead of maintaining `unwrapCrMap` , how about passing bid object to `unwrap service` and updating ADM there when its a success?

Here, we are looping twice.
1. forming the `unwrapCrMap`
2. for updating ADM using `unwrapCrMap`

2023-06-07 06:11 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/vastunwrap/hook_raw_bidder_response.go
> +	httpResp := httptest.NewRecorder()
Write custom implementation of ResponseWriter interface or Change library implementation.

2023-06-13 05:00 UTC, pm-jaydeep-mohite commented on modules/pubmatic/vastunwrap/constant.go
> +	UnwrapTimeoutValue  = "1000"
can we remove `UnwrapTimeoutValue` ?

2023-06-13 06:23 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/vastunwrap/constant.go
> +	UnwrapTimeoutValue  = "1000"
Removed

2023-06-13 06:23 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/vastunwrap/hook_raw_bidder_response.go
> +	for i := 0; i < len(payload.Bids); i++ {
Updated code as per suggestion

2023-06-13 06:23 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/vastunwrap/hook_raw_bidder_response.go
> +func vastUnwrapCreative(input string, userAgent, bidid string, respChan chan<- *models.UnwrapReq) {
done

2023-06-13 06:23 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/vastunwrap/hook_raw_bidder_response.go
> +		unwrapInfo := <-responseChannel
Done

2023-06-13 06:24 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/vastunwrap/hook_raw_bidder_response.go
> +	responseChannel := make(chan *models.UnwrapReq, len(payload.Bids))
Done

2023-06-13 06:24 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/vastunwrap/hook_raw_bidder_response.go
> +			go vastUnwrapCreative(bid.Bid.AdM, vastRequestContext.UA, bid.Bid.ID, responseChannel)
done

2023-06-13 06:24 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/vastunwrap/constant.go
> +	VastUnwrapperEnableKey = "enableVastUnwrapper"
done

2023-06-13 06:24 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/vastunwrap/entryhook.go
>  		VastUnwrapFlag: getVastUnwrapperEnable(payload.Request.Context(), VastUnwrapperEnableKey),
done

2023-06-13 06:25 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/vastunwrap/constant.go
> +	MediaTypeVideo         = "video"
This are the constant specific to vastunwrap model

2023-06-13 06:47 UTC, ShriprasadM requested changes

2023-06-13 06:47 UTC, ShriprasadM commented on modules/pubmatic/vastunwrap/constant.go
> +	MediaTypeVideo         = "video"
Yes. but if I want to alter any configuration then it would be easy to do it from vault. It will not need any deployment but needs restart.

2023-06-13 06:53 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/vastunwrap/module.go
> +		return VastUnwrapModule{}, fmt.Errorf("invalid unwrap config: %v", err)
Done

2023-06-13 08:08 UTC, pm-jaydeep-mohite reviewed
LGTM

2023-06-16 11:42 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/vastunwrap/constant.go
> +	POST                = "POST"
http.MethodPost constant can be used. No need of POST cosntant.

2023-06-16 12:03 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/vastunwrap/unwrap_service_test.go
> +			server.URL = tt.args.url
The test Server is not being used by this unit test.

2023-06-16 12:04 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/vastunwrap/unwrap_service_test.go
> +func TestDoUnwrap(t *testing.T) {
Can we add more cases for this UT like unwrap service response with bad request, unwrap service timeout, valid response?

2023-06-19 03:43 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/vastunwrap/unwrap_service_test.go
> +			server.URL = tt.args.url
Removed

2023-06-19 03:43 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/vastunwrap/unwrap_service_test.go
> +func TestDoUnwrap(t *testing.T) {
Added

2023-06-19 05:15 UTC, Pubmatic-Dhruv-Sonone approved these changes

2023-06-19 10:51 UTC, pm-jaydeep-mohite commented on modules/pubmatic/vastunwrap/entryhook.go
> +		Reject: true,
No need to assign` reject: true`

2023-06-20 07:06 UTC, pm-jaydeep-mohite commented on modules/pubmatic/vastunwrap/unwrap_service.go
> +		return
remove return statement

2023-06-20 07:08 UTC, pm-jaydeep-mohite commented on modules/pubmatic/vastunwrap/unwrap_service.go
> +	if httpResp.Code == http.StatusOK {
can we add debug print log in case of no response or any error ?

2023-06-20 11:44 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/vastunwrap/unwrap_service.go
> +	if httpResp.Code == http.StatusOK {
Done

2023-06-20 11:44 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/vastunwrap/unwrap_service.go
> +		return
Done

2023-06-20 11:44 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/vastunwrap/entryhook.go
> +		Reject: true,
Done

2023-06-20 11:44 UTC, merged