OTT-1104: Move the stat-server from HB to prebid
PubMatic-OpenWrap/prebid-server pull request #504
Opened 2023-06-05 12:13 UTC by ashishshinde-pubm

2023-06-06 11:38 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/metrics/stats/client.go
> +	req, err := http.NewRequest(http.MethodPost, sc.endpoint, io.NopCloser(bytes.NewBuffer(sb)))
io.NopCloser not needed.

2023-06-06 11:47 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/metrics/stats/client.go
> +		if resp != nil {
`if rest != nil `  and `if resp.Body != nil {` check is not needed. 

Just add `defer resp.Body.Close()`

2023-06-06 11:48 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/metrics/stats/client.go
> +			ResponseHeaderTimeout: 30 * time.Second,
Can we make it configurable ?

2023-06-06 11:49 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/metrics/stats/client.go
> +		if err == nil && resp != nil && resp.StatusCode == http.StatusOK {
We should close body in this case as well.

2023-06-06 11:50 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/metrics/stats/client.go
> +	u := url.URL{
Take the entire host:port/path from

2023-06-06 11:51 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/metrics/stats/client.go
> +		pubChan:   make(chan stat, statsChanLen), // TODO : statsChanLen should it be configurable ???
Make it configurable

2023-06-06 11:52 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/metrics/stats/client.go
> +			val := sc.statMap[stat.Key] // if key is absent then val will be 0
combine this 2 statements

2023-06-06 11:54 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/metrics/stats/client.go
> +	}
add graceful shutdown case

2023-06-06 11:54 UTC, Pubmatic-Dhruv-Sonone requested changes

2023-06-06 11:54 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/metrics/stats/client.go
> +		if err == nil && resp != nil && resp.StatusCode == http.StatusOK {
Close body in this case as well.

2023-06-06 11:54 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/metrics/stats/client.go
> +		if retry >= (sc.config.Retries - 1) {
`retry  == (sc.config.Retries - 1) ` will work.

2023-06-06 11:54 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/metrics/stats/init.go
> +var once sync.Once
Keep a single var block

2023-06-06 11:57 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/metrics/stats/client.go
> +		go sc.publishStatsToServer(collectedStats)
Check if we can use pond library

2023-06-06 11:58 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/metrics/stats/client.go
> +		go sc.publishStatsToServer(collectedStats)
Check best way to empty the map

2023-06-06 12:03 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/metrics/stats/client.go
> +		// glog.Info("[stats_retry] retry:[%d] status:[%d] nstats:[%v] time:[%v] error:[%v]", retry, code, len(statMap), elapsedTime, err)
Add log in case of success in debug

2023-06-06 12:09 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/metrics/stats/client_test.go
> +		assert.Equal(t, expectedClient.endpoint, actualClient.endpoint, "Mismatched endpoint")
check this ?

2023-06-07 09:43 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/metrics/stats/client.go
> +		go sc.publishStatsToServer(collectedStats)
There is no faster way to empty the map than re-initialising new one.

The stat key count differs based on profile/publisher/platform/bidder values, its not constant.
But still it is static and will be limited. Hence we can loop over it and assign 0 value to each key. 
But it will be time-consuming than current approach.

2023-06-07 09:46 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/metrics/stats/client_test.go
> +		assert.Equal(t, expectedClient.endpoint, actualClient.endpoint, "Mismatched endpoint")
Removed this duplicate statement

2023-06-07 09:46 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/metrics/stats/client.go
> +		// glog.Info("[stats_retry] retry:[%d] status:[%d] nstats:[%v] time:[%v] error:[%v]", retry, code, len(statMap), elapsedTime, err)
Done

2023-06-07 09:48 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/metrics/stats/client.go
> +		if err == nil && resp != nil && resp.StatusCode == http.StatusOK {
Done

2023-06-07 09:49 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/metrics/stats/client.go
> +			val := sc.statMap[stat.Key] // if key is absent then val will be 0
Done

2023-06-07 10:29 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/metrics/stats/client.go
> +		pubChan:   make(chan stat, statsChanLen), // TODO : statsChanLen should it be configurable ???
Done

2023-06-07 10:30 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/metrics/stats/client.go
> +	u := url.URL{
Done

2023-06-08 03:45 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/metrics/stats/client.go
> +		if resp != nil {
I've removed the resp.Body != nil check but have kept the resp!=nil check.
If I call resp.Body.Close() without resp!=nil check then go-static-code analyser gives warning of possible-nil-pointer-dereference.

2023-06-08 06:43 UTC, Pubmatic-Dhruv-Sonone submitted a review, later dismissed

2023-06-08 06:56 UTC, pm-nilesh-chate commented on modules/pubmatic/openwrap/metrics/stats/client.go
> +		case <-sc.shutDownChan:
we should attempt to send the gathered data from `statMap` to stats server before closing the grouting.

2023-06-08 06:58 UTC, pm-nilesh-chate commented on modules/pubmatic/openwrap/metrics/stats/client.go
> +func (sc *Client) ShutdownProcess() {
To avoid data loss, this should be called as part of signal trap when service is being shutdown.

2023-06-12 03:37 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/metrics/stats/client.go
> +		case <-sc.shutDownChan:
Fixed it

2023-06-12 03:40 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/metrics/stats/client.go
> +func (sc *Client) ShutdownProcess() {
Need to handle the signal traps in HB first, then we can call this function.
Will take it as enhancement and will address in separate task.

2023-06-12 07:04 UTC, Pubmatic-Dhruv-Sonone approved these changes

2023-06-12 11:42 UTC, pm-nilesh-chate approved these changes

2023-06-12 11:43 UTC, Pubmatic-Dhruv-Sonone approved these changes

2023-06-12 11:44 UTC, merged