OTT-1073: introduce the stats in Pubmatic OW module
PubMatic-OpenWrap/prebid-server pull request #516
Opened 2023-06-27 09:39 UTC by ashishshinde-pubm

2023-07-10 09:10 UTC, ShriprasadM requested changes

2023-07-10 09:10 UTC, ShriprasadM commented on modules/pubmatic/openwrap/config/config.go
> +type Stats struct {
move this structure in `stats/config.go`

2023-07-10 09:41 UTC, ShriprasadM requested changes

2023-07-10 09:41 UTC, ShriprasadM commented on modules/pubmatic/openwrap/defaultbids.go
> +func (m *OpenWrap) recordErrorStats(rctx models.RequestCtx, bidResponseExt *openrtb_ext.ExtBidResponse, bidder string) {
In future we should use Non Seat bid error codes

2023-07-10 09:41 UTC, ShriprasadM commented on modules/pubmatic/openwrap/entrypointhook.go
> +	var endpoint string
instead of `endpoint`  we can use `payload.Request.URL.Path`  and  add `default` case 
```go
validPath := true
switch payload.Request.URL.Path {
   case :  // Valid Paths
  default:
         validPath = false
}

if validPath {
    // record bad request error if applicable
}
```

2023-07-10 09:41 UTC, ShriprasadM commented on router/router.go
> +			}).Dial,
As discussed this is from another PR. Ensure this PR is up-to-date with upstream

2023-07-10 12:31 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/util.go
> +func parseUIDCookies(httpReqUIDCookie *http.Cookie, hostCookie *config.HostCookie) *usersync.Cookie {
removed the 2nd argument, made the suggested changes.

2023-07-10 12:32 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/util.go
> +		cookieFlagMap[partnerConfig[models.BidderCode]] = matchedImpression
done

2023-07-10 12:34 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/auctionresponsehook.go
> +				m.metricEngine.RecordPlatformPublisherPartnerResponseStats(rctx.Platform, rctx.PubIDStr, seatBid.Seat)
as per old code, RecordPlatformPublisherPartnerResponseStats records the metrics at bid level. hence for multi-bid response, it records multiple times, hence no need to make any changes in above function.

2023-07-10 12:57 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/auctionresponsehook.go
> +			if rctx.Platform != "" {
having platform empty is bad-request hence added the check at early stage and if we receive empty platform then we will return. Hence going ahead we will not require this check

2023-07-10 12:58 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/auctionresponsehook.go
>  	for k, v := range responseExt.ResponseTimeMillis {
done

2023-07-10 13:28 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/beforevalidationhook.go
> +	m.metricEngine.RecordPublisherProfileRequests(rCtx.PubIDStr, rCtx.ProfileIDStr)
it counts all valid+invalid requests

2023-07-10 13:28 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/beforevalidationhook.go
> +		m.metricEngine.RecordPublisherInvalidProfileImpressions(rCtx.PubIDStr, rCtx.ProfileIDStr, len(payload.BidRequest.Imp))
as discussed we will handle this once we completely migrate from HB to OW module

2023-07-11 03:34 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/beforevalidationhook.go
> +			m.metricEngine.RecordBadRequests(rCtx.Endpoint, result.NbrCode)
I've introduced the getPubmaticErrorCode as temporary function which will map the standard-NBR with Pubmatic specific error-code. We will use this function while recording the bad request so that it will not impact the existing monitoring alerts/system

2023-07-11 03:39 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/config/config.go
> +type Stats struct {
done

2023-07-11 04:59 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/entrypointhook.go
> +	var endpoint string
okay, used payload.Request.URL.Path instead of endpoint variable

2023-07-11 06:26 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/util.go
> +		if partnerConfig[models.SERVER_SIDE_FLAG] != "1" {
done

2023-07-11 06:52 UTC, ashishshinde-pubm commented on router/router.go
> +			}).Dial,
pulled the base branch in feature branch to have up-to-date PR

2023-07-11 14:08 UTC, ShriprasadM submitted a review, later dismissed

2023-07-13 06:03 UTC, pm-nilesh-chate requested changes
requested a few changes

2023-07-13 06:03 UTC, pm-nilesh-chate commented on modules/pubmatic/openwrap/util.go
> +}
Do we need this?. I think PBS-Core already has these stats. Refer, `CookieFlag` done as part of `usersync.ParseCookieFromRequest`

2023-07-13 10:26 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/beforevalidationhook.go
> +			m.metricEngine.RecordNobidErrPrebidServerRequests(rCtx.PubIDStr)
I've created OTT-1182 story to address the same.

2023-07-13 10:26 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/util.go
> +}
As discussed we will address this in new task/story

2023-07-13 10:27 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/auctionresponsehook.go
> +	RecordPublisherPartnerNoCookieStats(rctx, m.metricEngine)
yes, we are recording it for all incoming requests for which prebid has given some bidResponse

2023-07-13 10:28 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/adunitconfig/banner.go
> +func UpdateBannerObjectWithAdunitConfig(rCtx models.RequestCtx, imp openrtb2.Imp, div string, metricEngine metrics.MetricsEngine) (adUnitCtx models.AdUnitCtx) {
Done. 
In each hook-function, I've used the metricEngine from openwrap object and for all functions that are getting called from hook-function I;ve used the metricsEngine from rCtx.

2023-07-14 08:32 UTC, pm-nilesh-chate commented on analytics/pubmatic/pubmatic.go
> +		glog.Errorf("Failed to get the request context from HookExecutionOutcome inside LogAuctionObject.")
remove this log until 100% traffic is migrated to modules to eliminate false error for non-module based auctions as rctx would be alway nil in such scenario

2023-07-14 08:33 UTC, pm-nilesh-chate commented on analytics/pubmatic/pubmatic.go
> +		glog.Errorf("Failed to send the owlogger for pub:[%d], profile:[%d], version:[%d].",
should have metrics for success/failure monitoring

2023-07-14 08:36 UTC, pm-nilesh-chate commented on modules/pubmatic/openwrap/beforevalidationhook.go
>  			if err != nil || len(bidderParams) == 0 {
add `RecordMisConfigurationErrorStats` here. can be used for all bidder

2023-07-14 09:04 UTC, pm-nilesh-chate commented on modules/pubmatic/openwrap/beforevalidationhook.go
>  			if err != nil || len(bidderParams) == 0 {
OTT-1182

2023-07-14 09:04 UTC, pm-nilesh-chate commented on modules/pubmatic/openwrap/beforevalidationhook.go
> +				m.metricEngine.RecordSlotNotMappedErrorStats(rCtx.PubIDStr, bidderCode)
OTT-1182

2023-07-14 09:04 UTC, pm-nilesh-chate approved these changes

2023-07-14 09:04 UTC, pm-nilesh-chate commented on modules/pubmatic/openwrap/util.go
> +}
OTT-1182

2023-07-14 09:16 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/util.go
> +}
added this in OTT-1182

2023-07-14 09:19 UTC, ShriprasadM approved these changes
LGTM

2023-07-14 09:19 UTC, merged