OTT-734: VAST Unwrapping Phase 1
PubMatic-OpenWrap/prebid-server pull request #523
Opened 2023-07-10 06:49 UTC by Pubmatic-Supriya-Patil

# Description

Please add change description or link to ticket, docs, etc.

# Checklist:

- [ ] PR commit list is unique (rebase/pull with the origin branch to keep master clean).
- [ ] JIRA number is added in the PR title and the commit message.
- [ ] Updated the `header-bidding` repo with appropiate commit id.
- [ ] Documented the new changes.

For Prebid upgrade, refer: https://inside.pubmatic.com:8443/confluence/display/Products/Prebid-server+upgrade

2023-07-11 06:23 UTC, pm-nilesh-chate commented on hooks/hookexecution/context.go
> +		moduleInvocationCtx.AccountID = ctx.account.ID
I would suggest to submit this to vanilla

2023-07-11 08:28 UTC, pm-nilesh-chate requested changes
Added review comments. Mostly around readability. Also, please do not merge the PR until Grafana monitoring dashboards and performance result is ready.

2023-07-11 08:28 UTC, pm-nilesh-chate commented on modules/pubmatic/vastunwrap/hook_raw_bidder_response_test.go
> +			_, err := handleRawBidderResponseHook(tt.args.module, tt.args.moduleInvocationCtx, tt.args.payload, "test")
add UT to cover scenarios like multiple bids with different media type, all bids with media type video, etc.

2023-07-11 08:28 UTC, pm-nilesh-chate commented on modules/pubmatic/vastunwrap/models/request.go
> +}
Prefer full naming convention similar to Prebid. Ex.
```
type UnwrapReq struct {
 	Adm       string
 	BidID     string
 	UnwrapCount int
 	Err       error
 	ResponseTime  int
 }
```

2023-07-11 08:28 UTC, pm-nilesh-chate commented on modules/pubmatic/vastunwrap/models/request.go
> +	IsVastUnwrapEnabled bool
Remove C style, `Is` from the name.

2023-07-11 08:28 UTC, pm-nilesh-chate commented on modules/pubmatic/vastunwrap/unwrap_service.go
> +		m.MetricsEngine.RecordRequestStatus(accountID, bidder, "Failure")
move `m.MetricsEngine.RecordRequestStatus()` inside defer besides `m.MetricsEngine.RecordRequestTime()` and set the status using variable.

2023-07-11 08:28 UTC, pm-nilesh-chate commented on modules/pubmatic/vastunwrap/unwrap_service.go
> +	httpResp := httptest.NewRecorder()
do not use `httptest` package in production code. Create a custom recorder if needed

2023-07-11 08:28 UTC, pm-nilesh-chate commented on modules/pubmatic/vastunwrap/unwrap_service.go
> +	}
can avoid if check with `ParseInt()`

2023-07-11 08:28 UTC, pm-nilesh-chate commented on modules/pubmatic/vastunwrap/unwrap_service.go
> +		bid.Bid.AdM = string(respBody)
function name suggests only unwrap but we are updating bid adm here. Please refactor the code to return the new adm and let the caller update the bid.adm. This will be mode readable, modular and better testable (the current assertion would be on incoming bid, kind of hacky UT).

2023-07-11 08:28 UTC, pm-nilesh-chate commented on modules/pubmatic/vastunwrap/unwrap_service.go
> +		glog.Infof("\n UnWrap Done for BidId = %s Cnt = %d in %v (ms)", bid.Bid.ID, wrapperCnt, time.Since(startTime).Milliseconds())
We are adding stats, so why do we need to log successful unwrap details?. This log would be a spam, unless this data is needed for audit or monitoring via decentralised logger.

2023-07-11 08:28 UTC, pm-nilesh-chate commented on modules/pubmatic/vastunwrap/unwrap_service_test.go
> +			doUnwrap(tt.args.module, tt.args.bid, tt.args.userAgent, tt.args.url, "5890", "pubmatic")
Add UT to cover different response scenarios from unwrap service using httptest server. Ex. timeout, invalid request, invalid response body, etc.

2023-07-11 08:28 UTC, pm-nilesh-chate commented on modules/pubmatic/vastunwrap/unwrap_service_test.go
> +				mockMetricsEngine.EXPECT().RecordRequestStatus(gomock.Any(), gomock.Any(), gomock.Any())
let not use gomock.Any() where we know the values. Ex. status param

2023-07-14 08:41 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/vastunwrap/unwrap_service.go
> +		bid.Bid.AdM = string(respBody)
@pm-nilesh-chate This code is updated as per review comment https://github.com/PubMatic-OpenWrap/prebid-server/pull/503#discussion_r1220885433

2023-07-14 08:44 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/vastunwrap/module.go
> +	MetricsEngine     stats.MetricsEngine
Actually this MetricsEngine is used only to call prometheus stats so we are not used this to marshal or unmarshal

2023-07-14 08:45 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/vastunwrap/module.go
> +}
I tried to move this struct to models package but as package for this struct and package where its getting used as receiver are different so not moving struct to models package

2023-07-17 09:30 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/vastunwrap/models/request.go
> +	IsVastUnwrapEnabled bool
Updated as per https://github.com/PubMatic-OpenWrap/prebid-server/pull/503#discussion_r1220873310

2023-07-19 11:46 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/vastunwrap/module_test.go
> +			got, err := Builder(tt.args.rawCfg, tt.args.deps)
Done

2023-07-19 11:49 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/vastunwrap/hook_raw_bidder_response.go
> +type mediaTypes map[string]struct{}
Removed

2023-07-19 11:49 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/vastunwrap/hook_raw_bidder_response.go
> +		if _, ok := bidMediaTypes[MediaTypeVideo]; ok {
Updated

2023-07-20 06:55 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/vastunwrap/unwrap_service.go
> +		bid.Bid.AdM = string(respBody)
Updated function name

2023-07-20 06:57 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/vastunwrap/models/request.go
> +	IsVastUnwrapEnabled bool
Updated to VastUnwrapEnabled

2023-07-20 08:35 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/vastunwrap/module.go
> +	}, nil
Removed check for InitUnWrapperConfig

2023-07-20 08:38 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/vastunwrap/stats/metrics.go
> +		[]float64{50, 100, 200, 300, 500})
Vast unwrap timeout is in milliseconds so if we log in seconds then most probably it will comes under same bucket. For now we are not logging this stats so commenting code.

2023-07-27 09:03 UTC, pm-nilesh-chate commented on go.mod
> +
why no directly use `git.pubmatic.com/PubMatic/vastunwrap` instead of importing `git.pubmatic.com/vastunwrap`

2023-07-27 09:04 UTC, pm-nilesh-chate commented on go.mod
> +replace github.com/beevik/etree/110 => github.com/beevik/etree v1.1.0
use only the latest version?

2023-07-27 09:08 UTC, pm-nilesh-chate commented on modules/pubmatic/vastunwrap/constant.go
> +	UnwrapURL           = "http://localhost:8003/unwrap"
this should be configurable. Also, port 8003 is used by admin api's

2023-07-27 09:20 UTC, Pubmatic-Supriya-Patil commented on go.mod
> +replace github.com/beevik/etree/110 => github.com/beevik/etree v1.1.0
etree v1.1.0 is used by vast unwrap service so we are using same here also

2023-07-27 10:15 UTC, Pubmatic-Supriya-Patil commented on go.mod
> +
vast unwrap service is using git.pubmatic.com/vastunwrap as module name.

2023-07-27 12:22 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/vastunwrap/constant.go
> +	UnwrapURL           = "http://localhost:8003/unwrap"
As per my understanding , This URL is just to create http request. This is not getting used to call actual service as we are calling function of vast unwrap service directly. So it doen't affect anything unless we use it actually.

2023-10-13 03:40 UTC, ashishshinde-pubm commented on modules/pubmatic/vastunwrap/entryhook.go
> +			glog.Error("body:" + string(payload.Body) + ". stacktrace:" + string(debug.Stack()))
Can we print the value of "r" ? it will contain actual error like "divide by zero"

2023-10-13 04:01 UTC, ashishshinde-pubm commented on modules/pubmatic/vastunwrap/unwrap_service.go
> +			glog.Error("AdM:" + bid.Bid.AdM + ". stacktrace:" + string(debug.Stack()))
Please print "r" variable here

2023-10-13 04:08 UTC, ashishshinde-pubm commented on modules/pubmatic/vastunwrap/constant.go
> +	OpenWrapAuction     = "/pbs/openrtb2/auction"
can you plz confirm if we are using this constants somewhere ?  if not then remove it in case there is no plan to use in future ?

2023-10-13 04:09 UTC, ashishshinde-pubm commented on modules/pubmatic/vastunwrap/constant.go
> +	OpenWrapAmp         = "/openrtb/amp"
can you plz confirm if we are using this constants somewhere ? if not then remove it in case there is no plan to use in future ?

2023-10-13 06:29 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/vastunwrap/entryhook.go
> +			glog.Error("body:" + string(payload.Body) + ". stacktrace:" + string(debug.Stack()))
Done

2023-10-13 06:29 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/vastunwrap/unwrap_service.go
> +			glog.Error("AdM:" + bid.Bid.AdM + ". stacktrace:" + string(debug.Stack()))
Done

2023-10-13 06:30 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/vastunwrap/constant.go
> +	OpenWrapAmp         = "/openrtb/amp"
Removed

2023-10-16 06:07 UTC, ashishshinde-pubm approved these changes
LGTM

2023-10-16 06:36 UTC, pm-nilesh-chate approved these changes

2023-10-16 06:39 UTC, ashishshinde-pubm approved these changes

2023-10-16 06:53 UTC, pm-jaydeep-mohite approved these changes

2023-10-16 06:56 UTC, merged