OTT-1160: Introduce Prometheus Metric Engine for PubMatic openwrap module
PubMatic-OpenWrap/prebid-server pull request #526
Opened 2023-07-13 08:10 UTC by ashishshinde-pubm

2023-07-14 09:16 UTC, pm-viral-vala requested changes

2023-07-14 09:16 UTC, pm-viral-vala commented on modules/pubmatic/openwrap/metrics/prometheus/prometheus.go
> +	methodLabel    = "method"
can we keep label names consistent with wrapper tracker publisher id, profile id, etc?

2023-07-15 05:04 UTC, ashishshinde-pubm commented on metrics/config/metrics.go
> +func NewMetricsEngine(cfg *config.Configuration, adapterList []openrtb_ext.BidderName, syncerKeys []string, moduleStageNames map[string][]string, promRegistry *prometheus.Registry) *DetailedMetricsEn
yes, modified the code to pass generic MetricsRegistry

2023-07-15 05:04 UTC, ashishshinde-pubm commented on metrics/config/metrics.go
> +func NewMetricsEngine(cfg *config.Configuration, adapterList []openrtb_ext.BidderName, syncerKeys []string, moduleStageNames map[string][]string, promRegistry *prometheus.Registry) *DetailedMetricsEn
done

2023-07-15 05:04 UTC, ashishshinde-pubm commented on metrics/prometheus/prometheus.go
> +func NewMetrics(cfg config.PrometheusMetrics, disabledMetrics config.DisabledMetrics, syncerKeys []string, moduleStageNames map[string][]string, promRegistry *prometheus.Registry) *Metrics {
done

2023-07-15 05:04 UTC, ashishshinde-pubm commented on metrics/prometheus/prometheus.go
> +func NewMetrics(cfg config.PrometheusMetrics, disabledMetrics config.DisabledMetrics, syncerKeys []string, moduleStageNames map[string][]string, promRegistry *prometheus.Registry) *Metrics {
done

2023-07-15 05:04 UTC, ashishshinde-pubm commented on metrics/prometheus/prometheus.go
> +	reg := promRegistry
done

2023-07-15 05:05 UTC, ashishshinde-pubm commented on modules/moduledeps/deps.go
> +	PrometheusRegistry *prometheus.Registry
introduced MetricRegistry and MetricsCfg which contains generic metric-engines data

2023-07-15 05:05 UTC, ashishshinde-pubm commented on modules/moduledeps/deps.go
> +	PrometheusCfg      *config.PrometheusMetrics
done

2023-07-15 05:05 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/beforevalidationhook.go
> +				m.metricEngine.RecordPartnerConfigErrors(rCtx.PubIDStr, bidderCode, models.PartnerErrSlotNotMapped)
Done. Added profile label for this metric.

2023-07-15 05:06 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/bidderparams/pubmatic.go
> +			rctx.MetricsEngine.RecordPartnerConfigErrors(rctx.PubIDStr, string(openrtb_ext.BidderPubmatic), models.PartnerErrMisConfig)
Added profile label for this metric. 
But need to discuss this, there is difference between HB behaviour and this code. Not able to map this error to exact location. We have created OTT-1182 ticket to address such issues.

2023-07-15 05:07 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/metrics/prometheus/prometheus.go
> +	methodLabel    = "method"
Modified few parameters to make them consistent with go-tracker labels

2023-07-31 03:04 UTC, closed without merging