OTT-806 :: Adpod Support (CTV)
PubMatic-OpenWrap/prebid-server pull request #532
Opened 2023-07-20 14:23 UTC by pm-nikhil-vaidya

# Description

Please add change description or link to ticket, docs, etc.

# Checklist:

- [ ] PR commit list is unique (rebase/pull with the origin branch to keep master clean).
- [ ] JIRA number is added in the PR title and the commit message.
- [ ] Updated the `header-bidding` repo with appropiate commit id.
- [ ] Documented the new changes.

For Prebid upgrade, refer: https://inside.pubmatic.com:8443/confluence/display/Products/Prebid-server+upgrade

2023-11-08 09:20 UTC, pm-jaydeep-mohite commented on modules/pubmatic/openwrap/adpod/adpod.go
> +	adpodConfigs, ok, err := resolveAdpodConfigs(impVideo, requestExtConfigs, adUnitConfig)
Can we return only **adpodConfigs, err** and remove ok variable as its redundnet info

2023-11-08 09:21 UTC, pm-jaydeep-mohite commented on modules/pubmatic/openwrap/adpod/adpod.go
> +// func getAdpodConfigsFromExt(ext json.RawMessage) (models.AdPod, error) {
Remove dead code if its unused

2023-11-08 09:23 UTC, pm-jaydeep-mohite commented on modules/pubmatic/openwrap/adpod/adpod.go
> +		adpodConfigs.VideoAdDuration = utils.GetIntArrayFromString(videoAdDuration, models.ArraySeparator)
Is it Ok to overwrite adpodConfigs.VideoAdDuration provided in incoming request ? 

Applicable to below params as well

2023-11-09 11:52 UTC, Pubmatic-Dhruv-Sonone requested changes

2023-11-09 11:52 UTC, Pubmatic-Dhruv-Sonone commented on analytics/pubmatic/logger.go
> +	return &adPodSlot
Can be written as return &AdPodSlot{

2023-11-09 11:52 UTC, Pubmatic-Dhruv-Sonone commented on analytics/pubmatic/logger.go
> +			_ = json.Unmarshal(bid.Ext, &bidExt)
json.Unmarshal(bid.Ext, &bidExt)  works  _= is not needed

2023-11-09 11:52 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/adpod/adpod.go
> +	}
Use  constant

2023-11-09 11:52 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/adpod/adpod.go
> +		adpodBytes, _, _, err := jsonparser.Get(impVideo.Ext, "adpod")
constant - adpod

2023-11-09 11:52 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/adpod/adpod.go
> +		if len(adpodBytes) > 0 && err == nil {
can we check err == nil first ?

2023-11-09 11:52 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/adpod/auction/adpod_generator.go
> +			if nil != hbc {
nbc != nil

2023-11-10 09:58 UTC, pm-viral-vala requested changes

2023-11-10 09:58 UTC, pm-viral-vala commented on modules/pubmatic/openwrap/endpoints/legacy/ctv/parser_implementation.go
> +package ctv
let's make sure it is in sync with the latest code, such as Ankit has committed something regarding Schain and key-value support.

2023-11-10 09:58 UTC, pm-viral-vala commented on modules/pubmatic/openwrap/middleware/adpod/adpod.go
> +			body, err := io.ReadAll(r.Body)
***IMP*** Please use existing prometheus stats of panic w.r.t function in all functions

2023-11-10 09:58 UTC, pm-viral-vala commented on modules/pubmatic/openwrap/middleware/adpod/adpod.go
> +		writeErrorResponse(w, http.StatusBadRequest, err)
Please use existing prometheus stats for bad requests

2023-11-10 09:58 UTC, pm-viral-vala commented on modules/pubmatic/openwrap/middleware/adpod/error.go
> +type OwError struct {
please rename it to `OWError`

2023-11-10 09:58 UTC, pm-viral-vala commented on modules/pubmatic/openwrap/middleware/adpod/openrtb.go
> +			bidArrayMap[impId] = bids
can we have something like below?
```
bidArrayMap[impId] = append(bidArrayMap[impId], bid)
```

2023-11-10 09:58 UTC, pm-viral-vala commented on modules/pubmatic/openwrap/middleware/adpod/openrtb.go
> +		}
not sure but we were appending all UNIQUE category and domain details for each slot bid to merge bid parameters. 
could you please check once?

2023-11-10 09:58 UTC, pm-viral-vala commented on modules/pubmatic/openwrap/middleware/adpod/vast.go
> +		fmt.Printf("ERROR, %v", err.Error())
Please remove this message and log it to correct location

2023-11-20 04:54 UTC, pm-nikhil-vaidya commented on modules/pubmatic/openwrap/adpod/adpod.go
> +	adpodConfigs, ok, err := resolveAdpodConfigs(impVideo, requestExtConfigs, adUnitConfig)
It was to differentiate between the adpod and normal video impression. Error was there when adpod is present but issue while reading

2023-11-20 04:55 UTC, pm-nikhil-vaidya commented on modules/pubmatic/openwrap/adpod/adpod.go
> +// func getAdpodConfigsFromExt(ext json.RawMessage) (models.AdPod, error) {
Done

2023-11-20 04:56 UTC, pm-nikhil-vaidya commented on modules/pubmatic/openwrap/adpod/adpod.go
> +		adpodConfigs.VideoAdDuration = utils.GetIntArrayFromString(videoAdDuration, models.ArraySeparator)
We are not accepting videoAdduration in request, it was just made part of the structure

2023-11-20 09:57 UTC, pm-nikhil-vaidya commented on analytics/pubmatic/logger.go
> +	return &adPodSlot
It is coding pattern style, both work as same, just here it will create variable on stack instead of heap
Both can be used

2023-11-20 10:18 UTC, pm-nikhil-vaidya commented on modules/pubmatic/openwrap/adpod/adpod.go
> +	}
Done

2023-11-20 10:21 UTC, pm-nikhil-vaidya commented on modules/pubmatic/openwrap/adpod/adpod.go
> +		adpodBytes, _, _, err := jsonparser.Get(impVideo.Ext, "adpod")
Done

2023-11-20 10:21 UTC, pm-nikhil-vaidya commented on modules/pubmatic/openwrap/adpod/adpod.go
> +		if len(adpodBytes) > 0 && err == nil {
Done

2023-11-20 10:22 UTC, pm-nikhil-vaidya commented on modules/pubmatic/openwrap/adpod/auction/adpod_generator.go
> +			if nil != hbc {
Done

2023-11-23 08:05 UTC, pm-nikhil-vaidya commented on modules/pubmatic/openwrap/middleware/adpod/adpod.go
> +		}
Done

2023-11-23 08:05 UTC, pm-nikhil-vaidya commented on modules/pubmatic/openwrap/middleware/adpod/adpod.go
> +	aw.Response = append(aw.Response, data...)
Done

2023-11-23 08:05 UTC, pm-nikhil-vaidya commented on modules/pubmatic/openwrap/middleware/adpod/adpod.go
> +	Response []byte
Done

2023-11-23 08:05 UTC, pm-nikhil-vaidya commented on modules/pubmatic/openwrap/middleware/adpod/adpod.go
> +}
Done

2023-11-23 08:06 UTC, pm-nikhil-vaidya commented on modules/pubmatic/openwrap/middleware/adpod/adpod.go
> +	w.Header().Set(ContentType, ApplicationJSON)
Done

2023-11-23 08:52 UTC, pm-nikhil-vaidya commented on modules/pubmatic/openwrap/middleware/adpod/vast.go
> +		fmt.Printf("ERROR, %v", err.Error())
Replced with glog

2023-11-23 12:33 UTC, pm-nikhil-vaidya commented on modules/pubmatic/openwrap/middleware/adpod/error.go
> +type OwError struct {
Done

2023-11-24 05:33 UTC, pm-nikhil-vaidya commented on modules/pubmatic/openwrap/middleware/adpod/adpod.go
> +	w.Header().Set(ContentType, ApplicationXML)
Done

2023-11-24 05:33 UTC, pm-nikhil-vaidya commented on modules/pubmatic/openwrap/middleware/adpod/adpod.go
> +	w.Header().Set(ContentType, ApplicationJSON)
Done

2023-11-24 05:33 UTC, pm-nikhil-vaidya commented on modules/pubmatic/openwrap/tracker/create.go
> +			tracker.SlotID = fmt.Sprintf("%s_%s", impId, tagid)
Done

2023-11-24 06:24 UTC, pm-nikhil-vaidya commented on modules/pubmatic/openwrap/endpoints/legacy/ctv/video.go
> +		request.Imp = request.Imp[:j]
Done, moved in muatation

2023-11-24 06:26 UTC, pm-nikhil-vaidya commented on modules/pubmatic/openwrap/endpoints/legacy/ctv/parser_util.go
> +type URLValues struct {
This functionality is mainly used by ctv request, no other request is using this
Thats why kept in parser_util instead of making it common

2023-11-24 06:28 UTC, pm-nikhil-vaidya commented on modules/pubmatic/openwrap/cache/bidcache/bid_cache.go
> +
Removed this file, as moved caching mechanism in middleware itself
We will be using prebid fuction for caching

2023-11-24 06:28 UTC, pm-nikhil-vaidya commented on modules/pubmatic/openwrap/cache/bidcache/bid_cache.go
> +		buffer.WriteString(`"`)
Removed this file, as moved caching mechanism in middleware itself
We will be using prebid fuction for caching

2023-11-24 06:29 UTC, pm-nikhil-vaidya commented on modules/pubmatic/openwrap/cache/bidcache/bid_cache.go
> +func encodeValueToBuffer(value pbc.Cacheable, leadingComma bool, buffer *bytes.Buffer) error {
Removed this file, as moved caching mechanism in middleware itself
We will be using prebid fuction for caching

2023-12-13 08:44 UTC, pm-viral-vala approved these changes

2023-12-13 08:44 UTC, pm-viral-vala commented on modules/pubmatic/openwrap/models/openwrap.go
> +		if wbid.BidDealTierSatisfied && !bid.BidDealTierSatisfied {
Please check one scenario:
A total of 10 bids were there, the first 4 were lost because of higher prices, after that if you found a deal bid then remaining all bids will get the reason for loss to deal bid.
Ideally, if a deal bid is selected then all other nonwinning bids should have a reason for loss to the deal bid.
or Check if this is required.

2023-12-19 09:27 UTC, pm-nikhil-vaidya commented on modules/pubmatic/openwrap/utils/buffer_writer.go
> +type CustomWriter struct {
Done

2023-12-19 09:32 UTC, pm-nikhil-vaidya commented on modules/pubmatic/openwrap/models/adpod.go
> +	DefaultMaxAds                      = 3
Confirmed with QA its 3

2024-02-09 07:56 UTC, pm-jaydeep-mohite commented on exchange/exchange.go
> +		if oldCatDur, ok := bidCategory[utils.GetOriginalBidId(bid.Bid.ID)]; ok {
Can we get Original Bid Id once and reuse at line 676, to avoid extra call utils.GetOriginalBidId() ?

2024-02-09 07:59 UTC, pm-jaydeep-mohite commented on modules/pubmatic/openwrap/adpod/adpod.go
> +	adpodConfigs, ok, err := resolveAdpodConfigs(impVideo, requestExtConfigs, adUnitConfig, pubId, me)
Can we set default values for adPodConfig here, so that extra checks at later stages shall be removed

2024-02-09 09:23 UTC, pm-jaydeep-mohite commented on modules/pubmatic/openwrap/adpod/auction/auction.go
> +		tmp := GetNearestDuration(duration, config)
can we rename tmp to meaningful name ?

2024-02-09 11:45 UTC, pm-jaydeep-mohite commented on modules/pubmatic/openwrap/defaultbids.go
> +// TODO : Check if we need this?
If not required can we remove commented code ?

2024-02-09 11:47 UTC, pm-jaydeep-mohite commented on modules/pubmatic/openwrap/endpoints/legacy/ctv/constant.go
> +const (
Can we remove these 3 lines and have single block of constant ?

2024-02-13 06:07 UTC, pm-nikhil-vaidya commented on modules/pubmatic/openwrap/endpoints/legacy/ctv/parser_implementation.go
> +package ctv
Done

2024-02-13 10:53 UTC, pm-nikhil-vaidya commented on modules/pubmatic/openwrap/metrics/prometheus/prometheus.go
> +	prebidCacheWriteTimer *prometheus.HistogramVec
Done

2024-02-13 11:05 UTC, pm-nikhil-vaidya commented on modules/pubmatic/openwrap/metrics/prometheus/prometheus.go
> +	cacheWriteTimeBuckets := []float64{0.001, 0.002, 0.005, 0.01, 0.025, 0.05, 0.1, 0.2, 0.3, 0.4, 0.5, 1}
Done

2024-02-13 11:06 UTC, pm-nikhil-vaidya commented on modules/pubmatic/openwrap/metrics/prometheus/prometheus.go
> +		"openwrap_write_time_seconds",
Renamed to `cache_write_time`

2024-02-13 15:17 UTC, pm-nikhil-vaidya commented on modules/pubmatic/openwrap/metrics/prometheus/prometheus.go
> +	}).Observe(length.Seconds())
Done

2024-02-14 05:17 UTC, pm-nikhil-vaidya commented on modules/pubmatic/openwrap/tracker/create.go
> +			trackers[bidId] = models.OWTracker{
Ticket created
https://inside.pubmatic.com:9443/jira/browse/OTT-1624

2024-02-14 05:20 UTC, pm-nikhil-vaidya commented on modules/pubmatic/openwrap/cache/bidcache/bid_cache.go
> +			MaxConnsPerHost:     cfg.CacheClient.MaxConnsPerHost,
Removed the bid-cache

2024-02-14 05:25 UTC, pm-nikhil-vaidya commented on modules/pubmatic/openwrap/brandcategory.go
> +			(models.IncludeIABBranchCategory == *wrapperExt.IncludeBrandCategory ||
Here IncludeIABBrandCategory is constant having value 1 and we are having only one field IncludeBrandCategory in wrapper ext

2024-02-14 05:31 UTC, pm-nikhil-vaidya commented on modules/pubmatic/openwrap/middleware/adpod/vast.go
> +func adjustBidIDInVideoEventTrackers(doc *etree.Document, bid *openrtb2.Bid) {
Removed

2024-02-14 05:34 UTC, pm-nikhil-vaidya commented on modules/pubmatic/openwrap/metrics/prometheus/prometheus.go
> +	)
https://inside.pubmatic.com:9443/jira/browse/OTT-1627

2024-02-14 05:37 UTC, pm-nikhil-vaidya commented on modules/pubmatic/openwrap/middleware/adpod/vast.go
> +	var v vast.VAST
https://inside.pubmatic.com:9443/jira/browse/OTT-1628

2024-02-14 06:03 UTC, pm-nikhil-vaidya commented on modules/pubmatic/openwrap/adpod/auction/adpod_generator.go
> +	maxRoutines := 3
Done

2024-02-14 06:23 UTC, pm-nikhil-vaidya commented on modules/pubmatic/openwrap/endpoints/legacy/ctv/constant.go
> +const (
Done

2024-02-14 06:25 UTC, pm-nikhil-vaidya commented on modules/pubmatic/openwrap/adpod/auction/auction.go
> +		tmp := GetNearestDuration(duration, config)
It was part of legacy code, we are going to remove it in future

2024-02-14 06:26 UTC, pm-nikhil-vaidya commented on modules/pubmatic/openwrap/defaultbids.go
> +// TODO : Check if we need this?
For now we are keeping, yet to decide the on this part

2024-02-14 06:28 UTC, pm-nikhil-vaidya commented on exchange/exchange.go
> +		if oldCatDur, ok := bidCategory[utils.GetOriginalBidId(bid.Bid.ID)]; ok {
It was used one time, so it was not declared separately

2024-02-14 06:28 UTC, pm-nikhil-vaidya commented on modules/pubmatic/openwrap/adpod/adpod.go
> +	adpodConfigs, ok, err := resolveAdpodConfigs(impVideo, requestExtConfigs, adUnitConfig, pubId, me)
We need that to validate if adpod object exists or not, if we set default value it will be always available

2024-02-29 09:10 UTC, pm-nikhil-vaidya commented on modules/pubmatic/openwrap/middleware/adpod/openrtb.go
> +		}
Added unqiue cat and addomains from selected bids

2024-02-29 09:10 UTC, pm-nikhil-vaidya commented on modules/pubmatic/openwrap/middleware/adpod/adpod.go
> +			body, err := io.ReadAll(r.Body)
Done

2024-02-29 09:10 UTC, pm-nikhil-vaidya commented on modules/pubmatic/openwrap/middleware/adpod/adpod.go
> +			body, err := io.ReadAll(r.Body)
Defined new metrics in prebid, to record panics

2024-03-01 04:27 UTC, pm-nikhil-vaidya commented on modules/pubmatic/openwrap/models/openwrap.go
> +		if wbid.BidDealTierSatisfied && !bid.BidDealTierSatisfied {
This is applicable only for non adpod request, so this will work for non adpod request

2024-03-08 04:58 UTC, pm-nikhil-vaidya commented on modules/pubmatic/openwrap/middleware/adpod/adpod.go
> +		writeErrorResponse(w, http.StatusBadRequest, err)
Done

2024-03-08 05:58 UTC, pm-nikhil-vaidya commented on analytics/pubmatic/logger.go
> +			}
Done

2024-06-25 09:11 UTC, Pubmatic-Dhruv-Sonone approved these changes

2024-07-01 12:01 UTC, pm-viral-vala submitted a review, later dismissed

2024-07-02 05:12 UTC, pm-viral-vala approved these changes

2024-07-02 05:14 UTC, ashishshinde-pubm approved these changes

2024-07-02 05:16 UTC, merged