UOE-9178: add tests for database package
PubMatic-OpenWrap/prebid-server pull request #535
Opened 2023-07-26 09:35 UTC by pm-saurabh-narkhede

# Description

Please add change description or link to ticket, docs, etc.

# Checklist:

- [ ] PR commit list is unique (rebase/pull with the origin branch to keep master clean).
- [ ] JIRA number is added in the PR title and the commit message.
- [ ] Updated the `header-bidding` repo with appropiate commit id.
- [ ] Documented the new changes.

For Prebid upgrade, refer: https://inside.pubmatic.com:8443/confluence/display/Products/Prebid-server+upgrade

2023-07-28 07:20 UTC, pm-aadit-patil approved these changes

2023-07-28 07:33 UTC, AvinashKapre commented on modules/pubmatic/openwrap/database/database.go
> -	GetAdunitConfig(profileID, displayVersionID int) (*adunitconfig.AdUnitConfig, error)
can we keep displayVersionId, pubId, profileId consiestant across all packages.

2023-07-28 07:36 UTC, AvinashKapre commented on modules/pubmatic/openwrap/database/mysql/fsc_test.go
> +				mock.ExpectQuery(regexp.QuoteMeta(`SELECT dsp_id,value from wrapper_feature_dsp_mapping WHERE key_id=(SELECT id FROM wrapper_key_master WHERE key_name = "fsc_pcnt")`)).WillReturnRows(rows)
Adding quries in test cacses are we exposing it, since it is public repo?

2023-07-28 07:39 UTC, AvinashKapre commented on modules/pubmatic/openwrap/database/mysql/adunit_config.go
> -		err = fmt.Errorf("[QUERY_FAILED] Name:[%v] Error:[%v]", "GetAdunitConfig", err.Error())
can we keep the error as earlier and add thr name of query which will be more informative.

2023-07-28 07:47 UTC, pm-saurabh-narkhede commented on modules/pubmatic/openwrap/database/database.go
> -	GetAdunitConfig(profileID, displayVersionID int) (*adunitconfig.AdUnitConfig, error)
Made consistent

2023-07-31 06:01 UTC, pm-nilesh-chate requested changes
approved with comments

2023-07-31 10:10 UTC, pm-saurabh-narkhede commented on modules/pubmatic/openwrap/database/mysql/slot_mapping_test.go
> +func Test_mySqlDB_GetPubmaticSlotMappings(t *testing.T) {
done

2023-08-01 05:26 UTC, pm-nilesh-chate approved these changes

2023-08-01 06:31 UTC, AvinashKapre approved these changes

2023-08-01 06:43 UTC, pm-nilesh-chate approved these changes

2023-08-01 06:43 UTC, merged