OTT-1182: RecordPartnerConfigErrors for slot-not-mapped and mis-config errors
PubMatic-OpenWrap/prebid-server pull request #536
Opened 2023-07-31 03:35 UTC by ashishshinde-pubm

2023-07-31 06:04 UTC, pm-nilesh-chate requested changes

2023-07-31 06:04 UTC, pm-nilesh-chate commented on modules/pubmatic/openwrap/beforevalidationhook.go
> +				slot, kgpv, isRegex, bidderParams, err = bidderparams.PrepareAdapterParamsV25(rCtx, m.cache, *payload.BidRequest, imp, *impExt, partnerID, bidderCode)
no need to pass `bidderCode`, it is accessible via `rctx.PartnerConfigMap[partnerID]`

2023-07-31 06:55 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/beforevalidationhook.go
> +				slot, kgpv, isRegex, bidderParams, err = bidderparams.PrepareAdapterParamsV25(rCtx, m.cache, *payload.BidRequest, imp, *impExt, partnerID, bidderCode)
Fixed it by using the rctx.PartnerConfigMap[partnerID][models.BidderCode] for partner-name.

2023-07-31 11:13 UTC, ashishshinde-pubm commented
As per the discussion with @pm-viral-vala , we don't need this metric to record mis-config errors, it does not add fruitful information. 
Only having the slot-not-mapped error itself is enough to determine the partner level configuration issue.

2023-08-01 04:48 UTC, pm-viral-vala approved these changes

2023-08-01 04:49 UTC, merged