UOE-9179: Cache OpenWrap's DB details
PubMatic-OpenWrap/prebid-server pull request #537
Opened 2023-08-01 08:02 UTC by AvinashKapre

# Description

Please add change description or link to ticket, docs, etc.

# Checklist:

- [ ] PR commit list is unique (rebase/pull with the origin branch to keep master clean).
- [ ] JIRA number is added in the PR title and the commit message.
- [ ] Updated the `header-bidding` repo with appropiate commit id.
- [ ] Documented the new changes.

For Prebid upgrade, refer: https://inside.pubmatic.com:8443/confluence/display/Products/Prebid-server+upgrade

2023-08-02 06:48 UTC, aadit-patil commented on modules/pubmatic/openwrap/cache/gocache/fsc_test.go
> +			name: "Error In DB, Set Empty",
can we add one more case invalid / floating percentage given as input, will be neglected you can refer existing _"Valid rows returned,avoiding floating pcnt values"_

2023-08-02 07:06 UTC, pm-saurabh-narkhede commented on modules/pubmatic/openwrap/cache/gocache/vast_tags_test.go
> +				101: {ID: 101, PartnerID: 501, URL: "vast_tag_url_1", Duration: 15, Price: 2.0},
add tests for duplicate vastTags

2023-08-02 07:12 UTC, pm-saurabh-narkhede submitted a review, later dismissed

2023-08-02 07:18 UTC, AvinashKapre commented on modules/pubmatic/openwrap/cache/gocache/fsc_test.go
> +			name: "Error In DB, Set Empty",
already handled error in the mock.

2023-08-02 09:04 UTC, pm-nilesh-chate requested changes
added a few comments

2023-08-02 09:04 UTC, pm-nilesh-chate commented on modules/pubmatic/openwrap/cache.go
> +func getTestModePartnerConfigMap(platform string, timeout int64, displayVersion int) map[int]map[string]string {
move this function to `profiledata.go` and delete this file

2023-08-03 05:41 UTC, AvinashKapre commented on modules/pubmatic/openwrap/cache/gocache/adunit_config_test.go
> +	tests := []struct {
Done

2023-08-03 05:57 UTC, AvinashKapre commented on modules/pubmatic/openwrap/cache/gocache/adunit_config_test.go
> +				adunitConfig: []byte(`{"configPattern":"_AU_","regex":true,"config":{"default":{"floors":{"floormin":15,"data":{"currency":"USD","modelgroups":[{"currency":"USD","modelweight":40,"modelversion":"
Done

2023-08-03 06:42 UTC, AvinashKapre commented on modules/pubmatic/openwrap/cache/gocache/adunit_config_test.go
> +			if obj != nil {
Done

2023-08-03 06:45 UTC, AvinashKapre commented on modules/pubmatic/openwrap/cache.go
> +func getTestModePartnerConfigMap(platform string, timeout int64, displayVersion int) map[int]map[string]string {
Done

2023-08-03 06:56 UTC, AvinashKapre commented on modules/pubmatic/openwrap/cache/gocache/vast_tags.go
> -func (c *cache) populatePublisherVASTTags(pubid int) {
If we remove check from caller then it always call `LockAndLoad` 
`if mapNameHash, ok := c.cache.Get(key(PubSlotNameHash, pubID)); !ok || mapNameHash == nil {
		c.LockAndLoad(pubLockKey, func() error {
			dbAccessed = true
			return c.populateCacheWithPubSlotNameHash(pubID)
		})
		//TODO: Add stat if error from the DB
	}`

2023-08-03 08:24 UTC, pm-nilesh-chate commented on modules/pubmatic/openwrap/cache/gocache/adunit_config_test.go
> +	}
```
err := c.populateCacheWithAdunitConfig(tt.args.pubID, tt.args.profileID, tt.args.displayVersion)
if assert.Equal(t, wantErr, err != nil) {
    assert.Equal(t, tt.want.adunitConfig, gotAdunitConfig)
}  else {
    assert.Equal(t, nil, gotAdunitConfig)    
}
```

2023-08-03 10:39 UTC, pm-nilesh-chate commented on modules/pubmatic/openwrap/cache/gocache/slot_mappings.go
> +	}
remove this check to keep current behaviour as is

2023-08-03 11:00 UTC, AvinashKapre commented on modules/pubmatic/openwrap/cache/gocache/slot_mappings.go
> +	}
Done

2023-08-03 11:16 UTC, pm-saurabh-narkhede approved these changes

2023-08-03 11:18 UTC, pm-aadit-patil approved these changes

2023-08-03 11:25 UTC, pm-nilesh-chate approved these changes

2023-08-03 11:25 UTC, merged