UOE-9434: migrate sshb metrics to pbs-ow module
PubMatic-OpenWrap/prebid-server pull request #551
Opened 2023-08-14 08:26 UTC by pm-nilesh-chate

# Description

Please add change description or link to ticket, docs, etc.

# Checklist:

- [ ] PR commit list is unique (rebase/pull with the origin branch to keep master clean).
- [ ] JIRA number is added in the PR title and the commit message.
- [ ] Updated the `header-bidding` repo with appropiate commit id.
- [ ] Documented the new changes.

For Prebid upgrade, refer: https://inside.pubmatic.com:8443/confluence/display/Products/Prebid-server+upgrade

2023-08-16 11:34 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/metrics/prometheus/prometheus.go
> +	newSSHBMetrics(&metrics, cfg, promRegistry)
As we discussed, we will be using same namespace "ow" and subsytem "pbs" name as that of prebid's openwrap module. 
Due to this, we wont be able to differentiate metrics from header-bidding and prebid-OW module.
But since the header-bidding specific metrics are NOT getting used in any dashboards there wont be any impact.

2023-08-24 08:22 UTC, pm-nilesh-chate commented on modules/pubmatic/openwrap/metrics/prometheus/prometheus_sshb.go
> +		"sshb_sshb_request_time",
done

2023-08-24 08:28 UTC, ashishshinde-pubm commented on Makefile
> +mockgen: mockgeninstall mockgendb mockgencache mockgenprometheus
should this be mockgenmetrics ?

2023-08-24 08:35 UTC, ashishshinde-pubm approved these changes
Looks good

2023-08-24 08:35 UTC, pm-nilesh-chate commented on Makefile
> +mockgen: mockgeninstall mockgendb mockgencache mockgenprometheus
done

2023-08-24 08:36 UTC, ashishshinde-pubm approved these changes

2023-08-25 08:16 UTC, Pubmatic-Dhruv-Sonone requested changes

2023-08-25 08:16 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/metrics/config/metrics.go
> +	}
Add comments to function to avoid new codacy issues.

2023-08-25 10:05 UTC, Pubmatic-Dhruv-Sonone submitted a review, later dismissed

2023-08-28 09:03 UTC, pm-nikhil-vaidya submitted a review, later dismissed
LGTM

2023-08-31 06:57 UTC, pm-nilesh-chate commented on modules/pubmatic/openwrap/metrics/config/metrics.go
> +	}
done

2023-08-31 06:59 UTC, ashishshinde-pubm approved these changes

2023-08-31 07:01 UTC, merged