OTT-1281: Add SeatNonBids in bidResponse only if returnallbidstatus is true
PubMatic-OpenWrap/prebid-server pull request #558
Opened 2023-08-30 12:06 UTC by ashishshinde-pubm

It contains following 2 changes -
1. Checks the bidrequest.ext.prebid.returnallbidsstatus flag before computing and adding the seat-non-bids in response
2. Adds the safe check if responseExt.Prebid is nil. For valid bidresponse it will never be nil. However, if code flow goes through rejectAuctionRequest then it will be nil and in that case code panics.

2023-08-30 12:11 UTC, pm-nilesh-chate approved these changes

2023-08-30 12:11 UTC, pm-nilesh-chate commented
LGTM. Would suggest to add UT

2023-08-30 16:31 UTC, Pubmatic-Dhruv-Sonone requested changes

2023-08-31 03:15 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/auctionresponsehook_test.go
> +				mockEngine.EXPECT().RecordPublisherResponseTimeStats(gomock.Any(), gomock.Any())
Done

2023-08-31 03:16 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/nonbids_test.go
> +				assert.ElementsMatch(t, v, tt.seatNonBids[k], tt.name)
Note - reflect.DeepEqual and assert.Equal checks the order of elements in slice. 
In this case, order of elements returned by prepareSeatNonBids may vary.

2023-08-31 03:56 UTC, Pubmatic-Dhruv-Sonone approved these changes

2023-08-31 10:26 UTC, Pubmatic-Dhruv-Sonone approved these changes

2023-08-31 11:41 UTC, pm-nilesh-chate approved these changes

2023-08-31 11:41 UTC, merged