UOE-9172: BeforeValidation hook- update the incoming request in OpenW…
PubMatic-OpenWrap/prebid-server pull request #566
Opened 2023-09-12 11:58 UTC by AvinashKapre

…rap module

# Description

Please add change description or link to ticket, docs, etc.

# Checklist:

- [ ] PR commit list is unique (rebase/pull with the origin branch to keep master clean).
- [ ] JIRA number is added in the PR title and the commit message.
- [ ] Updated the `header-bidding` repo with appropiate commit id.
- [ ] Documented the new changes.

For Prebid upgrade, refer: https://inside.pubmatic.com:8443/confluence/display/Products/Prebid-server+upgrade

2023-09-13 10:36 UTC, pm-nilesh-chate commented on modules/pubmatic/openwrap/adunitconfig/utils.go
> +		slotConfig.BidFloorCur = ptrutil.ToPtr[string](models.USD)
use `ptrutil.ToPtr(models.USD)`

2023-09-13 10:42 UTC, pm-nilesh-chate commented on modules/pubmatic/openwrap/beforevalidationhook.go
>  	return pubID, err
you can do a blank `return` here

2023-10-03 09:45 UTC, pm-nikhil-vaidya reviewed
LGTM

2023-10-04 06:46 UTC, PubMatic-OpenWrap requested changes

2023-10-04 06:46 UTC, PubMatic-OpenWrap commented on modules/pubmatic/openwrap/abtest_test.go
> +			name: "AbTest_is_enabled_and_random_no_return_apply_AbTest",
Can we add one more condition for `groupsize=90` and `randomvalue>90`?

2023-10-04 06:46 UTC, PubMatic-OpenWrap commented on modules/pubmatic/openwrap/abtest_test.go
> +			}
can we use `assert.Equal` function?

2023-10-04 06:46 UTC, PubMatic-OpenWrap commented on modules/pubmatic/openwrap/abtest_test.go
> +			got, got1 := ABTestProcessing(tt.args.rctx)
can we rename got and got1 with name like `(config,found)` ?

2023-10-04 06:46 UTC, PubMatic-OpenWrap commented on modules/pubmatic/openwrap/abtest_test.go
> +		m map[int]map[string]string
can we rename name for variable to config?

2023-10-04 06:46 UTC, PubMatic-OpenWrap commented on modules/pubmatic/openwrap/adapterthrottle_test.go
> +			name: "All_prtners_throttled",
can we correct partner spelling in other test cases too?

2023-10-04 06:46 UTC, PubMatic-OpenWrap commented on modules/pubmatic/openwrap/adapterthrottle_test.go
> +			}
please use `assert.Equal` for asserting purpose.

2023-10-04 06:46 UTC, PubMatic-OpenWrap commented on modules/pubmatic/openwrap/adapterthrottle_test.go
> +			name: "All_prtners_throttled",
this is case for `all_partner_are_client_side_throttled`.

2023-10-04 06:46 UTC, PubMatic-OpenWrap commented on modules/pubmatic/openwrap/adapterthrottle_test.go
> +		{
Can we add `all_server_side partner_throttled` case too?

2023-10-04 06:46 UTC, PubMatic-OpenWrap commented on modules/pubmatic/openwrap/util.go
> +		return false
you can directly return like
`return deviceType == adcom1.DeviceMobile || deviceType == adcom1.DeviceTablet || deviceType == adcom1.DevicePhone`

2023-10-04 06:46 UTC, PubMatic-OpenWrap commented on modules/pubmatic/openwrap/util.go
> +	return false
you can return directly instead of if condition

2023-10-04 06:46 UTC, PubMatic-OpenWrap commented on modules/pubmatic/openwrap/util.go
> -			}
why this is removed, any specific reason?

2023-10-04 08:41 UTC, pm-isha-bharti requested changes

2023-10-04 08:41 UTC, pm-isha-bharti commented on modules/pubmatic/openwrap/beforevalidationhook_test.go
> +				},
Add missing UTs for fields like `schain`, `wlang` etc

2023-10-04 08:41 UTC, pm-isha-bharti commented on modules/pubmatic/openwrap/bidderparams/pubmatic_test.go
> +		},
Include UTs for 

- Pubmatic secondary case 
- When Video object is present in the request and 0x0 is sent in the adSlot field in the pubmatic params
- When native object is present in the request and 1x1 is sent in the adSlot field in the pubmatic params

2023-10-04 08:52 UTC, pm-isha-bharti commented on modules/pubmatic/openwrap/profiledata_test.go
> +			name: "get_profile_data_for_other_than_test_mode_and_cache_returned_error",
Rename the test as it is a test request, 
`IsTestRequest: 1` on line no `177`

2023-10-10 06:39 UTC, AvinashKapre commented on modules/pubmatic/openwrap/util.go
> -			}
`getDomainFromUrl` method parsing the URL already so no need to parse again. if we do so will get empty `pageURL`. keeping behaviour same to header-bidding.

2023-10-10 06:57 UTC, AvinashKapre commented on modules/pubmatic/openwrap/abtest_test.go
> +func Test_copyPartnerConfigMap(t *testing.T) {
Done

2023-10-10 06:57 UTC, AvinashKapre commented on modules/pubmatic/openwrap/abtest_test.go
> +func Test_replaceControlConfig(t *testing.T) {
Done

2023-10-10 06:57 UTC, AvinashKapre commented on modules/pubmatic/openwrap/abtest_test.go
> +func Test_copyTestConfig(t *testing.T) {
Done

2023-10-10 06:58 UTC, AvinashKapre commented on modules/pubmatic/openwrap/beforevalidationhook_test.go
> +func Test_getPageURL(t *testing.T) {
Done

2023-10-10 07:00 UTC, AvinashKapre commented on modules/pubmatic/openwrap/beforevalidationhook_test.go
> +			name: "imp_has_banner_object_but_adunitConfig_banner_is_nil._imp_video_will_not_be_updated",
Done

2023-10-10 07:02 UTC, AvinashKapre commented on modules/pubmatic/openwrap/adunitconfig/regex_test.go
> +func Test_getRegexMatch(t *testing.T) {
Done

2023-10-10 07:02 UTC, AvinashKapre commented on modules/pubmatic/openwrap/abtest_test.go
> +		val  int
Done

2023-10-10 07:02 UTC, AvinashKapre commented on modules/pubmatic/openwrap/abtest_test.go
> +			name: "AbTest_is_enabled_and_random_no_return_apply_AbTest",
Done

2023-10-10 07:02 UTC, AvinashKapre commented on modules/pubmatic/openwrap/abtest_test.go
> +			}
Done

2023-10-10 07:03 UTC, AvinashKapre commented on modules/pubmatic/openwrap/abtest_test.go
> +			got, got1 := ABTestProcessing(tt.args.rctx)
Done

2023-10-10 07:03 UTC, AvinashKapre commented on modules/pubmatic/openwrap/abtest_test.go
> +		m map[int]map[string]string
Done

2023-10-10 07:04 UTC, AvinashKapre commented on modules/pubmatic/openwrap/adapterthrottle_test.go
> +			name: "All_prtners_throttled",
Done

2023-10-10 07:04 UTC, AvinashKapre commented on modules/pubmatic/openwrap/adapterthrottle_test.go
> +			}
Done

2023-10-10 07:04 UTC, AvinashKapre commented on modules/pubmatic/openwrap/adapterthrottle_test.go
> +			name: "All_prtners_throttled",
Done

2023-10-10 07:04 UTC, AvinashKapre commented on modules/pubmatic/openwrap/adapterthrottle_test.go
> +		{
Done

2023-10-10 07:05 UTC, AvinashKapre commented on modules/pubmatic/openwrap/util.go
> +		return false
Done

2023-10-10 07:05 UTC, AvinashKapre commented on modules/pubmatic/openwrap/util.go
> +	return false
Done

2023-10-10 08:17 UTC, AvinashKapre commented on modules/pubmatic/openwrap/beforevalidationhook_test.go
> +							ID: "5890",
Done

2023-10-10 08:22 UTC, AvinashKapre commented on modules/pubmatic/openwrap/adapters/bidders.go
> +func builderUnruly(params BidderParameters) (json.RawMessage, error) {
Will address this in the removing bidder info and bidder param static file in header-bidding.

2023-10-10 08:24 UTC, AvinashKapre commented on modules/pubmatic/openwrap/adapterthrottle_test.go
> +						models.SERVER_SIDE_FLAG:    "0",
Added both the cases server-side enabled =0 and 1.

2023-10-10 08:24 UTC, AvinashKapre commented on modules/pubmatic/openwrap/adunitconfig/utils_test.go
> +func Test_getFinalSlotAdUnitConfig(t *testing.T) {
Done

2023-10-10 08:29 UTC, AvinashKapre commented on modules/pubmatic/openwrap/adunitconfig/video_test.go
> +		},
Added the test case `Video_config_is_prsent_in_both_default_and_slot_preferance_is_given_to_slot_level`

2023-10-10 10:25 UTC, AvinashKapre commented on modules/pubmatic/openwrap/abtest_test.go
> +			}
Done

2023-10-10 10:25 UTC, AvinashKapre commented on modules/pubmatic/openwrap/adunitconfig/utils_test.go
> +func Test_getDefaultAllowedConnectionTypes(t *testing.T) {
Done

2023-10-10 16:58 UTC, AvinashKapre commented on modules/pubmatic/openwrap/beforevalidationhook_test.go
> +				},
Done

2023-10-10 17:05 UTC, AvinashKapre commented on modules/pubmatic/openwrap/profiledata_test.go
> +			name: "get_profile_data_for_other_than_test_mode_and_cache_returned_error",
Done

2023-10-10 17:12 UTC, AvinashKapre commented on modules/pubmatic/openwrap/adunitconfig/banner_test.go
> +									Enabled: ptrutil.ToPtr(true),
Added case `Banner_config_is_prsent_in_both_default_and_slot_preferance_is_given_to_slot_level`

2023-10-11 06:57 UTC, AvinashKapre commented on modules/pubmatic/openwrap/bidderparams/pubmatic_test.go
> +		},
Done

2023-10-12 18:55 UTC, AvinashKapre commented on modules/pubmatic/openwrap/bidderparams/pubmatic_test.go
> +		},
Done

2023-10-16 06:44 UTC, PubMatic-OpenWrap approved these changes

2023-10-16 06:50 UTC, pm-isha-bharti commented on modules/pubmatic/openwrap/bidderparams/pubmatic_test.go
> +				imp:       getTestImp("/Test_Adunit1234", false, false),
Is this a native request?

2023-10-16 06:55 UTC, pm-isha-bharti commented on modules/pubmatic/openwrap/bidderparams/pubmatic_test.go
> +			name: "pubmatic_param_for_native_default",
We have two test cases with the same name: `pubmatic_param_for_native_default`. You may want to use one for the video case

2023-10-16 07:01 UTC, pm-isha-bharti approved these changes

2023-10-16 08:22 UTC, PubMatic-OpenWrap approved these changes

2023-10-16 08:23 UTC, merged