Addressed Encoding problem in kvm macro
PubMatic-OpenWrap/prebid-server pull request #578
Opened 2023-10-10 08:59 UTC by Ankit-Pinge

2023-10-23 05:22 UTC, pm-jaydeep-mohite commented on adapters/vastbidder/bidder_macro.go
> +// GetValue returns the value from KV map wrt key
Correct function description

2023-10-23 05:23 UTC, pm-jaydeep-mohite commented on adapters/vastbidder/bidder_macro.go
> +	tempKeys := strings.Split(key, ".")
can we rename it to `macroKeys` ?

2023-10-23 05:25 UTC, pm-jaydeep-mohite commented on adapters/vastbidder/bidder_macro.go
> +			return "", true
we can remove this `return` statement

2023-10-23 05:27 UTC, pm-jaydeep-mohite commented on adapters/vastbidder/bidder_macro.go
> +			keyval += fmt.Sprintf("%s=%v&", key, jsonString)
We can use string concatenation instead of Sprintf() 

`keyval += key + "=" + jsonString + "&"`

2023-10-23 05:28 UTC, pm-jaydeep-mohite commented on adapters/vastbidder/bidder_macro.go
> +		keyval += fmt.Sprintf("%s=%v&", key, val)
We can use string concatenation instead of Sprintf()

2023-10-23 05:29 UTC, pm-jaydeep-mohite commented on adapters/vastbidder/util.go
> +
Remove empty 1st line and last line in this function

2023-10-23 06:22 UTC, Ankit-Pinge commented on adapters/vastbidder/bidder_macro.go
> +// GetValue returns the value from KV map wrt key
Done

2023-10-23 06:24 UTC, Ankit-Pinge commented on adapters/vastbidder/bidder_macro.go
> +	tempKeys := strings.Split(key, ".")
Yes we can rename it to macroKeys

2023-10-23 06:24 UTC, Ankit-Pinge commented on adapters/vastbidder/bidder_macro.go
> +			return "", true
Done

2023-10-23 06:25 UTC, Ankit-Pinge commented on adapters/vastbidder/bidder_macro.go
> +			keyval += fmt.Sprintf("%s=%v&", key, jsonString)
Done

2023-10-23 06:28 UTC, Ankit-Pinge commented on adapters/vastbidder/bidder_macro.go
> +		keyval += fmt.Sprintf("%s=%v&", key, val)
Here we are not able to use the  string concatenation as val is not always string type so by using  fmt.Sprintf() function we can convert it to string and then appending to keyval string

2023-10-23 06:29 UTC, Ankit-Pinge commented on adapters/vastbidder/util.go
> +
Done

2023-10-23 08:49 UTC, pm-jaydeep-mohite commented on adapters/vastbidder/bidder_macro.go
> +// GetValue return the value from KV map corresponding to key
can we add details about bool return

2023-10-23 09:44 UTC, pm-viral-vala requested changes

2023-10-23 09:44 UTC, pm-viral-vala commented on adapters/vastbidder/bidder_macro_test.go
> +				"url": "http://example.com?k1=v1&k2=v2",
this will break the final URL so please rename test cases with unencoded URLs.

2023-10-24 09:56 UTC, ShriprasadM requested changes
Please check my review comments

2023-10-24 09:56 UTC, ShriprasadM commented on adapters/vastbidder/bidder_macro.go
> +	return "", isKeyFound
@Ankit-Pinge : Check if we can write above function as follows.
```go
func (tag *BidderMacro) GetValue(key string) (string, bool) {
	if tag.kv == nil ||  (macroKeys[0] != prefixkv && macroKeys[0] != prefixkvm)  {
            return "", false
	}
	val := extractDataFromMap(macroKeys[1:], tag.KV)
	if isMap(val) {
		return getJsonString(val), true
	}
	return val , true
}
```

2023-10-24 09:56 UTC, ShriprasadM commented on adapters/vastbidder/bidder_macro.go
> +	return data.Encode()
Ensure that we are updating community documentation with following use cases
```
internal map = {
    "a": "b",
    "url": "http://google.com?x=y&p=q&u=http%3A%2F%2Ffacebook.com%3F1%3D2%263%3D4"
}


kv = & seperated version



Use Case 1: User want to pass only url to vast bidder


bidder url - http://somebidder.com?myurl={kv.url_ESC} 


Use case 2 : User wants to pass entire custom key-values in & seperated format.
 custom values contains url like patterns. In such a case prefer levels of url escapes

bidder url - http://somebidder.com?keyvalues={kv}

kv will looke like below. 

a=b & url=http://google.com?x=y&p=q&u=http%3A%2F%2Ffacebook.com%3F1%3D2%263%3D4

this will break the parsing on somebidder.com side. So, we should do two level esacpe, as follows. this is already taken care by OW S2S.

a=b & url=http%3A%2F%2Fgoogle.com%3Fx%3Dy%26p%3Dq%26u%3Dhttp%253A%252F%252Ffacebook.com%253F1%253D2%25263%253D4

for 2nd level of encoding use {kv_ESC} instead of {kv}, after that it will look like
a%3Db%26url%3Dhttp%253A%252F%252Fgoogle.com%253Fx%253Dy%2526p%253Dq%2526u%253Dhttp%25253A%25252F%25252Ffacebook.com%25253F1%25253D2%2525263%25253D4








```

2023-10-24 09:56 UTC, ShriprasadM commented on adapters/vastbidder/util.go
> +func extractDataFromMap(keyOrder []string, dataMap map[string]interface{}) interface{} {
change function definition to receiver function as follows

```go

func (tag *BidderMacro) getValueFromKV(lookUpOrder []string)  interface{} {
   // ....
      nextVal, _ :=  tag.kv[lookUpOrder[0]];
    // ....
    // recursive call
   return  tag.getValueFromKV(lookUpOrder[1:]);
}

```

2023-10-24 10:23 UTC, pm-viral-vala requested changes

2023-10-24 10:23 UTC, pm-viral-vala commented on adapters/vastbidder/bidder_macro.go
> +	return data.Encode()
can we write something like below? this is a utility function that will goes inside of `util.go` file
```
func mapToQuery(m map[string]any) string {
	values := url.Values{}
	for key, value := range m {
		switch reflect.TypeOf(value).Kind() {
		case reflect.Map:
			mvalue, ok := value.(map[string]any)
			if ok {
				values.Add(key, mapToQuery(mvalue))
			}
		default:
			values.Add(key, fmt.Sprintf("%v", value))
		}
	}
	return values.Encode()
}
```

2023-10-24 10:23 UTC, pm-viral-vala commented on adapters/vastbidder/bidder_macro_test.go
> +			name: "valid_Key",
can we keep the name in small case only?

2023-10-24 19:08 UTC, Ankit-Pinge commented on adapters/vastbidder/util.go
> +func extractDataFromMap(keyOrder []string, dataMap map[string]interface{}) interface{} {
Done

2023-10-25 09:26 UTC, Ankit-Pinge commented on adapters/vastbidder/bidder_macro_test.go
> +			name: "valid_Key",
Done

2023-10-25 09:26 UTC, Ankit-Pinge commented on adapters/vastbidder/util.go
> +		return extractDataFromMap(keyOrder[1:], nestedMap)
Done

2023-10-25 09:29 UTC, Ankit-Pinge commented on adapters/vastbidder/bidder_macro.go
> +	return "", isKeyFound
Yes i have checked but it there are some edge cases for which it will break

2023-10-25 09:30 UTC, Ankit-Pinge commented on adapters/vastbidder/bidder_macro.go
> +// GetValue return the value from KV map corresponding to key
Added

2023-10-25 09:30 UTC, Ankit-Pinge commented on adapters/vastbidder/constant.go
> +	prefixkvm = "kvm"
Yes we can use it

2023-10-25 09:30 UTC, Ankit-Pinge commented on adapters/vastbidder/util.go
> +	t := fmt.Sprintf("%T", data)
Done

2023-10-25 09:33 UTC, Ankit-Pinge commented on adapters/vastbidder/bidder_macro.go
> +		}
Yes we can do it using loop.

2023-10-25 09:33 UTC, Ankit-Pinge commented on adapters/vastbidder/bidder_macro_test.go
> +			value, _ := tag.GetValue(tt.args.key)
Done

2023-10-25 09:33 UTC, Ankit-Pinge commented on adapters/vastbidder/bidder_macro_test.go
> +			name: "key_with_value_as_map",
Removed

2023-10-25 09:35 UTC, Ankit-Pinge commented on adapters/vastbidder/bidder_macro_test.go
> +				"url": "http://example.com?k1=v1&k2=v2",
Done

2023-10-25 09:40 UTC, Ankit-Pinge commented on adapters/vastbidder/bidder_macro_test.go
> +		},
Added testcases. For point 3 work of this function is only return the value from map encoding part will be taken care while replacing  macro

2023-10-25 11:27 UTC, pm-viral-vala requested changes

2023-10-25 11:27 UTC, pm-viral-vala commented on adapters/vastbidder/bidder_macro.go
> +
Can we do something like below?
```
switch macroKeys[0] {
case MacroKV:
val := tag.getValueFromKV(macrosKeys[1:])
if isMap(val) {
  return mapToString(val), true
}
return fmt.Sprintf("%v", val), true
case MacroKVM:
val := tag.getValueFromKV(macrosKeys[1:])
if isMap(val) {
  return getJSONString(val), true
}
return fmt.Sprintf("%v", val), true
}
```

2023-10-25 11:27 UTC, pm-viral-vala commented on adapters/vastbidder/util.go
> +func (tag *BidderMacro) getValueFromKV(keyOrder []string) any {
Please add separate test cases for it.

2023-10-25 11:27 UTC, pm-viral-vala commented on adapters/vastbidder/util.go
> +func getJsonString(kvmap any) string {
Please use JSON in capital whenever creating a variable.

2023-10-25 11:27 UTC, pm-viral-vala commented on adapters/vastbidder/util.go
> +func (tag *BidderMacro) getValueFromKV(keyOrder []string) any {
Please make it generic and remove from BidderMacro struct

2023-10-25 11:27 UTC, pm-viral-vala commented on adapters/vastbidder/ibidder_macro.go
> +	getValueFromKV(lookUpOrder []string) any
Please remove this

2023-10-26 06:16 UTC, pm-viral-vala approved these changes

2023-10-26 06:36 UTC, ShriprasadM commented on adapters/vastbidder/bidder_macro.go
> +	return "", isKeyFound
Ok.

2023-10-26 06:50 UTC, ShriprasadM commented on adapters/vastbidder/util.go
> +func extractDataFromMap(keyOrder []string, dataMap map[string]interface{}) interface{} {
Instead of above just rename the function as follows

```go
func getValueFromMap(lookUpOrder []string, m map[string]any)) any 
```

2023-10-26 06:50 UTC, ShriprasadM approved these changes
LGTM. Only address function rename part

2023-10-26 09:00 UTC, pm-viral-vala approved these changes

2023-10-26 09:01 UTC, merged