OTT-1319: add prometheus stats to count number of bids with vast unwrapped
PubMatic-OpenWrap/prebid-server pull request #590
Opened 2023-10-18 12:28 UTC by Pubmatic-Supriya-Patil

# Description

Please add change description or link to ticket, docs, etc.

# Checklist:

- [ ] PR commit list is unique (rebase/pull with the origin branch to keep master clean).
- [ ] JIRA number is added in the PR title and the commit message.
- [ ] Updated the `header-bidding` repo with appropiate commit id.
- [ ] Documented the new changes.

For Prebid upgrade, refer: https://inside.pubmatic.com:8443/confluence/display/Products/Prebid-server+upgrade

2023-10-19 05:14 UTC, ashishshinde-pubm approved these changes

2023-10-19 05:39 UTC, pm-jaydeep-mohite commented on metrics/prometheus/prometheus.go
> +		"Count of vast tag by bidder and vast tag",
Can we update Description 
 **Count of vast tag by bidder and vast tag type (Wrapper, Inline, URL, Unknown)**

2023-10-19 05:39 UTC, pm-jaydeep-mohite commented on metrics/prometheus/prometheus.go
> +		"vast_tag",
Rename to **vast_tag_type** ?

2023-10-19 12:23 UTC, Pubmatic-Supriya-Patil commented on metrics/prometheus/prometheus.go
> +		"Count of vast tag by bidder and vast tag",
Done

2023-10-19 12:23 UTC, Pubmatic-Supriya-Patil commented on metrics/prometheus/prometheus.go
> +		"vast_tag",
Done

2023-10-20 04:38 UTC, pm-jaydeep-mohite submitted a review, later dismissed
LGTM

2023-10-23 09:10 UTC, pm-jaydeep-mohite commented on exchange/exchange.go
> +		recordVastTag(e.me, adapterBids)
It needs to be recorded for only video creatives at  https://github.com/PubMatic-OpenWrap/prebid-server/blob/827463ec469fb6c442d8ee00726b34bfdc99a57e/exchange/bidder.go#L264

2023-10-24 10:00 UTC, pm-viral-vala commented on metrics/metrics.go
> +	RecordVastTag(bidder, vastTag string)
Please Rename function to `RecordVASTTagType`?

2023-10-24 10:01 UTC, pm-viral-vala commented on exchange/exchange_ow.go
> +func recordVastTag(metricsEngine metrics.MetricsEngine, adapterBids *adapters.BidderResponse, bidder openrtb_ext.BidderName) {
Please rename the function to recordVASTTagType.

2023-10-24 10:03 UTC, pm-viral-vala commented on metrics/metrics.go
>  	RecordHttpCounter()
Can we create a new file `metrics_ow.go` and add the `OWMetricsEngine` interface? This will put all OW-specific metrics in one place and will reduce conflicts in future prebid upgrades.
```
metrics_ow.go

type OWMetricsEngine interface {
 RecordVASTVersion()
 RecordVASTTagType() 
 RecordHTTPCounter()
}

metrics.go
type MetricsEngine interface {
  OWMetricsEngine
  ...
}

```

2023-10-24 10:04 UTC, pm-viral-vala commented on metrics/prometheus/prometheus.go
> +	vastTag      *prometheus.CounterVec
please rename variable to `vastTagType`

2023-10-24 10:06 UTC, pm-viral-vala commented on metrics/prometheus/prometheus_ow.go
> +	vastTagLabel = "vasttag"
can we use like `vastTagTypeLabel = "type"`

2023-10-24 10:06 UTC, pm-viral-vala commented on metrics/prometheus/prometheus_ow.go
> +func (m *Metrics) RecordVastTag(bidder, vastTag string) {
please rename variable from `vastTag` to `vastTagType`

2023-10-25 06:46 UTC, Pubmatic-Supriya-Patil commented on metrics/prometheus/prometheus_ow.go
> +func (m *Metrics) RecordVastTag(bidder, vastTag string) {
Done

2023-10-25 06:46 UTC, Pubmatic-Supriya-Patil commented on metrics/prometheus/prometheus_ow.go
> +	vastTagLabel = "vasttag"
Done

2023-10-25 06:47 UTC, Pubmatic-Supriya-Patil commented on metrics/prometheus/prometheus.go
> +	vastTag      *prometheus.CounterVec
Done

2023-10-25 06:48 UTC, Pubmatic-Supriya-Patil commented on exchange/exchange_ow.go
> +func recordVastTag(metricsEngine metrics.MetricsEngine, adapterBids *adapters.BidderResponse, bidder openrtb_ext.BidderName) {
Done

2023-10-25 06:48 UTC, Pubmatic-Supriya-Patil commented on metrics/metrics.go
> +	RecordVastTag(bidder, vastTag string)
Done

2023-10-25 06:48 UTC, Pubmatic-Supriya-Patil commented on exchange/exchange_ow_test.go
> +var vastXMLAdM = "<VAST version='3.0'><Ad id='1'><Wrapper><AdSystem>PubMatic</AdSystem><VASTAdTagURI><![CDATA[https://owsdk-stagingams.pubmatic.com:8443/openwrap/video/Shashank/dspResponse/vastInline
Done

2023-10-25 06:55 UTC, Pubmatic-Supriya-Patil commented on exchange/exchange_ow_test.go
> +			name: "No Bids",
Done

2023-10-25 06:56 UTC, Pubmatic-Supriya-Patil commented on exchange/exchange_ow.go
> +	return err == nil && url.Scheme != "" && url.Host != ""
As discussed with @pm-viral-vala we should have strict check for proper URL format where we will check for protocol also.So there is no change required

2023-10-25 06:58 UTC, Pubmatic-Supriya-Patil commented on exchange/exchange_ow.go
> +			if strings.Contains(adapterBid.Bid.AdM, WrapperElement) {
Done

2023-10-25 06:58 UTC, Pubmatic-Supriya-Patil commented on exchange/exchange_ow.go
> +func IsUrl(adm string) bool {
Done

2023-10-25 06:58 UTC, Pubmatic-Supriya-Patil commented on exchange/exchange_ow.go
> +	Unknown        = "Unknown"
Done

2023-10-25 06:58 UTC, Pubmatic-Supriya-Patil commented on exchange/exchange_ow.go
> +	WrapperElement = "<Wrapper>"
Done

2023-10-25 07:22 UTC, Pubmatic-Supriya-Patil commented on metrics/config/metrics.go
> +
Done

2023-10-25 07:23 UTC, Pubmatic-Supriya-Patil commented on metrics/config/metrics.go
> +}
Done

2023-10-25 07:25 UTC, Pubmatic-Supriya-Patil commented on metrics/metrics.go
>  	RecordHttpCounter()
Done

2023-10-25 11:12 UTC, pm-viral-vala requested changes

2023-10-25 11:12 UTC, pm-viral-vala commented on exchange/exchange_ow.go
> +	Unknown               = "Unknown"
Please remove this seems to be redundant

2023-10-25 11:12 UTC, pm-viral-vala commented on metrics/prometheus/prometheus.go
> +
Can we move this and other openwrap-specific objects in the `prometheus_ow.go` file?
```
type Metrics struct {
 owMetrics OWMetrics
}

prometheus_ow.go
type OWMetrics struct {
 vastTagType *prometheus.CounterVec
}

func (m *OWMetrics) init(conf, reg) {
// init all variables
}
```

2023-10-25 11:12 UTC, pm-viral-vala commented on metrics/prometheus/prometheus_ow_test.go
> +		description string
use name as standard variable name for test cases.

2023-10-25 11:12 UTC, pm-viral-vala commented on metrics/prometheus/prometheus_ow_test.go
> +		pm := createMetricsForTesting()
Please use below format 
```
for _, tt := range tests {
  t.Run(tt.name, func(t *testing.T) {
  })
}
```

2023-10-25 12:51 UTC, Pubmatic-Supriya-Patil commented on exchange/exchange_ow.go
> +	Unknown               = "Unknown"
Done

2023-10-25 12:51 UTC, Pubmatic-Supriya-Patil commented on metrics/prometheus/prometheus.go
> +
Done

2023-10-25 12:51 UTC, Pubmatic-Supriya-Patil commented on metrics/prometheus/prometheus_ow_test.go
> +		description string
Done

2023-10-25 12:52 UTC, Pubmatic-Supriya-Patil commented on metrics/prometheus/prometheus_ow_test.go
> +		pm := createMetricsForTesting()
Done

2023-10-26 04:35 UTC, pm-viral-vala approved these changes

2023-10-26 04:36 UTC, merged