OTT-1349 : Pass schain object to VAST bidder via schain macro
PubMatic-OpenWrap/prebid-server pull request #633
Opened 2023-11-02 12:00 UTC by Ankit-Pinge

2023-11-03 10:07 UTC, pm-jaydeep-mohite commented on adapters/vastbidder/bidder_macro.go
> +
Remove blank line

2023-11-03 10:07 UTC, pm-jaydeep-mohite commented on adapters/vastbidder/bidder_macro.go
> +		}
Don't we need `serializedSchain.WriteString(",") ` in case of node.Domain = "" ?

2023-11-03 10:14 UTC, pm-jaydeep-mohite commented on adapters/vastbidder/bidder_macro_test.go
> +			name: "schain_with_single_node",
Try to cover all examples from https://github.com/InteractiveAdvertisingBureau/openrtb/blob/master/supplychainobject.md#single-hop---chain-complete-encoded-values

2023-11-03 11:45 UTC, Ankit-Pinge commented on adapters/vastbidder/bidder_macro.go
> +		}
This will only require in case when node.Ext in present and it already handled in code 
`if node.Ext != nil {
			serializedSchain.WriteString("," + url.QueryEscape(string(node.Ext)))
		}`

2023-11-03 11:46 UTC, Ankit-Pinge commented on adapters/vastbidder/bidder_macro_test.go
> +			name: "schain_with_single_node",
Sure will add all the cases

2023-11-06 06:11 UTC, pm-viral-vala requested changes

2023-11-06 06:11 UTC, pm-viral-vala commented on adapters/vastbidder/bidder_macro.go
> +			serializedSchain.WriteString(url.PathEscape(fmt.Sprintf("%v", *node.HP)) + ",")
It is integer value we don't need PathEscape for HP parameter

2023-11-06 06:11 UTC, pm-viral-vala commented on adapters/vastbidder/bidder_macro.go
> +	var schainObj openrtb2.SupplyChain
Please add serializing of the `schain` object as a member function in the SupplyChain object or separate function, Check with @Pubmatic-Dhruv-Sonone for the correct location.

2023-11-06 06:11 UTC, pm-viral-vala commented on adapters/vastbidder/bidder_macro_test.go
> +	}{
Please add test cases for each condition that is written in the code. source object not present, schain object not present, schain extension parsing failed, etc.

2023-11-06 12:26 UTC, Ankit-Pinge commented on adapters/vastbidder/bidder_macro.go
> +	schain, _, _, err := jsonparser.Get(tag.Request.Source.Ext, MacroSchain)
Done

2023-11-06 12:26 UTC, Ankit-Pinge commented on adapters/vastbidder/bidder_macro.go
> +	serializedSchain.WriteString(schainObj.Ver + "," + fmt.Sprintf("%v", schainObj.Complete))
Done

2023-11-06 12:27 UTC, Ankit-Pinge commented on adapters/vastbidder/bidder_macro.go
> +		serializedSchain.WriteString("!")
Done

2023-11-06 12:27 UTC, Ankit-Pinge commented on adapters/vastbidder/bidder_macro.go
> +
Done

2023-11-06 12:27 UTC, Ankit-Pinge commented on adapters/vastbidder/bidder_macro.go
> +	var serializedSchain strings.Builder
Done

2023-11-06 12:27 UTC, Ankit-Pinge commented on adapters/vastbidder/bidder_macro.go
> +		}
Done

2023-11-06 12:27 UTC, Ankit-Pinge commented on adapters/vastbidder/bidder_macro.go
> +			serializedSchain.WriteString(url.PathEscape(fmt.Sprintf("%v", *node.HP)) + ",")
Done

2023-11-06 12:29 UTC, Ankit-Pinge commented on adapters/vastbidder/bidder_macro.go
> +	var schainObj openrtb2.SupplyChain
Yes i have moved out this function to openrtb_ext package in supplyChain.go file

2023-11-06 13:21 UTC, pm-viral-vala commented on adapters/vastbidder/bidder_macro_test.go
> +	}{
Can we divide test cases into separate functions, as there are lots of test cases that are related to the `serializingSChain` object, which should be part of the `openrtb_ext/supplyChain_test.go` file?

2023-11-07 07:59 UTC, pm-viral-vala approved these changes

2023-11-07 08:48 UTC, pm-jaydeep-mohite approved these changes
LGTM

2023-11-07 08:57 UTC, pm-viral-vala approved these changes

2023-11-07 08:57 UTC, merged