OTT-1449: Traffic Shapping Framework
PubMatic-OpenWrap/prebid-server pull request #671
Opened 2023-12-18 11:08 UTC by Pubmatic-Dhruv-Sonone

# Description

**Traffic Shapping Framework:**
- Read bidding conditions from Adunit config
- Evaluate bidding condition for each bidder -> get filtered bidders list
- For each bidder check if bidder is filtered or not.

# Checklist:

- [ ] PR commit list is unique (rebase/pull with the origin branch to keep master clean).
- [ ] JIRA number is added in the PR title and the commit message.
- [ ] Updated the `header-bidding` repo with appropiate commit id.
- [ ] Documented the new changes.

For Prebid upgrade, refer: https://inside.pubmatic.com:8443/confluence/display/Products/Prebid-server+upgrade

2023-12-18 11:16 UTC, pm-nilesh-chate commented on modules/pubmatic/openwrap/cache/gocache/tracffic_shapping.go
file name type

2023-12-18 11:16 UTC, pm-nilesh-chate commented on modules/pubmatic/openwrap/beforevalidationhook.go
add UT

2023-12-18 11:19 UTC, pm-nilesh-chate commented on modules/pubmatic/openwrap/cache/gocache/tracffic_shapping_test.go
filename type

2023-12-18 11:21 UTC, pm-nilesh-chate commented on modules/pubmatic/openwrap/traffic_shapping.go
> +var countryAlpha3ToAlpha2Code = map[string]string{
is there a library available to avoid us maintaining this list?

2023-12-18 11:24 UTC, pm-nilesh-chate commented on modules/pubmatic/openwrap/traffic_shapping.go
> +func GetFilteredBidders(rCtx models.RequestCtx, bidRequest *openrtb2.BidRequest, cache cache.Cache, partnerConfigMap map[int]map[string]string) (map[string]bool, bool) {
`partnerConfigMap` is already part of rctx. `cache` reference can me moved to `rctx` to avoid it sending separately as param or implement Traffic Shaping as external dependency to address these issues.

2023-12-18 11:26 UTC, pm-nilesh-chate commented on modules/pubmatic/openwrap/traffic_shapping.go
> +func getCountryFromRequest(bidRequest *openrtb2.BidRequest) string {
This should be moved to beforevalidationhook so that country value can be reused. This would also eliminate need to pass BidRequest through all these functions

2023-12-18 11:27 UTC, pm-nilesh-chate commented on modules/pubmatic/openwrap/traffic_shapping.go
> +	country := getCountryFromRequest(BidRequest)
no empty check needed?

2023-12-18 11:30 UTC, pm-nilesh-chate commented on modules/pubmatic/openwrap/traffic_shapping_test.go
> +		want1 bool
use better name

2023-12-18 11:30 UTC, pm-nilesh-chate commented on modules/pubmatic/openwrap/traffic_shapping.go
> +	err := jsonlogic.Apply(logic, data, &result)
perf impact?

2023-12-18 11:30 UTC, pm-nilesh-chate approved these changes
LGTM, most of the comments are nitpicks

2023-12-18 11:31 UTC, pm-nilesh-chate requested changes
check the validate-merge failure

2023-12-18 11:59 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/beforevalidationhook.go
> +		filteredBidders, allBiddersDropped := GetFilteredBidders(rCtx, payload.BidRequest, m.cache, rCtx.PartnerConfigMap)
can we remove 'rCtx.PartnerConfigMap' argument ?

2023-12-18 13:00 UTC, ShriprasadM requested changes
@Pubmatic-Dhruv-Sonone : Please checkout my review comments

2023-12-19 06:11 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/traffic_shapping.go
> +var countryAlpha3ToAlpha2Code = map[string]string{
@ShriprasadM  We are using 2 letter country code. But ortb geo.country use 3 letter code. So we need to convert it to 2 letter code.

2023-12-19 06:38 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/traffic_shapping.go
> +			continue
Traffic shopping is part of openwrap module which is not applicable for hybrid profile.

2023-12-19 06:40 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/traffic_shapping.go
> +	biddingConditionPerBidder := cache.GetBidderFilterConditions(rCtx)
Bidding condition is just logical expression. Filter can contain other things like A/B testing scenarios, which can be supported in future.

2023-12-21 05:20 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/cache/gocache/tracffic_shapping.go
Fixed

2023-12-21 05:20 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/beforevalidationhook.go
Added UT

2023-12-21 05:20 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/cache/gocache/tracffic_shapping_test.go
Fixed

2023-12-21 05:21 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/traffic_shapping.go
> +func GetFilteredBidders(rCtx models.RequestCtx, bidRequest *openrtb2.BidRequest, cache cache.Cache, partnerConfigMap map[int]map[string]string) (map[string]bool, bool) {
User` partnerConfigMap` for rCtx. Not able to add cache to rCtx because of cyclic import issue.

2023-12-21 05:22 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/traffic_shapping.go
> +func getCountryFromRequest(bidRequest *openrtb2.BidRequest) string {
@ShriprasadM @pm-nilesh-chate. We are going to add support for others ortb fields as well. So we need bidRequest for latter use.

2023-12-21 05:23 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/traffic_shapping_test.go
> +		want1 bool
Changed

2023-12-21 05:24 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/traffic_shapping.go
> +	err := jsonlogic.Apply(logic, data, &result)
```
// Running tool: /usr/local/go/bin/go test -benchmem -run=^$ -coverprofile=/var/folders/z5/cj4zjtv15wn8yt53qzh57lnr0000gp/T/vscode-goiNJTYZ/go-code-cover -bench . test

// goos: darwin
// goarch: amd64
// pkg: test
// cpu: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
// BenchmarkEvaluate-12              	   57998	     20299 ns/op	   10220 B/op	     143 allocs/op
// BenchmarkJSONlOgicInterface-12    	  264285	      4462 ns/op	    1152 B/op	      35 allocs/op
// BenchmarkEvaluateRaw-12           	   63271	     18737 ns/op	    6987 B/op	     133 allocs/op
// BenchmarkEvaluateJSONParsing-12    	 5498480	       222.9 ns/op	       0 B/op	       0 allocs/op
// PASS
// coverage: [no statements]
// ok  	test	4.561s

```

@ShriprasadM @pm-nilesh-chate  These are different approach benchmark numbers. We are going with  BenchmarkJSONlOgicInterface-12 as we need to use jsonlogic syntax.

2023-12-21 05:24 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/beforevalidationhook.go
> +		filteredBidders, allBiddersDropped := GetFilteredBidders(rCtx, payload.BidRequest, m.cache, rCtx.PartnerConfigMap)
Removed

2023-12-21 05:24 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/cache/gocache/tracffic_shapping.go
> +			reader := bytes.NewReader(filterCfg.BiddingConditions)
Removed

2023-12-21 05:24 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/cache/gocache/tracffic_shapping.go
> +		for _, filterCfg := range defaultAdUnitConfig.BidderFilter.FilterConfig {
Done

2023-12-21 05:24 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/cache/gocache/tracffic_shapping.go
> +			}
Done

2023-12-21 06:53 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/models/adunitconfig/adunitconfig.go
> +	BidderFilter   *BidderFilter    `json:"bidder-filter,omitempty"`
using the same json template as prebid

2023-12-21 06:54 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/traffic_shapping.go
> +		biddingCondition, ok := biddingConditionPerBidder[partnerConfig[models.BidderCode]]
We are setting bidder filter against bidderCode. So it should work for alias bidder and vast bidder.

2023-12-21 06:55 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/traffic_shapping.go
> +	return strings.TrimRight(result.String(), "\r\n") == "true"
Changed to different implementation.

2023-12-21 06:55 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/traffic_shapping_test.go
> +func TestEvaluateLogic(t *testing.T) {
Fixed the test cases.

2023-12-21 06:55 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/traffic_shapping_test.go
> +			want1: false,
Changed

2023-12-21 06:56 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/traffic_shapping_test.go
> +			want:  map[string]bool{"bidderA": true},
Changed this logic. Now we will be return the list of filtered bidders i.e bidders that will be dropped from request.

2023-12-21 07:21 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/traffic_shapping.go
> +var countryAlpha3ToAlpha2Code = map[string]string{
> is there a library available to avoid us maintaining this list?

@pm-nilesh-chate  Could not find any library that is properly maintained.

2023-12-21 07:23 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/traffic_shapping.go
> +	country := getCountryFromRequest(BidRequest)
Not needed.

2023-12-21 07:27 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/traffic_shapping.go
> +	err := jsonlogic.Apply(logic, data, &result)
> perf

Once PR is approved. Will run performance. You can check the library benchmark above.

2023-12-21 09:46 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/traffic_shapping.go
> +func GetFilteredBidders(rCtx models.RequestCtx, bidRequest *openrtb2.BidRequest, c cache.Cache) (map[string]bool, bool) {
can we make it private if its not being used outside package. 
ignore this comment in case it is planned to use in future

2023-12-21 09:51 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/traffic_shapping.go
> +	filteredBidders := map[string]bool{}
if we are just going to store filteredBidders then can we make use of empty struct{} ?

2023-12-21 09:52 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/traffic_shapping.go
> +	bidderFilter := bf.(map[string]interface{})
can we validate the interface conversion ? otherwise we can check if bidderFilter is nil or not.

2023-12-21 09:55 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/traffic_shapping.go
> +	data["country"] = getCountryFromRequest(BidRequest)
can we use constant for country ?

2023-12-21 13:25 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/traffic_shapping.go
> +		glog.Errorf("Error evaluating bidding condition for rules: %v | data: %v | Error: %v", rules, data, err)
if it is not major issue then can we use debug log-level since this might add multiple error logs in production

2023-12-21 13:37 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/cache/gocache/adunit_config.go
> +		if defaultAdUnitConfig.BidderFilter != nil {
To avoid panic, should we add nil check for defaultAdUnitConfig ? else we can simply check if map contains that key or not.

2023-12-21 13:44 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/cache/gocache/gocache.go
> +	BidderFilter    = "bidderfilter_%d_%d_%d"
Plz add comment if possible

2023-12-21 13:56 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/cache/gocache/gocache.go
> +	BidderFilter    = "bidderfilter_%d_%d_%d"
Any particular reason, why we have introduced new key `bidderfilter_%d_%d_%d`.
We can get the same from rCtx.AdUnitConfig.
I think adding new key at pub-prof-version level will result in high memory usage.

Please ignore, if it is done to save the time required to get the "default" config and to build the map.

2023-12-21 14:01 UTC, ashishshinde-pubm requested changes
Please check my comments

2023-12-22 03:43 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/traffic_shapping.go
> +	filteredBidders := map[string]bool{}
Done

2023-12-22 03:45 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/traffic_shapping.go
> +	bidderFilter := bf.(map[string]interface{})
Done. Its not needed but added just for safety.

2023-12-22 03:46 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/traffic_shapping.go
> +	data["country"] = getCountryFromRequest(BidRequest)
Done

2023-12-22 03:53 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/beforevalidationhook.go
> +	filteredBidders, allPartnersFilteredFlag := GetFilteredBidders(rCtx, payload.BidRequest, m.cache)
It was discussed with product, first we need to check bidder filter and then throttling.

2023-12-22 03:53 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/cache/gocache/adunit_config.go
> +		if defaultAdUnitConfig.BidderFilter != nil {
```
	if _, ok := adunitConfig.Config["default"]; !ok {
		adunitConfig.Config["default"] = &adunitconfig.AdConfig{}
	}
```
This is handled in adunit db call.   default key will always be present.

2023-12-22 03:53 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/cache/gocache/gocache.go
> +	BidderFilter    = "bidderfilter_%d_%d_%d"
While add adunitconfig to cache we also want to generate  map of bidder -> filter condition and store in cache. Generating and retrieving this data for every request is expensive, so it's stored in cache. Hence this key is needed.

2023-12-22 03:53 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/traffic_shapping.go
> +		glog.Errorf("Error evaluating bidding condition for rules: %v | data: %v | Error: %v", rules, data, err)
I would prefer to keep it Error log for sometime. Letter can be changed to debug.

2023-12-22 03:55 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/traffic_shapping.go
> +func GetFilteredBidders(rCtx models.RequestCtx, bidRequest *openrtb2.BidRequest, c cache.Cache) (map[string]bool, bool) {
Done

2023-12-22 06:19 UTC, ShriprasadM requested changes

2023-12-22 06:19 UTC, ShriprasadM commented on modules/pubmatic/openwrap/traffic_shapping.go
> +func getCountryFromRequest(bidRequest *openrtb2.BidRequest) string {
@Pubmatic-Dhruv-Sonone : 
1. What are other ortb fields, where will be getting country information?
2. Does it mean existing `country` detection function is not having that support?

2023-12-22 06:19 UTC, ShriprasadM commented on modules/pubmatic/openwrap/traffic_shapping.go
> +			continue
@Pubmatic-Dhruv-Sonone : 
1. Do we keep client side partners (service side flag = 0) information in ` rCtx.PartnerConfigMap`?

2023-12-22 06:19 UTC, ShriprasadM commented on modules/pubmatic/openwrap/traffic_shapping.go
> +var countryAlpha3ToAlpha2Code = map[string]string{
@Pubmatic-Dhruv-Sonone : Instead of maintaining this in code, I could see following general way.

1.  Introduce `ISO-3166-1-alpha-3_country_code` column in `KomliAdServer.geo` table.
2. Update Common Geo API to return `ISO-3166-1-alpha-3.` code as well
3. Expect OpeWrap UI and API is able to pass and store this information in database
4. With this OpenWrap S2S can get the `ISO-3166-1-alpha-3` code.

Being this is OpenRTB standard
1. @Pubmatic-Dhruv-Sonone  : check with SSP team and SDK team how they do 2 letter - 3 letter conversion while sending it to oRTB based entities

2023-12-22 06:23 UTC, pm-viral-vala submitted a review, later dismissed

2023-12-22 07:09 UTC, ashishshinde-pubm submitted a review, later dismissed
LGTM

2023-12-22 08:52 UTC, ashishshinde-pubm approved these changes

2023-12-22 09:59 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/traffic_shapping.go
> +func getCountryFromRequest(bidRequest *openrtb2.BidRequest) string {
@ShriprasadM 
I don't see any existing country detection function in prebid/header-bidding code. If you are talking about video endpoint  `GetValueFromRequest` that can't be used here.
We need to pass BidRequest to the function because in future we will support other ortb fields for bidder filtering.

2023-12-22 10:03 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/traffic_shapping.go
> +			continue
@ShriprasadM  I don't sure probably yes, as  we are getting partnerConfigMap for (pubId,profid,version). Also version level properties are stored  with key as -1. So we need this check.

2023-12-22 10:07 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/traffic_shapping.go
> +var countryAlpha3ToAlpha2Code = map[string]string{
@ShriprasadM Checked with SDK team they are use some android/iOS sdk feature to check this details.
This country code information is not going to changes and rarely a new code will be added. Adding an api call just to get the converted code will increase latency. 
**huaweiads** bidder in prebid also maintains similar code map in memory.  I also not could not find any reliable go library for this.

2023-12-22 10:11 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/traffic_shapping.go
> +func getCountryFromRequest(bidRequest *openrtb2.BidRequest) string {
> This should be moved to beforevalidationhook so that country value can be reused. This would also eliminate need to pass BidRequest through all these functions
@pm-nilesh-chate 
This getCountry function  will also do a netacuity look for country. Is that needed for  other functionality? If yes, then I can move it in beforevalidationhook.

2023-12-26 06:38 UTC, ShriprasadM commented on modules/pubmatic/openwrap/traffic_shapping.go
> +var countryAlpha3ToAlpha2Code = map[string]string{
@Pubmatic-Dhruv-Sonone : Please check #3 and #4. Not sure, `where it is mentioned that S2S suppose to make a call`? So, there is no question o latency
The approach mentioned - Java API (header-bidding) should store the `ISO-3166-1-alpha-3` in our `giymdb` than `2 letter country code`. header-bidding UI (probably API) should expect the `ISO-3166-1-alpha-3` from Common API / KomliAdServer.geo table

2023-12-26 06:58 UTC, ShriprasadM requested changes

2023-12-26 06:58 UTC, ShriprasadM commented on modules/pubmatic/openwrap/traffic_shapping.go
> +func getCountryFromRequest(bidRequest *openrtb2.BidRequest) string {
@Pubmatic-Dhruv-Sonone : Ideally we should have common functionality for country detection. So, I would expect `netacuity` can be part of common functionality. and It can set in `requestContext (rCtx)`, once module determines it and others can use it
@pm-viral-vala  and @pm-jaydeep-mohite  : what are your thoughts here?

So, I could see this can be utility as 
```go
func getUserCountry(bidRequest) string {
   // your precedence logic will go here
}
```

2023-12-27 09:19 UTC, merged

2023-12-27 09:21 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/traffic_shapping.go
> +var countryAlpha3ToAlpha2Code = map[string]string{
We are going to use 3 letter codes now so this conversion is no longer needed.

2023-12-27 09:26 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/traffic_shapping.go
> +func getCountryFromRequest(bidRequest *openrtb2.BidRequest) string {
@pm-viral-vala  @pm-jaydeep-mohite  Can you please confirm this once?