UOE-9905: log device.ext.atts parameter in logger and tracker
PubMatic-OpenWrap/prebid-server pull request #675
Opened 2023-12-22 09:33 UTC by pm-viral-vala

# Description

Please add change description or link to ticket, docs, etc.

# Checklist:

- [ ] PR commit list is unique (rebase/pull with the origin branch to keep master clean).
- [ ] JIRA number is added in the PR title and the commit message.
- [ ] Updated the `header-bidding` repo with appropiate commit id.
- [ ] Documented the new changes.

For Prebid upgrade, refer: https://inside.pubmatic.com:8443/confluence/display/Products/Prebid-server+upgrade

2023-12-22 10:57 UTC, Pubmatic-Dhruv-Sonone requested changes

2023-12-22 10:57 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/util.go
> +}
Use constants

2023-12-22 11:36 UTC, ashishshinde-pubm approved these changes
LGTM.

Can you plz update details in - https://wiki.pubmatic.com/confluence/display/Products/Wrapper+Logger-Tracker+call+details

2023-12-22 11:36 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/beforevalidationhook.go
> +	rCtx.Device.Platform = GetDevicePlatform(rCtx, payload.BidRequest)
Not related to your code changes, but we can make this `GetDevicePlatform` function as private since its not being used outside package.

2023-12-22 11:53 UTC, pm-viral-vala commented on modules/pubmatic/openwrap/beforevalidationhook.go
> +	rCtx.Device.Platform = GetDevicePlatform(rCtx, payload.BidRequest)
1. Made GetDevicePlatform private function.
2. Updated Confluence Page with parameter details: https://wiki.pubmatic.com/confluence/display/Products/Wrapper+Logger-Tracker+call+details

2023-12-22 11:53 UTC, pm-viral-vala commented on modules/pubmatic/openwrap/util.go
> +}
Done

2023-12-22 12:05 UTC, Pubmatic-Dhruv-Sonone approved these changes

2024-01-10 06:37 UTC, pm-nilesh-chate approved these changes

2024-01-10 06:37 UTC, merged