OTT-1168: Support for traffic shaping based on country
PubMatic-OpenWrap/prebid-server pull request #676
Opened 2023-12-27 05:48 UTC by ashishshinde-pubm

2024-05-15 06:49 UTC, Pubmatic-Dhruv-Sonone requested changes

2024-05-15 06:49 UTC, Pubmatic-Dhruv-Sonone commented on .gitignore
> +analytics/build/xyz*
Remove this changes.

2024-05-15 06:49 UTC, Pubmatic-Dhruv-Sonone commented on analytics/pubmatic/logger.go
> +
Nitpick: Remove blank line.

2024-05-15 08:57 UTC, Pubmatic-Dhruv-Sonone commented on endpoints/openrtb2/amp_auction.go
> +
nitpick: Remove blank line

2024-05-15 13:37 UTC, ashishshinde-pubm commented on .gitignore
> +analytics/build/xyz*
done

2024-05-15 13:37 UTC, ashishshinde-pubm commented on analytics/pubmatic/logger.go
> +
done

2024-05-15 13:37 UTC, ashishshinde-pubm commented on endpoints/openrtb2/amp_auction.go
> +
done

2024-05-16 08:08 UTC, Pubmatic-Dhruv-Sonone submitted a review, later dismissed

2024-05-17 08:52 UTC, Pubmatic-Dhruv-Sonone approved these changes

2024-05-17 09:05 UTC, pm-nilesh-chate approved these changes

2024-05-17 09:05 UTC, merged