OTT-1448: Log seatnonbid rejected due to filtered bidders
PubMatic-OpenWrap/prebid-server pull request #699
Opened 2024-01-31 06:05 UTC by Ankit-Pinge

2024-01-31 11:08 UTC, ashishshinde-pubm commented on analytics/pubmatic/logger.go
> +			if nbr != nil {
Check if we can remove below checks ?

1. https://github.com/PubMatic-OpenWrap/prebid-server/pull/699/files#diff-c8e48ea94fc141b428db024b92d575735d4d8bde5da05ff5d80e7629c4239127R303
2. https://github.com/PubMatic-OpenWrap/prebid-server/pull/699/files#diff-c8e48ea94fc141b428db024b92d575735d4d8bde5da05ff5d80e7629c4239127R315

2024-01-31 11:10 UTC, ashishshinde-pubm commented on endpoints/openrtb2/ctv_auction.go
> +	// ao.SeatNonBid = auctionResponse.GetSeatNonBid()
remove comments

2024-01-31 11:11 UTC, ashishshinde-pubm commented on endpoints/openrtb2/ctv_auction.go
> +	// TODO - add seatNonBids in response.Ext
address this TODO , if required take separate task

2024-01-31 11:13 UTC, ashishshinde-pubm commented on exchange/exchange_ow.go
> +			// seatNonBids.addBid(pbsRejBid, int(rejectionReason), pbsRejSeatBid.Seat)
remove comments

2024-01-31 11:14 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/auctionresponsehook.go
> +	var seatNonBids openrtb_ext.NonBidCollection
remove this rctx.ReturnAllBidStatus flag check, framework will take care of it.

2024-01-31 11:15 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/beforevalidationhook.go
> +	if len(filteredBidders) > 0 {
remove this `len(filteredBidders)` check, range takes care of it

2024-01-31 11:15 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/traffic_shapping.go
> +			allPartnersFilteredFlag = false
make sure, we have unit-test for this

2024-01-31 11:18 UTC, ashishshinde-pubm requested changes
Added minor comments

2024-02-05 06:44 UTC, Pubmatic-Dhruv-Sonone commented on openrtb_ext/seat_non_bids.go
> +		StatusCode: bidParams.NonBidReason,
Can you use correct NonBidReason code?

2024-02-05 08:11 UTC, Pubmatic-Dhruv-Sonone commented on openrtb_ext/seat_non_bids.go
> +	var seatNonBid []SeatNonBid
can we write this as seatNonBid := make([]SeatNonBid, len(snb.seatNonBidsMap)?

2024-02-05 08:15 UTC, Pubmatic-Dhruv-Sonone commented on analytics/pubmatic/logger.go
> +			if nbr != nil {
Is this check needed?

2024-02-05 08:19 UTC, Pubmatic-Dhruv-Sonone commented on analytics/pubmatic/record.go
> +	wlog.Device.Platform = dvc.Platform
can wlog.Device be nil?

2024-02-05 08:21 UTC, Pubmatic-Dhruv-Sonone commented on analytics/pubstack/pubstack_module_test.go
> +									Ext:        openrtb_ext.ExtNonBid{Prebid: openrtb_ext.ExtNonBidPrebid{Bid: openrtb_ext.ExtNonBidPrebidBid{}}},
are this changes needed for formatting?

2024-02-05 10:15 UTC, Ankit-Pinge commented on endpoints/openrtb2/ctv_auction.go
> +	// TODO - add seatNonBids in response.Ext
will do as seperate task

2024-02-05 10:15 UTC, Ankit-Pinge commented on exchange/exchange.go
> +				// seatNonBids.addBid(bid, int(openrtb3.LossBidCategoryMapping), string(seatBid.Seat))
removed

2024-02-05 10:15 UTC, Ankit-Pinge commented on exchange/exchange_ow.go
> +			// seatNonBids.addBid(pbsRejBid, int(rejectionReason), pbsRejSeatBid.Seat)
Done

2024-02-05 10:15 UTC, Ankit-Pinge commented on modules/pubmatic/openwrap/auctionresponsehook.go
> +	var seatNonBids openrtb_ext.NonBidCollection
Done

2024-02-05 10:15 UTC, Ankit-Pinge commented on modules/pubmatic/openwrap/beforevalidationhook.go
> +	if len(filteredBidders) > 0 {
Done

2024-02-06 04:06 UTC, pm-viral-vala requested changes

2024-02-06 05:21 UTC, ashishshinde-pubm commented on analytics/pubstack/pubstack_module_test.go
> +									Ext:        openrtb_ext.ExtNonBid{Prebid: openrtb_ext.ExtNonBidPrebid{Bid: openrtb_ext.ExtNonBidPrebidBid{}}},
yes, this is done as per Scott's comment.

2024-02-06 05:29 UTC, ashishshinde-pubm commented on exchange/exchange.go
> +				nonBid := openrtb_ext.NewNonBid(openrtb_ext.NonBidParams{Bid: bid.Bid, NonBidReason: int(ResponseRejectedCategoryMappingInvalid),
Please use `ResponseRejectedCategoryMappingInvalid` as reason code for all bids getting rejected in applyCategoryMapping

2024-02-09 07:39 UTC, pm-viral-vala requested changes

2024-02-09 07:39 UTC, pm-viral-vala commented on exchange/exchange.go
> +							OriginalBidCPM: bid.OriginalBidCPM, OriginalBidCur: bid.OriginalBidCur})
Please indent to make it more readable wherever possible. like below.
```
	nonBid := openrtb_ext.NewNonBid(openrtb_ext.NonBidParams{
		Bid:            bid.Bid,
		NonBidReason:   int(ResponseRejectedCategoryMappingInvalid),
		OriginalBidCPM: bid.OriginalBidCPM,
		OriginalBidCur: bid.OriginalBidCur})
```

2024-02-09 07:39 UTC, pm-viral-vala commented on exchange/exchange.go
> +							// seatNonBids.addBid(bid, int(openrtb3.LossBidCategoryMapping), string(seatBid.Seat))
please remove commented code

2024-02-09 07:39 UTC, pm-viral-vala commented on modules/pubmatic/openwrap/beforevalidationhook.go
> +					NonBidReason: 505,
please use a variable instead of constant 505 even in test cases also, the variable would be more readable and easy to maintain.

2024-02-12 06:29 UTC, Ankit-Pinge commented on exchange/exchange.go
> +	//fmt.Print(seatNonBids.Get())
Done

2024-02-12 06:29 UTC, Ankit-Pinge commented on exchange/exchange.go
> +				nonBid := openrtb_ext.NewNonBid(openrtb_ext.NonBidParams{Bid: bid.Bid, NonBidReason: int(ResponseRejectedCategoryMappingInvalid),
Done

2024-02-12 06:30 UTC, Ankit-Pinge commented on analytics/pubmatic/logger.go
> +	504: {},
Done

2024-02-27 08:05 UTC, Ankit-Pinge commented on openrtb_ext/seat_non_bids.go
> +	var seatNonBid []SeatNonBid
This check will be added in going PR with vanilla prebid

2024-02-27 08:06 UTC, Ankit-Pinge commented on analytics/pubmatic/logger.go
> +			if nbr != nil {
Yes sometimes  bidExt.Nbr can be nil so we need this check

2024-02-27 09:09 UTC, Ankit-Pinge commented on exchange/exchange.go
> +							OriginalBidCPM: bid.OriginalBidCPM, OriginalBidCur: bid.OriginalBidCur})
Done please check ones

2024-02-27 09:22 UTC, Ankit-Pinge commented on analytics/pubmatic/logger.go
> +			if nbr != nil {
sometime nbr = bidExt.Nbr can be nil so need this check

2024-02-27 09:23 UTC, Ankit-Pinge commented on exchange/exchange.go
> +							// seatNonBids.addBid(bid, int(openrtb3.LossBidCategoryMapping), string(seatBid.Seat))
Done

2024-02-27 09:30 UTC, pm-viral-vala approved these changes

2024-02-27 09:48 UTC, Pubmatic-Dhruv-Sonone approved these changes

2024-02-27 09:49 UTC, merged