OTT-1650: Added headers required and query params for VAST Unwrap service
PubMatic-OpenWrap/prebid-server pull request #729
Opened 2024-03-12 11:09 UTC by pm-jaydeep-mohite

# Description

Please add change description or link to ticket, docs, etc.

# Checklist:

- [ ] PR commit list is unique (rebase/pull with the origin branch to keep master clean).
- [ ] JIRA number is added in the PR title and the commit message.
- [ ] Updated the `header-bidding` repo with appropiate commit id.
- [ ] Documented the new changes.

For Prebid upgrade, refer: https://inside.pubmatic.com:8443/confluence/display/Products/Prebid-server+upgrade

2024-03-14 09:19 UTC, Pubmatic-Supriya-Patil submitted a review, later dismissed
LGTM

2024-03-14 10:14 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/entrypointhook.go
> +	} else {
no need to use else block since we are using return

2024-03-14 10:23 UTC, pm-nilesh-chate commented on modules/pubmatic/openwrap/entrypointhook.go
> +}
Both these are helper/utility functions which ideally should be shared in common package but for now we should move them to `utils` package and pass only the request body to it and not hookstage datatype.

2024-03-14 10:28 UTC, pm-nilesh-chate commented on modules/pubmatic/openwrap/entrypointhook.go
> +}
Also, with changes like these vastunwrap as an independent module doesn't fit anymore. Plan to move it to OpenWrap module

Considering modifications like these, the standalone vastunwrap module no longer aligns with the current structure. Could you please plan migrating it to the OpenWrap module.

2024-03-14 12:22 UTC, pm-jaydeep-mohite commented on modules/pubmatic/openwrap/entrypointhook.go
> +	} else {
Done

2024-03-14 12:22 UTC, pm-jaydeep-mohite commented on modules/pubmatic/openwrap/entrypointhook.go
> +}
Moved functions into utils package. 
We have plan to move vast unwrap module into openwrap https://inside.pubmatic.com:9443/jira/browse/OTT-1381

2024-03-15 04:44 UTC, ashishshinde-pubm submitted a review, later dismissed
LGTM

2024-03-18 04:03 UTC, Pubmatic-Supriya-Patil submitted a review, later dismissed
LGTM

2024-03-18 05:24 UTC, pm-viral-vala requested changes

2024-03-18 05:29 UTC, pm-nikhil-vaidya commented on modules/pubmatic/openwrap/util.go
> +	reqIP := string(ipBytes)
we don't need extra assignment, we can do like this
```go
if len(ipBytes) > 0 {
    return string(ipBytes)
}
```

2024-03-18 05:30 UTC, pm-jaydeep-mohite commented on go.mod
> -	github.com/magiconair/properties v1.8.6
These are due to go-common version update

2024-03-18 05:30 UTC, pm-nikhil-vaidya commented on modules/pubmatic/openwrap/util.go
> +	reqUa := string(uaBytes)
Same here as well
```go
if len(uaBytes) > 0 {
     return reqUa
}
```

2024-03-18 05:32 UTC, pm-jaydeep-mohite commented on modules/pubmatic/vastunwrap/unwrap_service.go
> +	glog.Infof("UnWrap Response isStatsEnabled = %v for pubID = %s bidder = %s ImpID = %s BidId = %s  respStatus = %s http code = %d",
This is added to get each VAST un-wrap request status 

Will re-format message

2024-03-18 05:32 UTC, pm-jaydeep-mohite commented on modules/pubmatic/openwrap/util.go
> +	reqIP := string(ipBytes)
Done

2024-03-18 05:32 UTC, pm-jaydeep-mohite commented on modules/pubmatic/openwrap/util.go
> +	reqUa := string(uaBytes)
Done

2024-03-18 05:54 UTC, pm-nikhil-vaidya requested changes
Added some comments

2024-03-18 08:24 UTC, pm-jaydeep-mohite commented on modules/pubmatic/vastunwrap/unwrap_service.go
> +	glog.Infof("UnWrap Response isStatsEnabled = %v for pubID = %s bidder = %s ImpID = %s BidId = %s  respStatus = %s http code = %d",
Done

2024-03-18 11:39 UTC, pm-nikhil-vaidya approved these changes
LGTM

2024-03-18 15:27 UTC, pm-viral-vala approved these changes

2024-03-18 15:28 UTC, merged