cap bid price
PubMatic-OpenWrap/prebid-server pull request #731
Opened 2024-03-16 05:08 UTC by pm-nilesh-chate

# Description

Please add change description or link to ticket, docs, etc.

# Checklist:

- [ ] PR commit list is unique (rebase/pull with the origin branch to keep master clean).
- [ ] JIRA number is added in the PR title and the commit message.
- [ ] Updated the `header-bidding` repo with appropiate commit id.
- [ ] Documented the new changes.

For Prebid upgrade, refer: https://inside.pubmatic.com:8443/confluence/display/Products/Prebid-server+upgrade

2024-03-16 05:40 UTC, ShriprasadM requested changes
@pm-nilesh-chate : Please check my review comments

2024-03-16 05:40 UTC, ShriprasadM commented on exchange/exchange_ow.go
> +				price := rate * bid.Bid.Price
@pm-nilesh-chate : add nil check here for `bid.Bid`

2024-03-16 05:40 UTC, ShriprasadM commented on exchange/exchange.go
>  		recordBids(ctx, e.me, r.PubID, adapterBids)
@pm-nilesh-chate  why we can have new block under this if condition?

2024-03-16 05:57 UTC, pm-nilesh-chate commented on exchange/exchange_ow.go
> +				price := rate * bid.Bid.Price
done

2024-03-16 05:58 UTC, pm-nilesh-chate commented on exchange/exchange.go
>  		recordBids(ctx, e.me, r.PubID, adapterBids)
to keep changes minimum as I've not added UT, etc. Will add improvements, UT, etc once this approach is ok with team

2024-03-16 06:04 UTC, ShriprasadM submitted a review, later dismissed
LGTM

2024-03-16 06:58 UTC, ShriprasadM reviewed
Please check my comments

2024-03-16 06:58 UTC, ShriprasadM commented on exchange/exchange_ow.go
> +					})
@pm-nilesh-chate : Here, I could see `bidder` specific `bids` are not getting grouped in single `entities.PbsOrtbSeatBid` 
For example,

If bidder B returns

B1
B2
B3

And B1 and B2 have price > threshold then rejectedBids will contain 2 seat bid objects.
Whereas in my understanding It should have one single seat object with 2 rejected bids.

2024-03-16 07:02 UTC, pm-nilesh-chate commented on exchange/exchange_ow.go
> +					})
I think `nonBids`'s `addBid()` does it

2024-03-16 07:25 UTC, ShriprasadM submitted a review, later dismissed
LGTM

2024-03-16 16:29 UTC, ShriprasadM commented on exchange/exchange_ow.go
> +					bid.Bid.Price = 0
@pm-nilesh-chate 

1.  If there is no `seatBid.Currency` set  we are directly comparing the price <= threshold
2. Please check if we can get any value  > threshold at its NOT in USD
3. In such case bid will be rejected though it could be valid

2024-03-16 18:13 UTC, ShriprasadM approved these changes
LGTM

2024-03-20 07:18 UTC, pm-nilesh-chate commented on exchange/exchange_ow.go
> +					bid.Bid.Price = 0
discussed and updated pr over call

2024-03-20 07:18 UTC, merged