UOE-10233: Stats for the AMP Multiformat request and response
PubMatic-OpenWrap/prebid-server pull request #734
Opened 2024-03-22 09:39 UTC by AvinashKapre

2024-03-25 07:28 UTC, Pubmatic-Dhruv-Sonone requested changes

2024-03-25 07:28 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/metrics/prometheus/prometheus_sshb.go
> +		"sshb_amp_video_requests",
why do we need prefix sshb ?

2024-03-26 07:48 UTC, AvinashKapre commented on modules/pubmatic/openwrap/metrics/prometheus/prometheus_sshb.go
> +		"sshb_amp_video_requests",
This prefix is used to distinguish between hb and prebid stats. same we have used for other sshb stats.

2024-03-26 12:19 UTC, ashishshinde-pubm submitted a review, later dismissed

2024-03-27 05:24 UTC, pm-nilesh-chate commented on modules/pubmatic/openwrap/metrics/prometheus/prometheus.go
> +	ampVidoeRequests      *prometheus.CounterVec
typo: Video

2024-03-27 06:10 UTC, pm-nilesh-chate approved these changes

2024-03-27 06:11 UTC, pm-saurabh-narkhede approved these changes

2024-03-27 06:12 UTC, Pubmatic-Dhruv-Sonone approved these changes

2024-03-27 06:13 UTC, merged