OTT-1689:: Modified CTV auction to support dynamic and structured adpod
PubMatic-OpenWrap/prebid-server pull request #746
Opened 2024-04-07 20:15 UTC by pm-nikhil-vaidya

2024-04-15 08:21 UTC, Pubmatic-Dhruv-Sonone commented on endpoints/openrtb2/ctv/adpod/dynamic_adpod.go
> +	if nil == err {
nitpick:  err == nil

2024-04-15 08:34 UTC, Pubmatic-Dhruv-Sonone requested changes

2024-04-15 08:34 UTC, Pubmatic-Dhruv-Sonone commented on endpoints/openrtb2/ctv/adpod/structured_adpod.go
> +		sa.ImpBidMap[impId] = bids
`sa.ImpBidMap[impId] = bids`  not needed.  `util.SortBids(bids)` will replaces the slice reference in place.

2024-04-15 08:39 UTC, Pubmatic-Dhruv-Sonone commented on endpoints/openrtb2/ctv/adpod/adpod.go
> +	PodTypeStructured PodType = 0
Can be renamed to Structured, Dynamic, Hybrid ? Type already signifies the purpose of these vars.

2024-04-15 09:20 UTC, pm-nikhil-vaidya commented on endpoints/openrtb2/ctv/adpod/adpod.go
> +	GenerateImpressions()
Combine GenerateImpressions and GetImpressions

2024-04-15 11:59 UTC, Pubmatic-Dhruv-Sonone submitted a review, later dismissed

2024-04-15 12:11 UTC, Pubmatic-Dhruv-Sonone commented on endpoints/openrtb2/ctv_auction.go
> +	ImpPodIdMap               map[string]string
Can we rename this to `ImpToPodID`

2024-04-15 12:15 UTC, Pubmatic-Dhruv-Sonone commented on endpoints/openrtb2/ctv_auction.go
> +func (deps *ctvEndpointDeps) init(req *openrtb2.BidRequest) (errs []error) {
Can  we rename this from `init` to something else,  from current name its difficult to infer the usage.

2024-04-15 12:18 UTC, Pubmatic-Dhruv-Sonone commented on endpoints/openrtb2/ctv_auction.go
> +func (deps *ctvEndpointDeps) prepareAdpodCtx(request *openrtb2.BidRequest) (errs []error) {
Do we need to pass the request here? `deps.request` already has the same value.

2024-04-15 12:20 UTC, Pubmatic-Dhruv-Sonone commented on endpoints/openrtb2/ctv_auction.go
> +func (deps *ctvEndpointDeps) readVideoAdPodExt(imp openrtb2.Imp) (*openrtb_ext.ExtVideoAdPod, error) {
This can be a normal function, no field from deps is  being used here.

2024-04-15 12:56 UTC, Pubmatic-Dhruv-Sonone commented on endpoints/openrtb2/ctv_auction.go
> +				MaxDuration:                 ptrutil.ToPtr(int(imp.Video.MaxDuration)),
Can we just use  `minPodDuration` and `maxPodDuratin` var here?

2024-04-15 13:39 UTC, Pubmatic-Dhruv-Sonone commented on endpoints/openrtb2/ctv/adpod/adpod.go
> +	PubId         string
why is PubId needed in AdpodCtx?

2024-04-15 13:55 UTC, Pubmatic-Dhruv-Sonone commented on endpoints/openrtb2/ctv/adpod/dynamic_adpod.go
> +		da.AddImpressions(imp)
da.AddImpressions(newImpression(da.Imp, da.ImpConfigs[I]))

2024-04-16 09:51 UTC, pm-nikhil-vaidya commented on endpoints/openrtb2/ctv/adpod/adpod.go
> +	PubId         string
It is required for metrics

2024-04-16 09:57 UTC, pm-nikhil-vaidya commented on endpoints/openrtb2/ctv_auction.go
> +				MaxDuration:                 ptrutil.ToPtr(int(imp.Video.MaxDuration)),
If we assign these variable values, it will be confuse in future while understanding code

2024-04-16 10:00 UTC, pm-nikhil-vaidya commented on endpoints/openrtb2/ctv_auction.go
> +			adpodConfigInExt, err := deps.readVideoAdPodExt(imp)
add checks inside the function and convert to switch case

2024-04-16 11:06 UTC, pm-nikhil-vaidya commented on endpoints/openrtb2/ctv_auction.go
>  			if len(bid.ID) == 0 {
Check if we can get Bid ID from req extension

2024-04-16 11:06 UTC, pm-nikhil-vaidya commented on endpoints/openrtb2/ctv_auction.go
> +			originalImpID, _ := util.DecodeImpressionID(bid.ImpID)
check if we can reomove and maintain map

2024-04-16 11:09 UTC, pm-nikhil-vaidya commented on endpoints/openrtb2/ctv/adpod/adpod.go
> +	PerformAuctionAndExclusion()
Rename to HoldAuction

2024-04-16 11:09 UTC, pm-nikhil-vaidya commented on endpoints/openrtb2/ctv/adpod/structured_adpod.go
> +type StructuredAdpod struct {
Make it private and Add constructor method

2024-04-17 17:56 UTC, pm-nikhil-vaidya commented on endpoints/openrtb2/ctv/adpod/dynamic_adpod.go
> +	if nil == err {
Done

2024-04-17 17:56 UTC, pm-nikhil-vaidya commented on endpoints/openrtb2/ctv/adpod/structured_adpod.go
> +		sa.ImpBidMap[impId] = bids
Done

2024-04-17 17:56 UTC, pm-nikhil-vaidya commented on endpoints/openrtb2/ctv/adpod/adpod.go
> +	PodTypeStructured PodType = 0
Done

2024-04-17 17:56 UTC, pm-nikhil-vaidya commented on endpoints/openrtb2/ctv/adpod/adpod.go
> +	GenerateImpressions()
Done

2024-04-17 17:56 UTC, pm-nikhil-vaidya commented on endpoints/openrtb2/ctv_auction.go
> +	if errs := deps.init(request); len(errs) > 0 {
Done

2024-04-17 17:57 UTC, pm-nikhil-vaidya commented on endpoints/openrtb2/ctv_auction.go
> +func (deps *ctvEndpointDeps) prepareAdpodCtx(request *openrtb2.BidRequest) (errs []error) {
Yes its request after executing request wrapper functions

2024-04-17 17:59 UTC, pm-nikhil-vaidya commented on endpoints/openrtb2/ctv/adpod/dynamic_adpod.go
> +		da.AddImpressions(imp)
Done

2024-04-17 18:00 UTC, pm-nikhil-vaidya commented on endpoints/openrtb2/ctv/adpod/adpod.go
> +	PerformAuctionAndExclusion()
Done

2024-04-17 18:00 UTC, pm-nikhil-vaidya commented on endpoints/openrtb2/ctv_auction.go
> +			adpodConfigInExt, err := deps.readVideoAdPodExt(imp)
done

2024-04-17 18:14 UTC, pm-nikhil-vaidya commented on endpoints/openrtb2/ctv_auction.go
>  			if len(bid.ID) == 0 {
Done

2024-04-17 18:19 UTC, pm-nikhil-vaidya commented on endpoints/openrtb2/ctv/adpod/dynamic_adpod.go
> +	return &bid
It was written due to bidId generation, will refactor it when modify dynamic adpod code

2024-04-17 18:20 UTC, pm-nikhil-vaidya commented on endpoints/openrtb2/ctv_auction.go
> +func (deps *ctvEndpointDeps) init(req *openrtb2.BidRequest) (errs []error) {
We are doing multiple things in this, so i guess init is the best appropriate name in my opinion

2024-05-21 10:37 UTC, ashishshinde-pubm submitted a review, later dismissed

2024-05-22 11:53 UTC, pm-viral-vala approved these changes

2024-05-22 12:13 UTC, Pubmatic-Supriya-Patil approved these changes
LGTM

2024-05-22 12:14 UTC, Ankit-Pinge approved these changes

2024-05-22 12:15 UTC, merged