OTT-1697 : Add support to handle /stats and /metrics endpoint on prometheus server
PubMatic-OpenWrap/prebid-server pull request #750
Opened 2024-04-11 06:33 UTC by Ankit-Pinge

2024-04-11 08:08 UTC, pm-viral-vala requested changes

2024-04-11 08:08 UTC, pm-viral-vala commented on server/prometheus.go
> -		}),
If we are not using `newPrometheusServer` function then there shouldn't be any changes in file

2024-04-11 08:08 UTC, pm-viral-vala commented on server/prometheus_ow.go
> +}
if both are returning same values then we can exclude `metrics` endpoint

2024-04-11 08:26 UTC, Ankit-Pinge commented on server/prometheus_ow.go
> +}
Here for /metrics endpoint we are using DefaultGatherer while for /stats endpoint we use prometheus custom gatherer hence we need maintained separate handler for both the endpoint

2024-04-11 08:31 UTC, Ankit-Pinge commented on server/prometheus.go
> -		}),
Sure, you means we need to keep handler as it is and later we can update it in getOpenwrapPrometheusServer() function so that we do not required to updated newPrometheusServer function

2024-04-12 07:42 UTC, pm-jaydeep-mohite submitted a review, later dismissed
LGTM

2024-04-15 07:09 UTC, pm-viral-vala approved these changes

2024-04-16 08:26 UTC, Pubmatic-Supriya-Patil approved these changes

2024-04-16 08:56 UTC, merged