UOE-10388: Support for Applovin Max Response
PubMatic-OpenWrap/prebid-server pull request #759
Opened 2024-04-17 07:41 UTC by AvinashKapre

2024-04-22 05:26 UTC, pm-nilesh-chate requested changes

2024-04-22 05:26 UTC, pm-nilesh-chate commented on endpoints/openrtb2/auction.go
> +	if rCtx != nil && rCtx.IsMaxRequest && response.ID == models.MaxRejected {
Move this condition to function `ApplyMaxAppLovinResponseHeader()`

2024-04-22 05:26 UTC, pm-nilesh-chate commented on modules/pubmatic/openwrap/max.go
> +	respString, err := json.Marshal(bidResponse)
nitpick: marshal returns byte so would suggest to rename `respString` to either `respBytes` or simply `resp`.

2024-04-22 05:26 UTC, pm-nilesh-chate commented on modules/pubmatic/openwrap/max.go
> +	if bidResponse != nil && len(bidResponse.SeatBid) > 0 && len(bidResponse.SeatBid[0].Bid) > 0 {
Above Marshal can be avoided with moving these check at start

2024-04-22 05:26 UTC, pm-nilesh-chate commented on modules/pubmatic/openwrap/targeting.go
> +			} else if !rctx.SendAllBids && !rctx.IsMaxRequest {
can we have `IsMaxRequestDebugEnabled()`

2024-04-22 05:26 UTC, pm-nilesh-chate commented on modules/pubmatic/openwrap/auctionresponsehook_test.go
> +					SeatBid: []openrtb2.SeatBid{
Considering this as end-to-end UT, assert all the fields in response (i.e. fields returned by adapter but reset as part of maxapplovin resp) and include adm as well to assert injectTracker does not run?.

2024-04-22 05:26 UTC, pm-saurabh-narkhede commented on endpoints/openrtb2/auction_ow.go
> +		upadteResponseExtForMax(ao, rCtx, bidResponse)
nitpick: should be updateResponseExtForMax

2024-04-22 06:09 UTC, AvinashKapre commented on modules/pubmatic/openwrap/max.go
> +	return bidResponse
can we keep debug in orignal response Ext?

2024-04-23 12:06 UTC, pm-isha-bharti approved these changes

2024-04-24 06:32 UTC, pm-nilesh-chate commented on modules/pubmatic/openwrap/applovinmax.go
> +}
```
func updateMaxAppLovinResponse(rctx models.RequestCtx, bidResponse *openrtb2.BidResponse) models.MaxAppLovin {
	maxAppLovin := models.MaxAppLovin{Reject: false}

	if bidResponse.NBR != nil {
		if !rctx.Debug {
			maxAppLovin.Reject = true
		}
	} else if len(bidResponse.SeatBid) == 0 || len(bidResponse.SeatBid[0].Bid) == 0 {
		maxAppLovin.Reject = true
	}
	return maxAppLovin
}
```

2024-04-24 06:49 UTC, pm-nilesh-chate commented on modules/pubmatic/openwrap/applovinmax.go
> +	}
add comment that this condition will be true only when debug is enabled

2024-04-24 06:52 UTC, pm-nilesh-chate commented on modules/pubmatic/openwrap/applovinmax_test.go
> +	for _, tt := range tests {
add case with "bidresponse w/o NBR and debug is disabled and seatbid.bid is valid"

2024-04-24 06:56 UTC, pm-nilesh-chate commented on modules/pubmatic/openwrap/applovinmax_test.go
> +			name: "failed to marshal bidresponse",
This does not fail at unmarshal

2024-04-24 06:59 UTC, pm-nilesh-chate commented on modules/pubmatic/openwrap/applovinmax_test.go
> +					},
Should seat be required field?

2024-04-24 07:34 UTC, pm-nilesh-chate commented on modules/pubmatic/openwrap/targeting.go
> +			} else if !rctx.SendAllBids && isMaxRequestDebugEnabled(rctx) {
This should be OR

2024-04-24 07:34 UTC, pm-nilesh-chate commented on modules/pubmatic/openwrap/util.go
> +func isMaxRequestDebugEnabled(rctx models.RequestCtx) bool {
add UT

2024-04-24 07:35 UTC, pm-nilesh-chate commented on modules/pubmatic/openwrap/models/constants.go
> +	MaxRejected      = "max_rejected"
this is not needed

2024-04-24 07:36 UTC, pm-nilesh-chate commented on modules/pubmatic/openwrap/applovinmax.go
> +		},
Seat should be set

2024-04-24 07:58 UTC, AvinashKapre commented on modules/pubmatic/openwrap/applovinmax_test.go
> +					},
Need to check with OW SDK.

2024-04-24 07:59 UTC, AvinashKapre commented on modules/pubmatic/openwrap/util.go
> +func isMaxRequestDebugEnabled(rctx models.RequestCtx) bool {
Removed function

2024-04-24 08:00 UTC, AvinashKapre commented on modules/pubmatic/openwrap/applovinmax.go
> +		},
Need to check with OW SDK

2024-04-24 08:16 UTC, pm-saurabh-narkhede approved these changes

2024-04-24 08:38 UTC, pm-nilesh-chate approved these changes

2024-04-24 08:38 UTC, merged