OTT-1730: Push PartnerConfig in cache after reading slotMappings and adUnitConfig
PubMatic-OpenWrap/prebid-server pull request #761
Opened 2024-04-18 11:43 UTC by pm-jaydeep-mohite

# Description

Please add change description or link to ticket, docs, etc.

# Checklist:

- [ ] PR commit list is unique (rebase/pull with the origin branch to keep master clean).
- [ ] JIRA number is added in the PR title and the commit message.
- [ ] Updated the `header-bidding` repo with appropiate commit id.
- [ ] Documented the new changes.

For Prebid upgrade, refer: https://inside.pubmatic.com:8443/confluence/display/Products/Prebid-server+upgrade

2024-04-18 11:48 UTC, pm-nilesh-chate commented on modules/pubmatic/openwrap/cache/gocache/partner_config.go
> +	c.cache.Set(cacheKey, partnerConfigMap, getSeconds(c.cfg.CacheDefaultExpiry))
Please add UT for GetPartnerConfigMap() to cover all the cases described

2024-04-18 13:14 UTC, pm-jaydeep-mohite commented on modules/pubmatic/openwrap/cache/gocache/partner_config.go
> +	c.cache.Set(cacheKey, partnerConfigMap, getSeconds(c.cfg.CacheDefaultExpiry))
Updated code and UT

2024-04-19 05:37 UTC, pm-nilesh-chate requested changes

2024-04-19 05:37 UTC, pm-nilesh-chate commented on modules/pubmatic/openwrap/cache/gocache/partner_config.go
> +	if errWrapperSlotMapping == nil && errAdunitConfig == nil {
This check removes the current fallback mechanism, which suspends database calls for an hour if the database entry is not found or encounters network issues. To maintain the existing behavior, we should add a dummy entry in the event of an error.

2024-04-19 05:37 UTC, pm-nilesh-chate commented on modules/pubmatic/openwrap/cache/gocache/partner_config.go
> +	if errWrapperSlotMapping = c.populateCacheWithWrapperSlotMappings(pubID, partnerConfigMap, profileID, displayVersion); errWrapperSlotMapping != nil {
nitpick: if with initialization is removed so you can move the function call out of if condition
```
errWrapperSlotMapping = c.populateCacheWithWrapperSlotMappings(pubID, partnerConfigMap, profileID, displayVersion)
if  errWrapperSlotMapping != nil {
```

2024-04-19 05:37 UTC, pm-nilesh-chate commented on modules/pubmatic/openwrap/cache/gocache/partner_config.go
> +	if errAdunitConfig = c.populateCacheWithAdunitConfig(pubID, profileID, displayVersion); errAdunitConfig != nil {
nitpick: if with initialization is removed so you can move the function call out of if condition
```
errAdunitConfig = c.populateCacheWithAdunitConfig(pubID, profileID, displayVersion)
if errAdunitConfig != nil {
```

2024-04-19 05:37 UTC, pm-nilesh-chate commented on modules/pubmatic/openwrap/cache/gocache/partner_config_test.go
> +			want:    nil,
we should add cache assertion to validate the end to end check. i.e cache content in case of error, non-error, etc.

2024-04-19 06:21 UTC, Pubmatic-Dhruv-Sonone requested changes

2024-04-19 06:21 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/cache/gocache/partner_config.go
> +	if errWrapperSlotMapping == nil && errAdunitConfig == nil {
Move the `errWrapperSlotMapping` check above. No need to call `c.populateCacheWithAdunitConfig` if `errWrapperSlotMapping` is not nil.

2024-04-19 06:31 UTC, pm-jaydeep-mohite commented on modules/pubmatic/openwrap/cache/gocache/partner_config.go
> +	if errAdunitConfig = c.populateCacheWithAdunitConfig(pubID, profileID, displayVersion); errAdunitConfig != nil {
Done

2024-04-19 06:32 UTC, pm-jaydeep-mohite commented on modules/pubmatic/openwrap/cache/gocache/partner_config.go
> +	if errWrapperSlotMapping == nil && errAdunitConfig == nil {
We would try get in second request immediately and would not wait for 1 hour

2024-04-19 06:38 UTC, pm-viral-vala requested changes

2024-04-19 06:38 UTC, pm-viral-vala commented on modules/pubmatic/openwrap/cache/gocache/partner_config.go
> +		c.cache.Set(cacheKey, partnerConfigMap, getSeconds(c.cfg.CacheDefaultExpiry))
let's make sure the following scenarios are tested well
PCM: partnerConfigMap
AC: AdunitConfig
SM: SlotMapping

**nothing set in cache**
1. PCM = db/network error OR AC = db/network error OR SM = db/network error (4 test cases of 1 valid, 3 invalid)

**cache will be populated**
1. PCM = valid AND AC = valid AND SM = valid
2. PCM = empty (PCM is set to empty, IGNORE AC and SM)
3. AC = empty OR unmarshal error (AC will be set EMPTY in cache)
4. SM = empty OR other than DB error (SM will be set EMPTY in cache)

PLEASE ADD DEV UNIT Cases for the above scenarios.

PLEASE VERIFY DROP with PRODUCTION AdUnitConfigs, because there are so many combinations in production.

2024-04-19 06:42 UTC, pm-jaydeep-mohite commented on modules/pubmatic/openwrap/cache/gocache/partner_config_test.go
> +			want:    nil,
Added

2024-04-19 06:43 UTC, pm-jaydeep-mohite commented on modules/pubmatic/openwrap/cache/gocache/partner_config.go
> +	if errWrapperSlotMapping = c.populateCacheWithWrapperSlotMappings(pubID, partnerConfigMap, profileID, displayVersion); errWrapperSlotMapping != nil {
Done

2024-04-19 06:51 UTC, pm-jaydeep-mohite commented on modules/pubmatic/openwrap/cache/gocache/partner_config.go
> +	if errWrapperSlotMapping == nil && errAdunitConfig == nil {
Done

2024-04-19 07:26 UTC, pm-jaydeep-mohite commented on modules/pubmatic/openwrap/cache/gocache/partner_config.go
> +		c.cache.Set(cacheKey, partnerConfigMap, getSeconds(c.cfg.CacheDefaultExpiry))
cache will be populated

1. PCM = valid AND AC = valid AND SM = valid
2. AC = empty  (AC will be set EMPTY in cache)
3. SM = empty   (SM will be set EMPTY in cache)

Cache won't have PCM when 
1. PCM = empty this mandatory condition in OpenWrap to process any request 
2. AC = error OR SM = error, as its invalid parameters set by publisher which needs to be corrected by publisher

2024-04-22 04:52 UTC, pm-nilesh-chate reviewed
minor nitpick suggestions

2024-04-22 04:52 UTC, pm-nilesh-chate commented on modules/pubmatic/openwrap/cache/gocache/partner_config.go
> +
nitpick: remove this new line

2024-04-22 04:52 UTC, pm-nilesh-chate commented on modules/pubmatic/openwrap/cache/gocache/partner_config.go
> +	errWrapperSlotMapping := c.populateCacheWithWrapperSlotMappings(pubID, partnerConfigMap, profileID, displayVersion)
nitpick: rename errWrapperSlotMapping it to err

2024-04-22 04:52 UTC, pm-nilesh-chate commented on modules/pubmatic/openwrap/cache/gocache/partner_config.go
> +	errAdunitConfig := c.populateCacheWithAdunitConfig(pubID, profileID, displayVersion)
nitpick: rename errAdunitConfig it to err

2024-04-23 08:40 UTC, pm-jaydeep-mohite commented on modules/pubmatic/openwrap/cache/gocache/partner_config.go
> +
Done

2024-04-23 08:40 UTC, pm-jaydeep-mohite commented on modules/pubmatic/openwrap/cache/gocache/partner_config.go
> +	errWrapperSlotMapping := c.populateCacheWithWrapperSlotMappings(pubID, partnerConfigMap, profileID, displayVersion)
Done

2024-04-23 08:40 UTC, pm-jaydeep-mohite commented on modules/pubmatic/openwrap/cache/gocache/partner_config.go
> +	errAdunitConfig := c.populateCacheWithAdunitConfig(pubID, profileID, displayVersion)
Done

2024-04-24 04:16 UTC, Pubmatic-Dhruv-Sonone requested changes

2024-04-24 04:16 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/models/errorstypes.go
> +type DBError struct {
Should this be a generic Error and not specific to DB?

2024-04-24 04:16 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/cache/gocache/partner_config.go
> +	if models.GetErrorCode(err) == models.DBErrorCode {
Should we check the underlying error type instead of checking the code?
[Refer- errors.As](https://pkg.go.dev/errors#As. )

2024-04-24 08:44 UTC, pm-jaydeep-mohite commented on modules/pubmatic/openwrap/models/errorstypes.go
> +type DBError struct {
Updated Error Struct

2024-04-24 08:44 UTC, pm-jaydeep-mohite commented on modules/pubmatic/openwrap/cache/gocache/partner_config.go
> +	if models.GetErrorCode(err) == models.DBErrorCode {
Updated Error Struct

2024-04-24 10:22 UTC, pm-viral-vala submitted a review, later dismissed

2024-04-24 13:49 UTC, Pubmatic-Dhruv-Sonone submitted a review, later dismissed

2024-04-24 14:14 UTC, pm-jaydeep-mohite commented
> minor nitpick suggestions

Done

2024-04-24 14:24 UTC, pm-nilesh-chate requested changes

2024-04-24 14:24 UTC, pm-nilesh-chate commented on modules/pubmatic/openwrap/cache/gocache/partner_config.go
> +		c.cache.Set(cacheKey, partnerConfigMap, getSeconds(c.cfg.CacheDefaultExpiry)) // Setting empty partner Config map
Remove this dummy entry. This will restrict retry for an hour (CacheDefaultExpiry). Publishers will have issues while testing setups, etc. Below two  queries can act as retry fallback.

2024-04-24 14:24 UTC, pm-nilesh-chate commented on modules/pubmatic/openwrap/cache/gocache/partner_config.go
> +		}
Remove this check. We did an activity in prod. to clean the adunitconfig files. We don't want to encourage the publishers to upload back configs. Also, this defeats the original purpose of this PR as this change allows requests to by pass adunit config.

2024-04-25 06:29 UTC, pm-jaydeep-mohite commented on modules/pubmatic/openwrap/cache/gocache/partner_config.go
> +		c.cache.Set(cacheKey, partnerConfigMap, getSeconds(c.cfg.CacheDefaultExpiry)) // Setting empty partner Config map
Done

2024-04-25 06:29 UTC, pm-jaydeep-mohite commented on modules/pubmatic/openwrap/cache/gocache/partner_config.go
> +		}
Done

2024-04-25 08:25 UTC, pm-nilesh-chate approved these changes

2024-04-25 08:29 UTC, pm-viral-vala approved these changes

2024-04-25 08:30 UTC, merged