UOE:10435-1 Migrate Wakanda to prebid
PubMatic-OpenWrap/prebid-server pull request #783
Opened 2024-05-03 06:58 UTC by pm-priyanka-bagade

2024-05-07 05:39 UTC, pm-nilesh-chate commented on analytics/pubmatic/pubmatic.go
> +	url, headers, wlog := GetLogAuctionObjectAsURL(*ao, rCtx, false, false)
no need of wlog, use url

2024-05-07 05:39 UTC, pm-nilesh-chate commented on analytics/pubmatic/pubmatic.go
> +		rCtx.WakandaDebug.DebugData.Logger, _ = json.Marshal(wlog)
use url instead of wlog

2024-05-07 05:39 UTC, pm-nilesh-chate commented on analytics/pubmatic/pubmatic.go
> +		defer rCtx.WakandaDebug.WriteLogToFiles()
remove defer

2024-05-07 05:39 UTC, pm-nilesh-chate commented on modules/pubmatic/openwrap/entrypointhook.go
> +	pubIdStr, _, _, errs := getAccountIdFromRawRequest(false, nil, payload.Body)
remove `getPubID` from before validation hook

2024-05-07 05:39 UTC, pm-nilesh-chate commented on modules/pubmatic/openwrap/wakanda/mock/mock.goclear
delete this fie

2024-05-07 12:00 UTC, pm-priyanka-bagade commented on analytics/pubmatic/pubmatic.go
> +		defer rCtx.WakandaDebug.WriteLogToFiles()
removed

2024-05-07 17:51 UTC, pm-priyanka-bagade commented on analytics/pubmatic/pubmatic.go
> +	url, headers, wlog := GetLogAuctionObjectAsURL(*ao, rCtx, false, false)
url is string and wlog is struct 
1 - when we json.marshal() string then it will give JSON representation of the string
example - "Hello, World!" -> marhsal  -> "\"Hello, World!\""
2 - when we json.marshal() struct then it will JSON representation of the struct.
example - person := Person{
		Name:  "Alice",
		Age:   30,
		Email: "alice@example.com",
	} 
         -> marshal -> {"name":"Alice","age":30,"email":"alice@example.com"}
         
that's why we can't use url 
we need to use wlog

2024-05-07 18:02 UTC, pm-priyanka-bagade commented on modules/pubmatic/openwrap/wakanda/mock/mock.goclear
done

2024-05-07 18:03 UTC, pm-priyanka-bagade commented on modules/pubmatic/openwrap/entrypointhook.go
> +	pubIdStr, _, _, errs := getAccountIdFromRawRequest(false, nil, payload.Body)
done removed

2024-05-10 05:12 UTC, pm-nilesh-chate commented on analytics/pubmatic/pubmatic.go
> +	url, headers, wlog := GetLogAuctionObjectAsURL(*ao, rCtx, false, false)
Parse url and use the value of query param `json`. Check `PrepareLoggerURL()`
Also, move wakandadebug code to helper function to keep the code clean

2024-05-21 10:41 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/wakanda/rulesMap.go
> +	if nil != aWakandaRule {
rewrite this like `aWakandaRule != nil`

2024-05-21 10:52 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/wakanda/rulesMap.go
> +	c := time.Tick(time.Duration(cleanupFrequencyInMin) * time.Minute)
looks like, you are multying cleanupFrequencyInMin 2 times by time.Minute.
one time in `clean` and one time in `getNewRulesMap`. 
correct this and multiply only once

2024-05-21 11:52 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/wakanda/wakandaDebug_test.go
> +// func init() {
remove this

2024-05-21 11:53 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/wakanda/wakanda_test.go
> +	// wakndaGetTester(t, handler, "/wakanda", `{success: "false", statusMsg: "No key was generated for the request.", host: ""}`)
remove this if we dont need this.

2024-05-21 11:55 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/wakanda/mock/mock.go
> +// Source: header-bidding/wakanda (interfaces: Commands)
try to generate this file using `mockgen`

2024-05-21 11:57 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/wakanda/mock/mock.go
> +// Source: header-bidding/wakanda (interfaces: Commands)
also update Makefile and add entries for mock-wakanda , refer below code of mock-cache 
```
mockgencache:
	mkdir -p modules/pubmatic/openwrap/cache/mock
	mockgen github.com/PubMatic-OpenWrap/prebid-server/v2/modules/pubmatic/openwrap/cache Cache > modules/pubmatic/openwrap/cache/mock/mock.go
```

2024-05-21 11:59 UTC, ashishshinde-pubm requested changes
Please fix comments

2024-05-22 15:36 UTC, AvinashKapre commented on modules/pubmatic/openwrap/entrypointhook.go
> +	pubIdStr, _, _, errs := getAccountIdFromRawRequest(false, nil, payload.Body)
How do we get pubID for get request since body will be nil?

2024-05-23 08:48 UTC, AvinashKapre commented on modules/pubmatic/openwrap/entrypointhook_test.go
>  						ProfileID:                 12929,
can we have the test case for the checking the raw request body is updated in wakand if enabled?

2024-05-23 08:48 UTC, AvinashKapre commented on modules/pubmatic/openwrap/openwrap.go
> +
NitPick: Empty Line

2024-05-23 09:30 UTC, AvinashKapre commented on modules/pubmatic/openwrap/util.go
> +func getAccountIdFromRawRequest(hasStoredRequest bool, storedRequest json.RawMessage, originalRequest []byte) (string, bool, bool, []error) {
Add test cases for this function

2024-05-23 09:30 UTC, AvinashKapre commented on modules/pubmatic/openwrap/util.go
> +func searchAccountId(request []byte) (string, bool, bool, error) {
Please add test case

2024-05-23 09:31 UTC, AvinashKapre commented on modules/pubmatic/openwrap/util.go
> +func getStringValueFromRequest(request []byte, key []string) (string, bool, error) {
Please add test cases

2024-05-23 09:33 UTC, AvinashKapre commented on modules/pubmatic/openwrap/server.go
> +var startServer = func(srvInterface string, hbMux *http.ServeMux) error {
Do we need this as a variable func?

2024-05-23 09:34 UTC, AvinashKapre commented on modules/pubmatic/openwrap/server.go
> +		logger.Fatal("main.main:unable to start http server: %s", err.Error())
Can we add more descriptive log that which server is unable to start

2024-05-23 09:40 UTC, AvinashKapre commented on analytics/pubmatic/helper.go
> +func setWakandaWinningBidFlag(debug *wakanda.Debug, response *openrtb2.BidResponse) {
NitPick: rename debug -> wakandaDebug

2024-05-23 09:42 UTC, AvinashKapre commented on analytics/pubmatic/helper.go
> +			jsonParam := parseURL.Query().Get("json")
Please use constant for ```json```

2024-05-23 09:44 UTC, AvinashKapre commented on analytics/pubmatic/helper.go
> +func setWakandaObject(rCtx *models.RequestCtx, ao *analytics.AuctionObject, loggerURL string) {
Please add test cases

2024-05-23 09:44 UTC, AvinashKapre commented on analytics/pubmatic/helper.go
> +func setWakandaWinningBidFlag(debug *wakanda.Debug, response *openrtb2.BidResponse) {
Please add test cases

2024-05-23 09:48 UTC, pm-priyanka-bagade commented on modules/pubmatic/openwrap/openwrap.go
> +
formatted according to go fmt

2024-05-23 09:53 UTC, pm-saurabh-narkhede commented on analytics/pubmatic/helper.go
> +	if debug != nil && debug.Enabled && response != nil {
Do we need this `debug != nil && debug.Enabled` checks as they are already covered in parent functions?

2024-05-23 10:07 UTC, pm-priyanka-bagade commented on modules/pubmatic/openwrap/util.go
> +func searchAccountId(request []byte) (string, bool, bool, error) {
done

2024-05-23 10:08 UTC, AvinashKapre commented on modules/pubmatic/openwrap/server.go
> +	go startServer(srvInterface, hbMux)
Are we starting the service even owserver fail to start

2024-05-23 10:11 UTC, AvinashKapre commented on analytics/pubmatic/helper.go
> +		parseURL, _ := url.Parse(loggerURL)
Hanlde parsing error

2024-05-23 10:12 UTC, AvinashKapre commented on analytics/pubmatic/helper.go
> +		bytes, _ := json.Marshal(ao.Response)
Handling marshal error

2024-05-23 10:14 UTC, AvinashKapre commented on go.mod
> +	git.pubmatic.com/PubMatic/go-common v0.0.0-20240313090142-97ff3d63b7c3
please push the go.sum as well

2024-05-23 10:24 UTC, AvinashKapre commented on modules/pubmatic/openwrap/server.go
> +		return err
No need to return error

2024-05-23 10:34 UTC, pm-priyanka-bagade commented on modules/pubmatic/openwrap/server.go
> +		return err
done

2024-05-23 10:38 UTC, pm-priyanka-bagade commented on go.mod
> +	git.pubmatic.com/PubMatic/go-common v0.0.0-20240313090142-97ff3d63b7c3
okay sure

2024-05-23 10:51 UTC, pm-priyanka-bagade commented on analytics/pubmatic/helper.go
> +		bytes, _ := json.Marshal(ao.Response)
Handled error

2024-05-23 11:01 UTC, pm-priyanka-bagade commented on analytics/pubmatic/helper.go
> +		parseURL, _ := url.Parse(loggerURL)
handled parsing error

2024-05-23 14:11 UTC, Pubmatic-Dhruv-Sonone requested changes

2024-05-24 06:27 UTC, pm-priyanka-bagade commented on modules/pubmatic/openwrap/util.go
> +func getAccountIdFromRawRequest(hasStoredRequest bool, storedRequest json.RawMessage, originalRequest []byte) (string, bool, bool, []error) {
okay

2024-05-24 06:30 UTC, pm-priyanka-bagade commented on modules/pubmatic/openwrap/util.go
> +	return serverName
done

2024-05-24 06:32 UTC, pm-priyanka-bagade commented on modules/pubmatic/openwrap/util.go
> +var accountIdSearchPath = [...]struct {
done moved

2024-05-24 06:34 UTC, pm-priyanka-bagade commented on modules/pubmatic/openwrap/util.go
> +func GetPodName() string {
yes we can make this private 
done

2024-05-24 06:37 UTC, pm-priyanka-bagade commented on modules/pubmatic/openwrap/util.go
> +	}
we can but anyway we need different return statements 
so it is one and the same

2024-05-24 06:42 UTC, pm-priyanka-bagade commented on analytics/pubmatic/helper.go
> +	if debug != nil && debug.Enabled && response != nil {
yes right removed

2024-05-24 06:57 UTC, Pubmatic-Dhruv-Sonone requested changes

2024-05-24 06:57 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/wakanda/wakandaDebug_test.go
> +}
use assert lib instead of `t.Errorf`

2024-05-24 06:57 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/wakanda/wakandaDebugData_test.go
> +func Test_response_setResponseWriter(t *testing.T) {
Nitpick:  TestResponseSetResponseWriter

2024-05-24 06:57 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/wakanda/constant.go
> +package wakanda
Can we move this to common constant file?

2024-05-24 06:57 UTC, Pubmatic-Dhruv-Sonone commented on analytics/pubmatic/helper.go
> +		bytes, _ := json.Marshal(ao.Response)
Add error check here

2024-05-24 06:57 UTC, Pubmatic-Dhruv-Sonone commented on analytics/pubmatic/helper.go
> +		setWakandaWinningBidFlag(&rCtx.WakandaDebug, ao.Response)
Should `setWakandaWinningBidFlag` be a receiver function on `WakandaDebug` ?

2024-05-24 06:57 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/server.go
> +	wakanda.InitWakanda(cfg.Wakanda)
Rename to `wakanda.Init`

2024-05-24 06:57 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/wakanda/wakanda.go
> +func InitWakanda(config Wakanda) {
Rename to `Init`, its already inside wakanda package.

2024-05-24 06:57 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/server.go
> +var startServer = func(srvInterface string, hbMux *http.ServeMux) error {
No need to return error from here, logger.Fatal calls os.Exit(2) internal

2024-05-24 06:57 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/wakanda/push_data_handler_test.go
> +func Test_send(t *testing.T) {
Nitpick: `TestSend`

2024-05-24 06:57 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/wakanda/rulesMap.go
> +	DebugLevel int
Can we create a type constant  for DebugLevel?

2024-05-24 06:57 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/wakanda/rulesMap_test.go
> +func Test_rulesMap_cleanRules(t *testing.T) {
Nitpick: `TestRulesMapCleanRules`

2024-05-24 06:57 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/wakanda/rulesMap_test.go
> +func Test_rulesMap_Incr(t *testing.T) {
Nitpick: TestRulesMapIncr

2024-05-24 06:57 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/wakanda/rulesMap.go
> +type rulesMap struct {
Can we rename `rulesMap` to `rulesConfig` or something appropriate?

2024-05-24 06:57 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/wakanda/rulesMap_test.go
> +}
use  assertion library

2024-05-24 06:57 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/wakanda/rulesMap_test.go
> +// }
Nitpick: Remove commented code.

2024-05-24 06:57 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/wakanda/wakandaDebug_test.go
> +				FolderPaths: []string{`pub_1`, `pub_1_prof_1`},
Can we create a temp dir and write to a temporary file for testing?

2024-05-24 07:11 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/util.go
> +func getAccountIdFromRawRequest(hasStoredRequest bool, storedRequest json.RawMessage, originalRequest []byte) (string, bool, bool, []error) {
This is a repetitive code, it's already part of `auction.go` in` package openrtb2`. 
Can we move it to some common place?

In auction.go only call to `getAccountIdFromRawRequest` will  change.

2024-05-24 08:36 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/wakanda/wakandaDebugData_test.go
> +			_, err := json.Marshal(got)
Why is checking json.Marshal being tested here? It should be tested  as  part of the function that call NewLogRecord

2024-05-24 12:02 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/wakanda/wakandaDebug_test.go
> +			wD.WriteLogToFiles()
Can we verify is data being written to the file?

2024-05-27 06:14 UTC, pm-priyanka-bagade commented on analytics/pubmatic/helper.go
> +			jsonParam := parseURL.Query().Get("json")
done

2024-05-27 06:15 UTC, pm-priyanka-bagade commented on modules/pubmatic/openwrap/wakanda/wakandaDebug_test.go
> +func TestDebug_WriteLogToFiles(t *testing.T) {
done

2024-05-27 06:52 UTC, pm-priyanka-bagade commented on modules/pubmatic/openwrap/wakanda/wakandaDebug_test.go
> +}
done

2024-05-27 07:02 UTC, pm-priyanka-bagade commented on modules/pubmatic/openwrap/wakanda/constant.go
> +package wakanda
NO it will give cyclic import because we are using common constant package

2024-05-27 07:02 UTC, pm-priyanka-bagade commented on modules/pubmatic/openwrap/wakanda/rulesMap_test.go
> +func Test_rulesMap_Incr(t *testing.T) {
Done

2024-05-27 07:10 UTC, pm-priyanka-bagade commented on modules/pubmatic/openwrap/wakanda/rulesMap.go
> +type rulesMap struct {
I think rulesMap is correct name as we are storing like that

2024-05-27 07:17 UTC, pm-priyanka-bagade commented on modules/pubmatic/openwrap/wakanda/rulesMap_test.go
> +}
Done

2024-05-27 07:18 UTC, pm-priyanka-bagade commented on modules/pubmatic/openwrap/util.go
> +func getAccountIdFromRawRequest(hasStoredRequest bool, storedRequest json.RawMessage, originalRequest []byte) (string, bool, bool, []error) {
That will give cyclic import we can't do that

2024-05-27 09:09 UTC, pm-priyanka-bagade commented on modules/pubmatic/openwrap/wakanda/wakandaDebug_test.go
> +			wD.WriteLogToFiles()
yes we can 
but in the code we are removing that file

2024-05-27 09:10 UTC, pm-priyanka-bagade commented on modules/pubmatic/openwrap/wakanda/wakandaDebug_test.go
> +				FolderPaths: []string{`pub_1`, `pub_1_prof_1`},
yes we can do it 
but anyway we are removing that file every time 
we are not storing that file

2024-05-27 09:11 UTC, pm-priyanka-bagade commented on modules/pubmatic/openwrap/wakanda/rulesMap_test.go
> +// }
done

2024-05-27 09:16 UTC, pm-priyanka-bagade commented on modules/pubmatic/openwrap/server.go
> +		logger.Fatal("main.main:unable to start http server: %s", err.Error())
done

2024-05-27 09:20 UTC, Pubmatic-Dhruv-Sonone requested changes

2024-05-27 09:29 UTC, pm-priyanka-bagade commented on modules/pubmatic/openwrap/server.go
> +var startServer = func(srvInterface string, hbMux *http.ServeMux) error {
to write the test case we need this as a variable func

2024-05-27 09:38 UTC, pm-priyanka-bagade commented on modules/pubmatic/openwrap/wakanda/wakandaDebugData_test.go
> +func Test_request_set(t *testing.T) {
done

2024-05-27 09:38 UTC, pm-priyanka-bagade commented on modules/pubmatic/openwrap/wakanda/wakandaDebugData_test.go
> +func Test_response_setResponseRecorder(t *testing.T) {
done

2024-05-27 09:39 UTC, pm-priyanka-bagade commented on modules/pubmatic/openwrap/wakanda/wakandaDebugData.go
> +		if r.Headers.Get(ContentType) == ContentTypeApplicationJSON {
we can't move to common constant file it will give cyclic import error

2024-05-27 09:40 UTC, pm-priyanka-bagade commented on modules/pubmatic/openwrap/wakanda/wakandaDebugData.go
> +	// PartnerMapping
done

2024-05-27 09:42 UTC, pm-priyanka-bagade commented on modules/pubmatic/openwrap/wakanda/wakandaDebugData.go
> +	if nil != resp {
done

2024-05-27 09:55 UTC, pm-priyanka-bagade commented on modules/pubmatic/openwrap/wakanda/push_data_handler.go
> +func send(destFileName, pubProfDir string, data []byte, cfg SFTP) (bool, error) {
yes right we don't need bool 
removed it

2024-05-27 09:57 UTC, pm-priyanka-bagade commented on modules/pubmatic/openwrap/wakanda/wakandaDebugData.go
> +	if nil != resp {
done

2024-05-27 16:05 UTC, Pubmatic-Dhruv-Sonone requested changes

2024-05-27 16:05 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/wakanda/push_data_handler.go
> +	srcFile.Write(data)
Do we need to close the file, before it's sent over SFTP?

2024-05-28 09:27 UTC, pm-priyanka-bagade commented on modules/pubmatic/openwrap/util.go
> +func getAccountIdFromRawRequest(hasStoredRequest bool, storedRequest json.RawMessage, originalRequest []byte) (string, bool, bool, []error) {
Done

2024-05-28 09:27 UTC, pm-priyanka-bagade commented on modules/pubmatic/openwrap/util.go
> +func getStringValueFromRequest(request []byte, key []string) (string, bool, error) {
Done

2024-05-28 10:59 UTC, pm-priyanka-bagade commented on analytics/pubmatic/helper.go
> +func setWakandaWinningBidFlag(debug *wakanda.Debug, response *openrtb2.BidResponse) {
Done

2024-05-29 06:59 UTC, pm-priyanka-bagade commented on analytics/pubmatic/helper.go
> +func setWakandaObject(rCtx *models.RequestCtx, ao *analytics.AuctionObject, loggerURL string) {
done

2024-05-29 07:00 UTC, pm-priyanka-bagade commented on analytics/pubmatic/helper.go
> +const ParseUrlFormat = "json"
done

2024-05-29 08:43 UTC, pm-priyanka-bagade commented on modules/pubmatic/openwrap/wakanda/push_data_handler.go
> +	srcFile.Write(data)
yes we need to close the file 
we are doing it line defer os.Remove(srcFile.Name())

2024-05-29 16:55 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/wakanda/push_data_handler.go
> +	srcFile.Write(data)
@pm-priyanka-bagade 
You should explicitly close the file by calling `Close()` before its sent over sftp or before removing the file.
 
In Go, if a file is open for reading and it's deleted before closing, the OS file descriptor remains active until the file is closed in your program. This is because when a file is opened, the operating system creates a file descriptor and any operations you perform on the file in your program are actually done through this file descriptor. 

Even if the file is deleted from the file system, the file descriptor remains valid and you can continue to read from it until you close it in your program. However, once the file is closed, you cannot reopen it because it has been deleted from the file system. 

OS does have a limit on the number of file descriptors that can be open at any given time.
If a program tries to open more files than the system limit, the operating system will not allocate a new file descriptor and the file opening operation will fail. 

In below  example, even though the file is deleted with os.Remove, we can still read the text we wrote because the file descriptor is still active.

```
package main

import (
    "fmt"
    "io/ioutil"
    "os"
)

func main() {
    // Create a temporary file
    tmpfile, err := ioutil.TempFile("", "example")
    if err != nil {
        fmt.Println(err)
        return
    }

    // Write some text to the file
    text := []byte("Hello, World!")
    if _, err = tmpfile.Write(text); err != nil {
        fmt.Println(err)
        tmpfile.Close()
        return
    }

    // Delete the file
    os.Remove(tmpfile.Name())

    // Seek to the beginning of the file
    tmpfile.Seek(0, 0)

    // Read the text
    readText := make([]byte, len(text))
    if _, err = tmpfile.Read(readText); err != nil {
        fmt.Println(err)
        tmpfile.Close()
        return
    }

    fmt.Printf("%s\n", readText)

    // Close the file
    tmpfile.Close()
}
```

2024-05-31 09:53 UTC, pm-priyanka-bagade commented on modules/pubmatic/openwrap/wakanda/push_data_handler.go
> +	srcFile.Write(data)
done

2024-05-31 09:53 UTC, pm-priyanka-bagade commented on modules/pubmatic/openwrap/wakanda/wakanda_test.go
> +}
will do in phase 2 of wakanda refactoring

2024-06-06 11:14 UTC, ashishshinde-pubm commented on analytics/pubmatic/helper.go
> +			glog.Error("Failed to marshal ao.Response while setting wakanda object")
please add error string in error.
glog.Errorf("Failed to marshal ao.Response while setting wakanda object err:%s",err.Error())

2024-06-06 11:14 UTC, ashishshinde-pubm commented on analytics/pubmatic/helper.go
> +			glog.Error("Failed to parse loggerURL while setting wakanda object")
please add error string in error.
`glog.Errorf("Failed to marshal ao.Response while setting wakanda object err:%s",err.Error())`

2024-06-06 11:25 UTC, ashishshinde-pubm submitted a review, later dismissed

2024-06-07 10:06 UTC, ashishshinde-pubm approved these changes

2024-06-07 13:33 UTC, Pubmatic-Dhruv-Sonone commented on analytics/pubmatic/helper_test.go
> +			args: args{
Won't the  `setWakandaWinningBidFlag`  function panic   if `wakandDebug` is  nil. I don't see any nil check on wakandaDebug in `setWakandaWinningBidFlag` and its underlying call to `wakandaDebug.SetWinningBid`

2024-06-07 13:43 UTC, Pubmatic-Dhruv-Sonone requested changes

2024-06-07 13:43 UTC, Pubmatic-Dhruv-Sonone commented on analytics/pubmatic/helper_test.go
> +			if tt.args.wakandaDebug != nil {
Why is this `if tt.args.wakandaDebug != nil {` check needed? 
if wakandaDebug is nil and bids are present in response then `setWakandaWinningBidFlag` will panic

2024-06-07 13:51 UTC, Pubmatic-Dhruv-Sonone submitted a review, later dismissed

2024-06-11 05:45 UTC, ashishshinde-pubm approved these changes

2024-06-11 09:00 UTC, ashishshinde-pubm approved these changes
LGTM

2024-06-11 11:06 UTC, Pubmatic-Dhruv-Sonone approved these changes

2024-06-11 11:26 UTC, ashishshinde-pubm submitted a review, later dismissed

2024-06-26 11:55 UTC, ashishshinde-pubm approved these changes

2024-07-01 08:23 UTC, pm-nilesh-chate approved these changes

2024-07-01 08:23 UTC, merged