OTT-1734: map bidder-params in bidRequest body
PubMatic-OpenWrap/prebid-server pull request #786
Opened 2024-05-06 06:32 UTC by ashishshinde-pubm

2024-05-06 06:53 UTC, ashishshinde-pubm commented on adapters/ortbbidder/ortbbidder.go
> +	"github.com/golang/glog"
Fixed it

2024-05-06 08:56 UTC, Pubmatic-Dhruv-Sonone commented on adapters/ortbbidder/bidderParamMapper.go
> +func (b bidderParamMapper) setBidderParam(bidderName string, paramName string, paramValue string) {
Nitpick:  `setBidderParam(bidderName, paramName, paramValue string)`

2024-05-06 08:57 UTC, Pubmatic-Dhruv-Sonone commented on adapters/ortbbidder/bidderParamMapper.go
> +func (b bidderParamMapper) setBidderParam(bidderName string, paramName string, paramValue string) {
Can we use some appropriate var name instead of `b`?

2024-05-06 10:05 UTC, Pubmatic-Dhruv-Sonone commented on adapters/ortbbidder/bidderParamMapper.go
> +	for i, part := range parts {
can we rename `part` to `nodeName` ?

2024-05-06 10:26 UTC, AvinashKapre commented on adapters/ortbbidder/bidderParamMapper.go
> +	return mapper, mapperErr
No need to return ```mapper```

2024-05-06 10:28 UTC, Pubmatic-Dhruv-Sonone commented on adapters/ortbbidder/bidderParamMapper.go
> +func InitMapper(dirPath string) (*Mapper, error) {
No need to return Mapper as its not being used.

2024-05-06 10:37 UTC, AvinashKapre commented on adapters/ortbbidder/bidderParamMapper.go
> +		mapper.bidderParamMapper, err = updateBidderParamsMapper(mapper.bidderParamMapper, fileContentsMap, bidderName)
No need to return ```mapper.bidderParamMapper```

2024-05-07 09:38 UTC, AvinashKapre approved these changes

2024-05-07 12:00 UTC, pm-viral-vala requested changes

2024-05-07 12:00 UTC, pm-viral-vala commented on adapters/ortbbidder/bidderParamMapper.go
> +func updateBidderParamsMapper(mapper bidderParamMapper, fileContentsMap JSONNode, bidderName string) (bidderParamMapper, error) {
Can we make this function as member function of bidderParamMapper?

2024-05-07 12:00 UTC, pm-viral-vala commented on adapters/ortbbidder/bidderParamMapper.go
> +func updateBidderParamsMapper(mapper bidderParamMapper, fileContentsMap JSONNode, bidderName string) (bidderParamMapper, error) {
func (bpm BPM) updateBidderParams(bidderName string, params JSONNode)

2024-05-07 12:00 UTC, pm-viral-vala commented on adapters/ortbbidder/bidderParamMapper.go
> +	parts := strings.Split(location, ".")
can we try to split the location only once while initializing bidderParamMapper?

2024-05-07 12:00 UTC, pm-viral-vala commented on adapters/ortbbidder/bidderParamMapper.go
> +			currentNode = newNode
can we reduce if...else

2024-05-07 12:00 UTC, pm-viral-vala commented on adapters/ortbbidder/bidderParamMapper.go
> +func setValueAtLocation(node JSONNode, location string, value any) bool {
Can we make setValue a member function

2024-05-07 13:11 UTC, Pubmatic-Dhruv-Sonone requested changes

2024-05-08 03:04 UTC, ashishshinde-pubm commented on adapters/ortbbidder/bidderParamMapper.go
> +	for i, part := range parts {
we dont need to do the strings.Spilt() for every request hence removed this part. 
Now we are getting locations as an array, and iterating over it using "loc" local-name

2024-05-08 03:04 UTC, ashishshinde-pubm commented on adapters/ortbbidder/bidderParamMapper.go
> +func (b bidderParamMapper) setBidderParam(bidderName string, paramName string, paramValue string) {
yes, changed it to `bpm`

2024-05-08 03:04 UTC, ashishshinde-pubm commented on adapters/ortbbidder/bidderParamMapper.go
> +func (b bidderParamMapper) setBidderParam(bidderName string, paramName string, paramValue string) {
removed this function itself, plz check latest code.

2024-05-08 03:04 UTC, ashishshinde-pubm commented on adapters/ortbbidder/bidderParamMapper.go
> +	return mapper, mapperErr
agree, made changes

2024-05-08 03:04 UTC, ashishshinde-pubm commented on adapters/ortbbidder/bidderParamMapper.go
> +func InitMapper(dirPath string) (*Mapper, error) {
done

2024-05-08 03:05 UTC, ashishshinde-pubm commented on adapters/ortbbidder/bidderParamMapper.go
> +		mapper.bidderParamMapper, err = updateBidderParamsMapper(mapper.bidderParamMapper, fileContentsMap, bidderName)
yes, also renamed the function to `setBidderParamsDetails`

2024-05-08 03:06 UTC, ashishshinde-pubm commented on adapters/ortbbidder/bidderParamMapper.go
> +type JSONNode = map[string]interface{}
done

2024-05-08 03:06 UTC, ashishshinde-pubm commented on adapters/ortbbidder/bidderParamMapper.go
> +type Mapper struct {
yes, corrected it

2024-05-08 03:22 UTC, ashishshinde-pubm commented on main.go
> +	mapper, err := ortbbidder.InitMapper(paramsDirectory)
yes, done

2024-05-08 03:23 UTC, ashishshinde-pubm commented on main.go
> +	mapper, err := ortbbidder.InitMapper(paramsDirectory)
as discussed we need to terminate the process when InitMapper returns error, and its not a good idea to terminate from init() function of package.

2024-05-08 03:26 UTC, ashishshinde-pubm commented on main.go
> +const paramsDirectory = "./static/bidder-params"
done

2024-05-08 03:29 UTC, ashishshinde-pubm commented on adapters/ortbbidder/bidderParamMapper.go
> +func updateBidderParamsMapper(mapper bidderParamMapper, fileContentsMap JSONNode, bidderName string) (bidderParamMapper, error) {
yes, changed it to
```
func (bpm bidderParamMapper) setBidderParamsDetails(bidderName string, params jsonNode) error 
```

2024-05-08 03:30 UTC, ashishshinde-pubm commented on adapters/ortbbidder/bidderParamMapper.go
> +	parts := strings.Split(location, ".")
yes, made the changes

2024-05-08 03:35 UTC, ashishshinde-pubm commented on adapters/ortbbidder/bidderParamMapper.go
> +			currentNode = newNode
done

2024-05-08 03:42 UTC, ashishshinde-pubm commented on adapters/ortbbidder/bidderParamMapper.go
> +func setValueAtLocation(node JSONNode, location string, value any) bool {
done

2024-05-08 03:42 UTC, ashishshinde-pubm commented on adapters/ortbbidder/bidderParamMapper.go
> +	params, ok := b[bidderName]
This function has been removed

2024-05-08 03:49 UTC, ashishshinde-pubm commented on adapters/ortbbidder/bidderParamMapper.go
> +		filePath := filepath.Join(dirPath, file.Name())
done

2024-05-08 03:49 UTC, ashishshinde-pubm commented on adapters/ortbbidder/bidderParamMapper.go
> +var mapperErr error
removed this mapperErr since we are not making mapper as singleton instance

2024-05-08 03:50 UTC, ashishshinde-pubm commented on adapters/ortbbidder/bidderParamMapper.go
> +var mapper *Mapper
not applicable after new changes.

2024-05-08 03:52 UTC, ashishshinde-pubm commented on main.go
> +const paramsDirectory = "./static/bidder-params"
No, we are planning to use existing flow of prebid to initialise bidder-params and build the builders/adapters.
If we moved ortbbidders.json to separate files then we will have to write new code to initialise bidder-params and its validator and which may cause conflict in prebid server upgrade.

2024-05-08 03:58 UTC, ashishshinde-pubm commented on adapters/ortbbidder/ortbbidder.go
> +				DealPriority: 1, //????
TODO - remove this

2024-05-08 06:52 UTC, Pubmatic-Dhruv-Sonone commented on adapters/ortbbidder/bidderParamMapper.go
> +	mapper := &mapper{bidderParamMapper: make(bidderParamMapper)}
Change to
`mapper := &mapper{bidderParamMapper: make(bidderParamMapper, len(files)}`

2024-05-08 06:55 UTC, Pubmatic-Dhruv-Sonone commented on adapters/ortbbidder/bidderParamMapper.go
> +	paramsDetails := make(map[string]paramDetails)
Can we change this to ?
`paramsDetails := make(map[string]paramDetails, len(propertiesMap))`

2024-05-09 02:51 UTC, ashishshinde-pubm commented on adapters/ortbbidder/bidderParamMapper.go
> +	mapper := &mapper{bidderParamMapper: make(bidderParamMapper)}
len(files) is 210 however and number of oRTB bidders would be quite less as compared to 210.

2024-05-09 02:52 UTC, ashishshinde-pubm commented on adapters/ortbbidder/bidderParamMapper.go
> +	paramsDetails := make(map[string]paramDetails)
yes

2024-05-14 05:25 UTC, pm-viral-vala requested changes

2024-05-14 05:25 UTC, pm-viral-vala commented on adapters/ortbbidder/bidderParamMapper.go
> +	return details
we shouldn't update details (paramDetails) from the function, if someone has changed paramDetails from call by value to reference structure then this may introduce an error.

2024-05-14 06:12 UTC, Pubmatic-Dhruv-Sonone requested changes

2024-05-14 06:12 UTC, Pubmatic-Dhruv-Sonone commented on adapters/ortbbidder/bidderParamMapper_test.go
> +				err := os.MkdirAll("test", 0755)
can we use `t.TempDir` here?

2024-05-14 06:12 UTC, Pubmatic-Dhruv-Sonone commented on adapters/ortbbidder/bidderParamMapper_test.go
> +func Test_mapBidderParamsInRequest(t *testing.T) {
nitpick: TestMapBidderParamsInRequest

2024-05-14 06:12 UTC, Pubmatic-Dhruv-Sonone commented on adapters/ortbbidder/bidderParamMapper_test.go
> +					fmt.Printf("cleanup returned error for test:%s, err:%v , remove 'test' directory manually", tt.name, err)
Can we use t.logf instead?

2024-05-14 06:14 UTC, Pubmatic-Dhruv-Sonone commented on adapters/ortbbidder/bidderParamMapper_test.go
> +	var cleanup = func() error {
Can we write a single clean function using `t.Cleanup` ?

2024-05-15 05:56 UTC, ashishshinde-pubm commented on adapters/ortbbidder/ortbbidder_test.go
> +func Test_prepareRequestData(t *testing.T) {
done

2024-05-15 05:56 UTC, ashishshinde-pubm commented on adapters/ortbbidder/bidderParamMapper_test.go
> +func Test_setBidderParamsDetails(t *testing.T) {
done

2024-05-15 06:32 UTC, ashishshinde-pubm commented on adapters/ortbbidder/bidderParamMapper_test.go
> +	var cleanup = func() error {
done

2024-05-15 06:36 UTC, ashishshinde-pubm commented on adapters/ortbbidder/bidderParamMapper_test.go
> +					fmt.Printf("cleanup returned error for test:%s, err:%v , remove 'test' directory manually", tt.name, err)
done

2024-05-15 06:36 UTC, ashishshinde-pubm commented on adapters/ortbbidder/bidderParamMapper_test.go
> +func Test_mapBidderParamsInRequest(t *testing.T) {
done

2024-05-15 06:41 UTC, ashishshinde-pubm commented on adapters/ortbbidder/bidderParamMapper_test.go
> +	for _, tt := range tests {
done

2024-05-15 06:42 UTC, ashishshinde-pubm commented on adapters/ortbbidder/bidderParamMapper_test.go
> +func Test_applyConditionalMapping(t *testing.T) {
Removed this function

2024-05-16 02:38 UTC, ashishshinde-pubm commented on adapters/ortbbidder/bidderParamMapper.go
> +type paramDetails struct {
okay

2024-05-16 02:38 UTC, ashishshinde-pubm commented on adapters/ortbbidder/bidderParamMapper.go
> +type bidderParamMapper map[string]map[string]paramDetails
done

2024-05-16 02:39 UTC, ashishshinde-pubm commented on adapters/ortbbidder/bidderParamMapper.go
> +	return details
agree, corrected this

2024-05-16 02:45 UTC, ashishshinde-pubm commented on adapters/ortbbidder/bidderParamMapper_test.go
> +				err := os.MkdirAll("test", 0755)
yes, made the changes.
with t.TempDir we dont need to write explicit cleanup function

2024-05-16 12:41 UTC, Pubmatic-Dhruv-Sonone approved these changes

2024-05-17 05:21 UTC, ShriprasadM requested changes

2024-05-18 14:20 UTC, ashishshinde-pubm commented on adapters/ortbbidder/bidderConfig.go
> +// bidderProperty contains property details like location
as discussed, renamed the functions & variables

2024-05-18 14:20 UTC, ashishshinde-pubm commented on adapters/ortbbidder/bidderConfig.go
> +	for ind, eachImp := range impList {
done

2024-05-18 14:20 UTC, ashishshinde-pubm commented on adapters/ortbbidder/bidderConfig.go
> +	impList, ok := requestBodyMap[impKey].([]any)
done

2024-05-18 14:20 UTC, ashishshinde-pubm commented on adapters/ortbbidder/bidderConfig.go
> +	requestBodyMap := map[string]any{}
okay

2024-05-18 14:21 UTC, ashishshinde-pubm commented on adapters/ortbbidder/bidderConfig.go
> +	appKey     = "app"
corrected it

2024-05-18 14:21 UTC, ashishshinde-pubm commented on adapters/ortbbidder/bidderConfig.go
> +func mapBidderParamsInRequest(requestBody []byte, bidderParamDetails map[string]bidderProperty) ([]byte, error) {
renamed it to `requestParams`

2024-05-18 14:21 UTC, ashishshinde-pubm commented on adapters/ortbbidder/ortbbidder.go
>  	body, err := json.Marshal(request)
ok

2024-05-18 14:21 UTC, ashishshinde-pubm commented on adapters/ortbbidder/bidderConfig.go
> +package ortbbidder
as discussed, modified the file structure

2024-05-20 07:04 UTC, pm-viral-vala approved these changes

2024-05-20 08:20 UTC, ashishshinde-pubm commented on adapters/ortbbidder/ortbbidder.go
> +func (o adapterInfo) prepareRequestData(request *openrtb2.BidRequest, requestParams map[string]bidderparams.BidderParamMapper) (*adapters.RequestData, error) {
done

2024-05-20 08:22 UTC, ashishshinde-pubm commented on adapters/ortbbidder/bidderparams/parser.go
> +func loadRequestParams(bidderName string, requestParamsConfig map[string]any) (map[string]BidderParamMapper, error) {
okay

2024-05-20 08:40 UTC, ashishshinde-pubm commented on adapters/ortbbidder/ortbbidder.go
> +		Body:   requestBody,
I've set generic headers (accept and content-type) for now.
BidderName is pubmatic specific code change and is being used only in MakebBids function of pubmatic bidder to create targeting keys, So we will not set it.

2024-05-20 09:10 UTC, pm-viral-vala approved these changes

2024-05-20 09:13 UTC, pm-viral-vala approved these changes

2024-05-20 09:14 UTC, merged