OTT-1799: support for macros in oRTB bidder endpoint-url
PubMatic-OpenWrap/prebid-server pull request #805
Opened 2024-06-03 02:54 UTC by ashishshinde-pubm

2024-06-03 06:07 UTC, Pubmatic-Dhruv-Sonone requested changes

2024-06-03 06:07 UTC, Pubmatic-Dhruv-Sonone commented on adapters/ortbbidder/requestParamMapper.go
> +		if setValue(request, imp, paramMapper.GetLocation(), paramValue) {
instead of traversing the complete request every time to update imp object,, can we pass imp object here and param location with reference the imp node?

If location is ["response", "imp", "ext", "ImpID"] 
we can pass imp object and ["ext", "ImpID"]

2024-06-04 06:37 UTC, pm-nikhil-vaidya commented on adapters/ortbbidder/ortbbidder.go
> +		return nil, []error{newBadInputError("invalid imp object found in request")}
Nitpick : Change error message to `imp object not found in request`

2024-06-04 06:43 UTC, AvinashKapre commented on adapters/ortbbidder/ortbbidder.go
> +			uri, err = macros.ResolveMacros(adapterInfo.endpointTemplate, bidderParams)
NitPick: can we rename ```ResolveMacros``` -> ```ResolveUriMacros```

2024-06-04 09:49 UTC, pm-nikhil-vaidya commented on adapters/ortbbidder/ortbbidder.go
> +		bidderParams map[string]any
Nitpick: short variable declaration can be done for `bidderParams`

2024-06-04 10:26 UTC, pm-nikhil-vaidya commented on adapters/ortbbidder/ortbbidder.go
>  }
We can combine `makeRequestPerImp` and `makeRequestForAllImps`, and pass `o.adapterInfo.extraInfo.RequestMode` as function parameter to decide single request creation or multiple

2024-06-04 10:28 UTC, pm-nikhil-vaidya commented on adapters/ortbbidder/ortbbidder.go
>  }
We don't need two functions as implementation is mostly same

2024-06-04 10:35 UTC, pm-nikhil-vaidya commented on adapters/ortbbidder/util.go
>  		if len(loc) == 0 { // if location part is empty string
If we have loc part empty that means in the template, someone provide values like `imp.ext.test.`, should it be invalid and should it be handled beforehand?

2024-06-04 11:21 UTC, pm-nikhil-vaidya commented on adapters/ortbbidder/util.go
>  		if len(loc) == 0 { // if location part is empty string
Or return true, so that entry should be deleted from the bidder params as its location is invalid

2024-06-04 11:32 UTC, pm-nikhil-vaidya commented on adapters/ortbbidder/util.go
> +		nextNode := getNode(currentNode, impNode, loc)
Compare performace with jsonparser.Set() with this map manipulations

2024-06-04 11:36 UTC, pm-nikhil-vaidya requested changes
Added some commets

2024-06-05 03:27 UTC, ashishshinde-pubm commented on adapters/ortbbidder/ortbbidder.go
> +		return nil, []error{newBadInputError("invalid imp object found in request")}
done

2024-06-05 03:27 UTC, ashishshinde-pubm commented on adapters/ortbbidder/requestParamMapper.go
> +		if setValue(request, imp, paramMapper.GetLocation(), paramValue) {
as discussed, requirement is different so this needs to be handled in same way

2024-06-05 03:28 UTC, ashishshinde-pubm commented on adapters/ortbbidder/ortbbidder.go
> +			uri, err = macros.ResolveMacros(adapterInfo.endpointTemplate, bidderParams)
`ResolveMacros` is prebid's function so we cannt rename it

2024-06-05 03:39 UTC, ashishshinde-pubm commented on adapters/ortbbidder/ortbbidder.go
> +	requestParams, _ := o.bidderParamsConfig.GetRequestParams(o.bidderName.String())
done

2024-06-05 03:57 UTC, ashishshinde-pubm commented on adapters/ortbbidder/ortbbidder.go
> +		bidderParams map[string]any
yes

2024-06-05 03:58 UTC, ashishshinde-pubm commented on adapters/ortbbidder/ortbbidder.go
>  }
as discussed, combined this functions.
Thanks for your valuable inputs

2024-06-05 04:01 UTC, ashishshinde-pubm commented on adapters/ortbbidder/util.go
>  		if len(loc) == 0 { // if location part is empty string
we are planning to write the utility script to check for such errors while onboarding bidder. Refer - https://inside.pubmatic.com:9443/jira/browse/OTT-1816 
So ideally such scenario will never happen. 
If location field is not provided then we are not removing the imp.ext.bidder fields hence to have same behaviour 
we are not removing/deleting the bidder-param.

2024-06-05 04:30 UTC, ashishshinde-pubm commented on adapters/ortbbidder/util.go
> +		nextNode := getNode(currentNode, impNode, loc)
there are some downside of using jsonparser.Set like we will need to maintain the data-type of each field. 
But if the performance is better than json-marshal then we will cerntainly move to it. 
But, will address this in https://inside.pubmatic.com:9443/jira/browse/OTT-1798 since it needs extra handling from Dev side

2024-06-05 05:02 UTC, Pubmatic-Dhruv-Sonone requested changes

2024-06-05 05:02 UTC, Pubmatic-Dhruv-Sonone commented on adapters/ortbbidder/requestParamMapper.go
> +		if setValue(request, imp, paramMapper.GetLocation(), paramValue) {
Can we add a generic setValue function that can handle array as well as json object?
You will have to change the how location are taken as input in bidder.json
For array, location can be [request.imp.{index}.impId],   {index} can be replaced at runtime.
 
```
func setValueAtLocation(node map[string]interface{}, location []string, value interface{}) bool {
    var (
        ok   bool
        next interface{} = node
    )
    lastIndex := len(location) - 1
    for i, loc := range location {
        switch next := next.(type) {
        case map[string]interface{}:
            if i == lastIndex {
                next[loc] = value
                return true
            }
            next, ok = next[loc]
            if !ok {
                return false
            }
        case []interface{}:
            index, err := strconv.Atoi(loc)
            if err != nil || index < 0 || index >= len(next) {
                return false
            }
            if i == lastIndex {
                next[index] = value
                return true
            }
            next = next[index]
        default:
            return false
        }
    }
    return false
}
```

2024-06-05 09:39 UTC, ashishshinde-pubm commented on adapters/ortbbidder/constant.go
> +	requestModeSingle = "single"
Not adding constants for now, so keeping it as it is

2024-06-05 09:40 UTC, ashishshinde-pubm commented on adapters/ortbbidder/ortbbidder.go
> +		if impIndex == 0 {
yes, ideally all imps should have values to replace macros.

2024-06-05 09:42 UTC, ashishshinde-pubm commented on adapters/ortbbidder/ortbbidder.go
> +func (adapterInfo adapterInfo) makeRequestPerImp(request map[string]any, requestParams map[string]bidderparams.BidderParamMapper) ([]*adapters.RequestData, []error) {
`BidderParamMapper` variable name has been changed multiple times.
After discussing with @ShriprasadM , we can concluded to use it so not changing it for now.

2024-06-06 10:51 UTC, pm-jaydeep-mohite commented on adapters/ortbbidder/bidderparams/config.go
>  	if bcfg == nil || len(bcfg.bidderConfigMap) == 0 {
Can restructure ? 



```
if bcfg == nil || len(bcfg.bidderConfigMap) == 0 || bcfg.bidderConfigMap[bidderName] == nil {
return nil 
} 

return bcfg.bidderConfigMap[bidderName].requestParams
```

2024-06-06 16:03 UTC, Pubmatic-Dhruv-Sonone requested changes

2024-06-06 16:03 UTC, Pubmatic-Dhruv-Sonone commented on adapters/ortbbidder/bidderparams/config.go
> +		return fmt.Errorf("BidderConfig is nil")
use `errors.New("BidderConfig is nil")`

2024-06-06 16:03 UTC, Pubmatic-Dhruv-Sonone commented on adapters/ortbbidder/bidderparams/config.go
>  	if bcfg == nil || len(bcfg.bidderConfigMap) == 0 {
Won't this require two map look ups,  original code only does it once.

2024-06-06 20:11 UTC, Pubmatic-Dhruv-Sonone requested changes

2024-06-06 20:11 UTC, Pubmatic-Dhruv-Sonone commented on adapters/ortbbidder/bidderparams/config.go
> +func (bcfg *BidderConfig) setRequestParams(bidderName string, requestParams map[string]BidderParamMapper) error {
if `bcfg == nil` is this check not need,  let it panic.  BidderConfig should be initialise once at the top.  Remove error return type.  The `setRequestParams` is being called on service initialisation, you won't need this checks on request processing, so let it panic if bidder config is invalid.
Even standard library does not handle this kind of errors.  
Refer [handle method with nil receiver](https://stackoverflow.com/questions/60878082/how-to-handle-method-with-nil-receiver)

2024-06-06 20:11 UTC, Pubmatic-Dhruv-Sonone commented on adapters/ortbbidder/bidderparams/config.go
>  	if bcfg.bidderConfigMap == nil {
`if bcfg.bidderConfigMap == nil {` Can we avoid this repetitive check and initialise this only once

2024-06-06 20:49 UTC, Pubmatic-Dhruv-Sonone requested changes

2024-06-06 20:49 UTC, Pubmatic-Dhruv-Sonone commented on adapters/ortbbidder/bidderparams/config.go
> +func (bpm *BidderParamMapper) SetLocation(location string) {
SetLocation is not being used anywhere other than unit test, remove it.

2024-06-07 06:30 UTC, ashishshinde-pubm commented on adapters/ortbbidder/bidderparams/config.go
> +func (bpm *BidderParamMapper) SetLocation(location string) {
done

2024-06-07 06:30 UTC, ashishshinde-pubm commented on adapters/ortbbidder/bidderparams/config.go
> +func (bcfg *BidderConfig) setRequestParams(bidderName string, requestParams map[string]BidderParamMapper) error {
okays

2024-06-07 06:31 UTC, ashishshinde-pubm commented on adapters/ortbbidder/bidderparams/config.go
> +		return fmt.Errorf("BidderConfig is nil")
yes

2024-06-07 06:32 UTC, ashishshinde-pubm commented on adapters/ortbbidder/bidderparams/config.go
>  	if bcfg == nil || len(bcfg.bidderConfigMap) == 0 {
yes, to avoid 2 map lookups, keeping it as it is

2024-06-07 11:20 UTC, ashishshinde-pubm commented on adapters/ortbbidder/bidderparams/config.go
>  	if bcfg.bidderConfigMap == nil {
okay

2024-06-10 05:55 UTC, ashishshinde-pubm commented on adapters/ortbbidder/requestParamMapper.go
> +		if setValue(request, imp, paramMapper.GetLocation(), paramValue) {
changes are done

2024-06-10 05:56 UTC, ashishshinde-pubm commented on adapters/ortbbidder/ortbbidder.go
>  }
we were missing readability after merging the functions, hence changed the logic. Please refer new code

2024-06-10 05:56 UTC, ashishshinde-pubm commented on adapters/ortbbidder/constant.go
> +	requestModeSingle = "single"
done

2024-06-10 05:58 UTC, Pubmatic-Dhruv-Sonone commented on adapters/ortbbidder/bidderparams/config.go
> +func (bcfg *BidderConfig) GetRequestParams(bidderName string) map[string]BidderParamMapper {
Do you see need to add interface to these methods, we can't mock these methods currently?

2024-06-10 06:03 UTC, ashishshinde-pubm commented on adapters/ortbbidder/util.go
> +func newBadInputError(message string) error {
done

2024-06-10 08:58 UTC, pm-nikhil-vaidya submitted a review, later dismissed

2024-06-10 11:20 UTC, Pubmatic-Dhruv-Sonone requested changes

2024-06-10 11:20 UTC, Pubmatic-Dhruv-Sonone commented on adapters/ortbbidder/requestBuilder_test.go
> +		// {
why is this commented

2024-06-10 12:16 UTC, Pubmatic-Dhruv-Sonone approved these changes

2024-06-11 07:15 UTC, ashishshinde-pubm commented on adapters/ortbbidder/requestBuilder_test.go
> +		// {
corrected it

2024-06-11 12:18 UTC, Pubmatic-Dhruv-Sonone requested changes

2024-06-11 12:18 UTC, Pubmatic-Dhruv-Sonone commented on adapters/ortbbidder/errors.go
> +func newBadInputError(message string) error {
Can we change this as below?
```
func newBadInputError(message string, args ...any) error {
	return &errortypes.BadServerResponse{
		Message: fmt.Sprintf(message, args...),
	}
}
```

2024-06-12 03:11 UTC, ashishshinde-pubm commented on adapters/ortbbidder/errors.go
> +func newBadInputError(message string) error {
done

2024-06-12 03:20 UTC, ashishshinde-pubm commented on adapters/ortbbidder/bidderparams/config.go
> +func (bcfg *BidderConfig) GetRequestParams(bidderName string) map[string]BidderParamMapper {
As discussed with @pm-viral-vala , having interface only for getter/setter is not standard thing, hence introduced `NewBidderConfig` and `SetRequestParams` methods

2024-06-12 04:26 UTC, Pubmatic-Dhruv-Sonone approved these changes

2024-06-12 04:44 UTC, pm-viral-vala approved these changes

2024-06-12 04:46 UTC, ashishshinde-pubm commented on adapters/ortbbidder/bidderparams/config.go
> +		return fmt.Errorf("BidderConfig is nil")
done

2024-06-12 04:46 UTC, ashishshinde-pubm commented on adapters/ortbbidder/requestBuilder.go
> +	requestNode         map[string]any
renamed it to newRequest

2024-06-12 04:48 UTC, merged