OTT-1802: [oRTB bidder] Map bidder-response parameters
PubMatic-OpenWrap/prebid-server pull request #837
Opened 2024-07-05 12:50 UTC by ashishshinde-pubm

2024-07-05 14:11 UTC, Pubmatic-Dhruv-Sonone requested changes

2024-07-05 14:11 UTC, Pubmatic-Dhruv-Sonone commented on adapters/ortbbidder/resolver/fledgeconfig_resolver.go
> +func validateFledgeConfig(fledgeCfg any) (map[string]any, bool) {
Can we do marshal/unmarshal to validate fledge config? 
If fledge struct changes in future we will have update this entire logic.

2024-07-05 14:11 UTC, Pubmatic-Dhruv-Sonone commented on adapters/ortbbidder/resolver/dealPriority_resolver_test.go
> +		{
Add test for invalid value found.

2024-07-05 14:11 UTC, Pubmatic-Dhruv-Sonone commented on adapters/ortbbidder/resolver/bidmeta_resolver_test.go
> +			name: "Found in location",
Add ut for invalid object scenario.

2024-07-05 14:11 UTC, Pubmatic-Dhruv-Sonone commented on adapters/ortbbidder/resolver/param_resolver.go
> +	setValue(targetNode map[string]any, value any) bool
bool returned is not being used anywhere. Is this needed?

2024-07-07 13:55 UTC, ashishshinde-pubm commented on adapters/ortbbidder/resolver/param_resolver.go
> +	setValue(targetNode map[string]any, value any) bool
Ideally there should be a way to convey whether the particular parameter was succesfully resolved or not.
My intension behind this was to add the log statement/ metric to identify failures but looks like log statements are not allowed in this package.

2024-07-07 13:55 UTC, ashishshinde-pubm commented on adapters/ortbbidder/resolver/bidmeta_resolver_test.go
> +			name: "Found in location",
done

2024-07-07 13:55 UTC, ashishshinde-pubm commented on adapters/ortbbidder/resolver/dealPriority_resolver_test.go
> +		{
done

2024-07-07 13:55 UTC, ashishshinde-pubm commented on adapters/ortbbidder/resolver/fledgeconfig_resolver.go
> +func validateFledgeConfig(fledgeCfg any) (map[string]any, bool) {
agree, will use marshal/unmarshal for validating complex objects

2024-07-07 13:55 UTC, ashishshinde-pubm commented on adapters/ortbbidder/resolver/helper.go
> +func validateJSONRawMessage(value any) (map[string]any, bool) {
renamed it to `validateMap`

2024-07-07 13:55 UTC, ashishshinde-pubm commented on adapters/ortbbidder/resolver/helper.go
> +}
done

2024-07-08 12:09 UTC, ashishshinde-pubm commented on adapters/ortbbidder/response_builder_test.go
> +									"networkId":         int(5), //TODO ??????????????????????? (discuss this)
TODO - discuss this

2024-07-09 06:01 UTC, Pubmatic-Dhruv-Sonone approved these changes

2024-07-09 13:03 UTC, ashishshinde-pubm commented on adapters/ortbbidder/response_builder_test.go
> +									"networkId":         int(5), //TODO ??????????????????????? (discuss this)
done

2024-07-09 16:37 UTC, ShriprasadM requested changes

2024-07-10 03:01 UTC, ashishshinde-pubm commented on adapters/ortbbidder/resolver/bidmeta_resolver.go
> +type bidMetaResolver struct {
`adaptercode` field is explicitly set by prebid while forming the bidExt. Refer `makeBidExtJSON` function.
It is not expected to be set by bidder/adapter.

2024-07-10 03:02 UTC, ashishshinde-pubm commented on adapters/ortbbidder/resolver/bidVideo_resolver.go
> +// 2. If not found, it then tries to retrieve the duration using the bidder param location.
yes, its a typo.
Corrected it.

2024-07-10 03:10 UTC, ashishshinde-pubm commented on adapters/ortbbidder/resolver/bidmeta_resolver.go
> +func (b *bidMetaResolver) retrieveFromBidderParamLocation(responseNode map[string]any, path string) (any, bool) {
yes, for structs like objects , we have added the support to retrieve the both individual fields (advertiserId) as well as complete object (bidMeta).
If value for same parameter (advertiserId) is present in both individual field (advertiserId) and complete object (meta), then individual field will have high priority.
Note - We have not added the support for individual fields present in `fledge` configuration. Since its an array of object.

2024-07-10 03:37 UTC, ashishshinde-pubm commented on adapters/ortbbidder/resolver/bidmeta_resolver_test.go
> +import (
Done, added this for bidMeta and bidVideo fields

2024-07-10 03:53 UTC, ashishshinde-pubm commented on adapters/ortbbidder/resolver/bidVideo_resolver.go
> +	return int64(dur), true
type casting never panics. 
Do you have any other concern specific to int64 ? Please elaborate

2024-07-12 11:01 UTC, ShriprasadM reviewed
@ashishshinde-pubm : Few more review comments.

2024-07-15 06:22 UTC, ashishshinde-pubm commented on adapters/ortbbidder/resolver/param_resolver.go
> +type defaultValueResolver struct{}
yes, it can be done.
Made the necessary changes

2024-07-15 06:29 UTC, ashishshinde-pubm commented on adapters/ortbbidder/resolver/bidmeta_resolver_test.go
> +	expectedFields := map[string]reflect.Type{
This constants are being used only in test functions, also they are not being used repetitively. Hence directly used them

2024-07-15 06:29 UTC, ashishshinde-pubm commented on adapters/ortbbidder/resolver/bidVideo_resolver_test.go
> +func TestExtBidPrebidVideoFields(t *testing.T) {
Done, added for all object fields.

2024-07-15 06:36 UTC, ashishshinde-pubm commented on adapters/ortbbidder/resolver/constant.go
> +	bidMetaSecondaryCatIdKey    = "secondaryCatIds"
yes, we have created separate task for this improvement

2024-07-16 12:18 UTC, ashishshinde-pubm commented on adapters/ortbbidder/resolver/param_resolver.go
> +func (pr *paramResolver) Resolve(sourceNode, targetNode map[string]any, path string, param parameter) bool {
Done, now we will get the warning if any issue occurred while mapping bidder-response param.
```
 "warnings": {
            "general": [
                {
                    "code": 10002,
                    "message": "debug turned off for account"
                }
            ],
            "owortb_testbidder": [
                {
                    "code": 0,
                    "message": "failed to map response-param:[fledgeAuctionConfig] value:[[map[adapter:ashish_adapter bidder:1 config:map[test-key:test-value]]]]"
                },
                {
                    "code": 0,
                    "message": "failed to map response-param:[dealPriority] value:[a]"
                }
            ]
        },
```

2024-07-24 05:45 UTC, ShriprasadM approved these changes
LGTM

2024-07-24 06:15 UTC, Pubmatic-Dhruv-Sonone approved these changes

2024-07-24 06:18 UTC, merged