OTT-1659: Use NBR for logging APRC in logger
PubMatic-OpenWrap/prebid-server pull request #848
Opened 2024-07-11 10:49 UTC by Pubmatic-Supriya-Patil

# Description

Please add change description or link to ticket, docs, etc.

# Checklist:

- [ ] PR commit list is unique (rebase/pull with the origin branch to keep master clean).
- [ ] JIRA number is added in the PR title and the commit message.
- [ ] Updated the `header-bidding` repo with appropiate commit id.
- [ ] Documented the new changes.

For Prebid upgrade, refer: https://inside.pubmatic.com:8443/confluence/display/Products/Prebid-server+upgrade

2024-07-17 15:34 UTC, ShriprasadM requested changes

2024-07-17 15:34 UTC, ShriprasadM commented on endpoints/openrtb2/ctv/adpod/dynamic_adpod.go
> +func getBidDuration(bid *openrtb2.Bid, reqExt *openrtb_ext.ExtRequestAdPod, config []*types.ImpAdPodConfig, defaultDuration int64) (int64, *openrtb3.NoBidReason) {
@Pubmatic-Supriya-Patil  and @pm-nikhil-vaidya 
Missing here the SRP (Single Responsibility Principle). Its doing following 3 things

1.  Determining duration of the bid (which is its core responsibility)
2. Validating and determining the duration as per policy (not a responsibility of this function)
3. Determining Non-bid reason code. 

Refactored code 
```go
// validate bid duration
	bidDuration := getDuration(bid, da.ImpConfigs[sequence-1].MaxDuration)
	var durations []int
	for _, config := range da.ImpConfigs {
		durations = append(durations, int(config.MinDuration))
		durations = append(durations, int(config.MaxDuration))
	}
	matches, bidDuration := isDurationMatchesPolicy(bidDuration, da.ReqAdpodExt.VideoAdDurationMatching, durations)
	var nbr openrtb3.NoBidReason
	if !matches {
		nbr = exchange.ResponseRejectedInvalidCreative
	}
```

`ad_duration.go`
```go
package adpod

import (
	"sort"

	"github.com/buger/jsonparser"
	"github.com/prebid/openrtb/v20/openrtb2"
	"github.com/prebid/prebid-server/v2/openrtb_ext"
)

func getDuration(bid *openrtb2.Bid, defaultDuration int64) int64 {
	if bid.Dur > 0 {
		return bid.Dur
	}
	if bid.Ext != nil {
		if duration, err := jsonparser.GetInt(bid.Ext, "prebid", "video", "duration"); err == nil && duration > 0 {
			return duration
		}
	}
	return defaultDuration
}

func isDurationMatchesPolicy(bidDuration int64, policy openrtb_ext.OWVideoAdDurationMatchingPolicy, durations []int) (bool, int64) {
	sort.Ints(durations)
	for _, duration := range durations {
		switch policy {
		case openrtb_ext.OWExactVideoAdDurationMatching:
			if bidDuration == int64(duration) {
				return true, bidDuration
			}
		case openrtb_ext.OWRoundupVideoAdDurationMatching:
			if int64(duration) >= bidDuration {
				return true, int64(duration)
			}
		}
	}
	return false, 0
}

```

2024-07-18 04:18 UTC, ShriprasadM requested changes

2024-07-18 04:18 UTC, ShriprasadM commented on endpoints/openrtb2/ctv/response/adpod_generator.go
> +					return nil, inext, jnext, ptrutil.ToPtr(exchange.ResponseRejectedCreativeAdvertiserExclusions)
@Pubmatic-Supriya-Patil : can't we use vanilla Prebid's method rather for pointer conversion - https://github.com/prebid/prebid-server/blob/99431ad83fa7546d8e8d60acc3feae77c815f37f/exchange/non_bid_reason.go#L19

2024-07-18 09:33 UTC, Pubmatic-Supriya-Patil commented on endpoints/openrtb2/ctv/adpod/dynamic_adpod.go
> +func getBidDuration(bid *openrtb2.Bid, reqExt *openrtb_ext.ExtRequestAdPod, config []*types.ImpAdPodConfig, defaultDuration int64) (int64, *openrtb3.NoBidReason) {
@ShriprasadM As discussed we can have this changes in modules code as we are moving to modules.

2024-07-18 09:44 UTC, Pubmatic-Supriya-Patil commented on endpoints/openrtb2/ctv/adpod/adpod.go
>  func addSeatNonBids(bids []*types.Bid) openrtb_ext.NonBidCollection {
Done

2024-07-19 08:38 UTC, ShriprasadM approved these changes
LGTM

2024-07-19 16:27 UTC, pm-nikhil-vaidya commented on endpoints/openrtb2/ctv/adpod/structured_adpod_test.go
>  	"testing"
Can you please add test case where provide exclusion configs and call hold auction and check if NBR are properly getting updated

2024-08-06 08:44 UTC, Pubmatic-Supriya-Patil commented on endpoints/openrtb2/ctv/adpod/structured_adpod_test.go
>  	"testing"
Done

2024-08-06 08:49 UTC, merged