UOE-10893: Mult floor multi bid support for AppLovinMax
PubMatic-OpenWrap/prebid-server pull request #861
Opened 2024-07-26 17:47 UTC by AvinashKapre

2024-07-29 03:17 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/auctionresponsehook.go
> +	re := regexp.MustCompile(models.AppLovinMaxImpressionPattern)
No need to compile regex each time. If possible, compile the regex only once.

2024-07-29 03:21 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/auctionresponsehook.go
> +		if seatBid.Seat == models.BidderPubMatic {
please check if this case is valid for an alias of `pubmatic` bidder.

2024-07-29 03:25 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/auctionresponsehook.go
> +	}
please confirm, if we need to consider the `deal` bids. 
In case of deal bids, above price based comparison might not work

2024-07-29 05:08 UTC, pm-nikhil-vaidya commented on adapters/pubmatic/pubmatic.go
> +		wrapperExtFromImp, pubIDFromImp, floors, err := parseImpressionObject(&request.Imp[i], extractWrapperExtFromImp, extractPubIDFromImp)
don't need to declare variable explicitly, it is taken care by short variable declaration

2024-07-29 05:18 UTC, pm-nikhil-vaidya commented on adapters/pubmatic/pubmatic.go
> +			impFloorsMap[request.Imp[i].ID] = floors
Instead of declaring map and creating multi impressions at last, check if we can create impressions here itself

2024-07-29 05:28 UTC, AvinashKapre commented on adapters/pubmatic/pubmatic.go
> +			impFloorsMap[request.Imp[i].ID] = floors
We are creating multi request not multi impression

2024-07-29 05:41 UTC, pm-nikhil-vaidya requested changes

2024-07-29 05:41 UTC, pm-nikhil-vaidya commented on modules/pubmatic/openwrap/auctionresponsehook.go
> +			bidResponse.SeatBid[i].Bid = winningBids
We do not update the bid response in the hook execution, as per prebid request or response should be always updated with mutations

2024-07-29 06:01 UTC, AvinashKapre commented on modules/pubmatic/openwrap/auctionresponsehook.go
> +			bidResponse.SeatBid[i].Bid = winningBids
yes, that's true but if here we want to do so then need to add changes in existing auction logic, we need updated pubmatic response before auction.

2024-07-29 06:04 UTC, AvinashKapre commented on modules/pubmatic/openwrap/auctionresponsehook.go
> +			bidResponse.SeatBid[i].Bid = winningBids
here we are updating directly the ```bidResponse.SeatBid[i].Bid``` for pubmatic it should not be issue

2024-07-29 09:13 UTC, pm-isha-bharti commented on openrtb_ext/imp_pubmatic.go
> +	AppLovinFloors      []float64               `json:"applovin_floors,omitempty"`
Please remove `applovin` as this feature can be used for other SDK mediation (e.g. IronSource)

2024-08-05 11:50 UTC, pm-nikhil-vaidya approved these changes

2024-08-09 07:59 UTC, pm-saurabh-narkhede approved these changes

2024-08-09 08:00 UTC, merged