OTT-1807: discard emptyVAST and invalidVAST bids detected by VAST unwrap module
PubMatic-OpenWrap/prebid-server pull request #874
Opened 2024-08-10 08:39 UTC by ashishshinde-pubm

2024-08-21 08:42 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/openwrap/hook_raw_bidder_response.go
> +		if notEligibleForUnwrap(bid) {
Can you please rename it to isEligibleForUnwrap ==> 
if !isEligibleForUnwrap(bid) {
continue
}

2024-08-21 08:42 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/openwrap/unwrap/unwrap.go
> +
Please remove below redundant check. This is already checked in notEligibleForUnwrap function.

2024-08-21 08:54 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/unwrap/unwrap.go
> +
done, removed redundent if-else check

2024-08-21 08:55 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/hook_raw_bidder_response.go
> +		if notEligibleForUnwrap(bid) {
done

2024-08-22 04:20 UTC, pm-nikhil-vaidya requested changes

2024-08-22 04:20 UTC, pm-nikhil-vaidya commented on modules/pubmatic/openwrap/hook_raw_bidder_response.go
> +		}(*bid)
Pass `bid` as pointer to avoid multiple reference and dereference

2024-08-22 04:20 UTC, pm-nikhil-vaidya commented on modules/pubmatic/openwrap/hook_raw_bidder_response.go
> +	unwrappedBidsChan := make(chan bidInfo, len(payload.Bids))
Close the channel after its use

2024-08-22 04:20 UTC, pm-nikhil-vaidya commented on modules/pubmatic/openwrap/hook_raw_bidder_response.go
> +		if rejectBid(unwrappedBid.unwrapStatus) {
Do we require separate functions if we have only two conditions to check?

2024-08-22 04:44 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/hook_raw_bidder_response.go
> +		}(*bid)
`Unwrap` function internally changes the `bid.AdM` after successful VAST unwrap.
In the hook, it is recommeded to change the bid/bidRequest/bidResponse only in the mutation. 
Hence, we are intentionally passing the copy of bid object to `unwrap` function to avoid the race condition.

2024-08-22 04:49 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/hook_raw_bidder_response.go
> +	unwrappedBidsChan := make(chan bidInfo, len(payload.Bids))
It is not mandatory to close the channel, they will automatically get garbage collected. 
I'll have to introduce waitGroup only for closing the channel, which I am avoiding here.

Reference -  `requestBid` function from bidder.go (prebid-server).

2024-08-22 04:52 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/hook_raw_bidder_response.go
> +		if rejectBid(unwrappedBid.unwrapStatus) {
I added this function just for readability purpose.
The go-compiler itself is inlining this function call during build.
Verified using command - `go build -gcflags='-m' ./modules/pubmatic/openwrap/... >&  xyz.txt`

```
modules/pubmatic/openwrap/hook_raw_bidder_response.go:53:15: inlining call to rejectBid
```

2024-08-22 05:04 UTC, pm-nikhil-vaidya commented on modules/pubmatic/openwrap/hook_raw_bidder_response.go
> +	unwrappedBidsChan := make(chan bidInfo, len(payload.Bids))
Even if its not mandatory, its a best practise to close channel after use

2024-08-22 05:08 UTC, pm-nikhil-vaidya commented on modules/pubmatic/openwrap/hook_raw_bidder_response.go
> +		}(*bid)
Why Unwrap is changing the adm? is it expected. This fuctionality will check if adm is valid or not right?

2024-08-22 05:15 UTC, pm-nikhil-vaidya commented on modules/pubmatic/openwrap/hook_raw_bidder_response.go
> +	unwrappedBidsChan := make(chan bidInfo, len(payload.Bids))
We don't require waitgroup. Simply `close()` will do the job

2024-08-22 05:16 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/hook_raw_bidder_response.go
> +		}(*bid)
Yes, its existing function which replaces the the AdM (wrapped VAST) with unwrapped-VAST when it successfully able to unwrap the VAST.

2024-08-22 05:24 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/hook_raw_bidder_response.go
> +	unwrappedBidsChan := make(chan bidInfo, len(payload.Bids))
Agree, but based on below article I dont see any need to close the channel. 
(Here, we are not using for-loop on the channel. )

Refer - https://go.dev/tour/concurrency/4 

```
Channels aren't like files; you don't usually need to close them. Closing is only necessary when the receiver must be told there are no more values coming, such as to terminate a range loop.
```

2024-08-22 05:40 UTC, pm-nikhil-vaidya commented on modules/pubmatic/openwrap/hook_raw_bidder_response.go
> +		if rejectBid(unwrappedBid.unwrapStatus) {
A function call adds a stack call runtime. What command you mentioned its a data on compile time not runtime.
Its not major one but its a nice todo :)

2024-08-22 06:52 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/hook_raw_bidder_response.go
> +		if rejectBid(unwrappedBid.unwrapStatus) {
The compiler replaces the function call with its actual code at compile time so it will not add a stack call in runtime.
Anyway, I've removed the function , please check latest code

2024-08-27 05:08 UTC, pm-jaydeep-mohite commented on modules/pubmatic/openwrap/hook_raw_bidder_response.go
> +	return bid != nil && bid.Bid != nil && bid.Bid.AdM != "" && bid.BidType == openrtb_ext.BidTypeVideo
check can be updates as 

`bid != nil &&  bid.BidType == openrtb_ext.BidTypeVideo && bid.Bid != nil && bid.Bid.AdM != "" `

2024-08-27 07:52 UTC, pm-nikhil-vaidya approved these changes

2024-08-27 08:47 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/hook_raw_bidder_response.go
> +	return bid != nil && bid.Bid != nil && bid.Bid.AdM != "" && bid.BidType == openrtb_ext.BidTypeVideo
done

2024-08-27 09:52 UTC, pm-jaydeep-mohite submitted a review, later dismissed
LGTM

2024-08-27 09:52 UTC, pm-jaydeep-mohite commented on hooks/hookexecution/executor.go
>  	executionCtx := e.newContext(stageName)
Do we need to contribute this change in prebid server open source ?

2024-08-30 11:24 UTC, pm-viral-vala approved these changes

2024-08-31 14:06 UTC, ashishshinde-pubm commented on modules/pubmatic/openwrap/hook_raw_bidder_response.go
> +		}
ok

2024-08-31 14:06 UTC, ashishshinde-pubm commented on analytics/pubmatic/logger.go
> +
ok

2024-09-02 03:27 UTC, ashishshinde-pubm commented on hooks/hookexecution/executor.go
>  	executionCtx := e.newContext(stageName)
Opened the PR - 3882 on open-source prebid-server

2024-09-02 04:37 UTC, Pubmatic-Supriya-Patil approved these changes
LGTM

2024-09-02 05:47 UTC, pm-jaydeep-mohite commented on analytics/pubmatic/logger.go
> +func GetBidPriceAfterCurrencyConversion(price float64, requestCurrencies []string, responseCurrency string,
Can we make in private ?

2024-09-02 05:49 UTC, pm-jaydeep-mohite commented on analytics/pubmatic/logger.go
> +func GetBidPriceAfterCurrencyConversion(price float64, requestCurrencies []string, responseCurrency string,
This function is used in header-bidding

2024-09-02 05:49 UTC, pm-jaydeep-mohite approved these changes
LGTM

2024-09-02 05:49 UTC, ashishshinde-pubm commented on analytics/pubmatic/logger.go
> +func GetBidPriceAfterCurrencyConversion(price float64, requestCurrencies []string, responseCurrency string,
function is getting used in header-bidding so can't make it private

2024-09-02 05:49 UTC, merged