UOE-11092: Support for the imp_counting_method(1px) feature for bidders.
PubMatic-OpenWrap/prebid-server pull request #903
Opened 2024-09-11 10:04 UTC by AvinashKapre

2024-09-11 11:42 UTC, Pubmatic-Dhruv-Sonone requested changes

2024-09-11 11:42 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/publisherfeature/impcountingmethod.go
> +func (fe *feature) GetImpCountingMethodEnabledBidders() map[string]struct{} {
Can we rewrite this as below?
```
func (fe *feature) GetImpCountingMethodEnabledBidders() map[string]struct{} {
    fe.RLock()
    defer fe.RUnlock()
    
    enabledBidders := make(map[string]struct{}, len(fe.impCountingMethod.enabledBidders))
    for bidder := range fe.impCountingMethod.enabledBidders {
        enabledBidders[bidder] = struct{}{}
    }
    return enabledBidders
}
```

2024-09-11 11:42 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/publisherfeature/impcountingmethod_test.go
> +func TestFeature_updateImpCountingMethodEnabledBidders(t *testing.T) {
Nitpick: `TestFeatureUpdateImpCountingMethodEnabledBidders`

2024-09-11 11:42 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/tracker/inject.go
>  			var errMsg string
Nitpick: use var block
```
var (
    errMsg string
    err error
    impCountingMethodEnabled bool
)
```

2024-09-11 11:42 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/publisherfeature/impcountingmethod_test.go
> +func TestFeature_GetImpCountingMethodEnabledBidders(t *testing.T) {
Nitpick:  `TestFeatureGetImpCountingMethodEnabledBidders`

2024-09-11 11:42 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/publisherfeature/impcountingmethod_test.go
> +	}{
Add ut for following
1. Feature is disabled.
2. Invalid value.

2024-09-12 04:44 UTC, Pubmatic-Dhruv-Sonone submitted a review, later dismissed

2024-09-12 09:43 UTC, pm-saurabh-narkhede commented on modules/pubmatic/openwrap/publisherfeature/reloader.go
> +	fe.updateImpCountingMethodEnabledBidders()
Can we have one test case for `updateFeatureConfigMaps`  with `updateImpCountingMethodEnabledBidders` in `Test_feature_updateFeatureConfigMaps`?

2024-09-12 12:48 UTC, pm-saurabh-narkhede submitted a review, later dismissed

2024-09-19 13:02 UTC, pm-viral-vala requested changes

2024-09-19 13:02 UTC, pm-viral-vala commented on modules/pubmatic/openwrap/tracker/inject.go
> +				}
Can we check tracker.IsOMEnabled flag instead of returning boolean flag?

2024-09-19 13:06 UTC, pm-viral-vala requested changes

2024-09-19 13:06 UTC, pm-viral-vala commented on modules/pubmatic/openwrap/publisherfeature/impcountingmethod_test.go
> +				},
Can we have test case if both are already set and after execution of the update function on one index got updated with the latest data? Currently in all test cases expected is initialized with empty data.

2024-09-19 13:06 UTC, pm-viral-vala commented on modules/pubmatic/openwrap/publisherfeature/impcountingmethod_test.go
> +			name: "get imp counting method enabled bidders when index is 0",
Please update all testcases name with underscore instead of spaces.

2024-12-12 10:13 UTC, closed without merging