UOE-11098: Pass user.ext.sessionduration and user.ext.impdepth ORTB request to OW partners
PubMatic-OpenWrap/prebid-server pull request #922
Opened 2024-09-27 05:24 UTC by Pubmatic-Supriya-Patil

# Description

Please add change description or link to ticket, docs, etc.

# Checklist:

- [ ] PR commit list is unique (rebase/pull with the origin branch to keep master clean).
- [ ] JIRA number is added in the PR title and the commit message.
- [ ] Updated the `header-bidding` repo with appropiate commit id.
- [ ] Documented the new changes.

For Prebid upgrade, refer: https://inside.pubmatic.com:8443/confluence/display/Products/Prebid-server+upgrade

2024-10-03 04:27 UTC, pm-viral-vala commented on modules/pubmatic/openwrap/endpoints/legacy/ctv/parser_implementation.go
> +	}
@Pubmatic-Dhruv-Sonone, Please note that instead of unmarshal and marshal for every extension field, can we have a list of extension parameters inside the OpenRTB struct and update those at the end? 
eg: 
```
type OpenRTB struct {
  ext struct {
    user map[string]any
  }
}
func (o *OpenRTB) ORTBUserExtImpDepth() (err error) {
 // .... add all nil checks
 o.ext.user["key"] = value
}
o.Parse()
o.UpdateExtension()
func (o *OpenRTB) UpdateExtension() {
  if len(o.ext.user)>0 {
   o.request.user.ext,_ = marshal(o.ext.user)
  }
}
```

2024-10-03 04:27 UTC, pm-viral-vala submitted a review, later dismissed

2024-10-03 05:17 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/endpoints/legacy/ctv/parser_implementation.go
> +	}
@pm-viral-vala Makes sense. Will try refactoring this code in ctv modules migration changes.

2024-10-03 05:17 UTC, Pubmatic-Dhruv-Sonone submitted a review, later dismissed

2024-10-07 05:59 UTC, AvinashKapre requested changes

2024-10-07 05:59 UTC, AvinashKapre commented on modules/pubmatic/openwrap/endpoints/legacy/ctv/util.go
> +			logger.Warn("Invalid sessionduration value: %v. Only positive values are allowed.", userExt.SessionDuration)
We are not using go-common logger in the module, can you please use glog for the same.

2024-10-07 05:59 UTC, AvinashKapre commented on modules/pubmatic/openwrap/endpoints/legacy/ctv/util.go
> +			logger.Warn("Invalid impdepth value: %v. Only positive values are allowed.", userExt.ImpDepth)
We are not using go-common logger in the module, can you please use glog for the same.

2024-10-07 09:27 UTC, AvinashKapre approved these changes
LGTM

2024-10-08 09:09 UTC, AvinashKapre approved these changes

2024-10-09 09:19 UTC, pm-viral-vala approved these changes

2024-10-09 09:25 UTC, merged