U0E-10990: Return error when a partial read of any DB Query.
PubMatic-OpenWrap/prebid-server pull request #932
Opened 2024-10-04 11:26 UTC by pm-priyanka-bagade

2024-10-07 06:37 UTC, AvinashKapre commented on modules/pubmatic/openwrap/database/mysql/app_integration_path.go
> +	}
@pm-viral-vala , Do we need the stat as well for this scinarios at application layer, I think we do have stats in place just need to return error?

2024-10-10 08:04 UTC, pm-priyanka-bagade commented on modules/pubmatic/openwrap/database/mysql/app_integration_path.go
> +	}
Discussed with @AvinashKapre 
No need to add stats, as we have stats already in place RecordDBQueryFailure

2024-10-10 08:07 UTC, pm-priyanka-bagade commented on modules/pubmatic/openwrap/database/mysql/app_sub_integration_path.go
> +
Done 
[PartialQueryFailure] [QueryName] %v, err

2024-10-11 06:23 UTC, Pubmatic-Dhruv-Sonone requested changes

2024-10-11 06:23 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/cache/gocache/adunit_config.go
> +		glog.Errorf("[PartialQueryFailure] for adunitConfigQuery with err: %v", err)
Should we keep this log at db layer instead of cache layer, We can't identify here if the error is because of row scan or query failure?

2024-10-11 06:23 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/database/mysql/app_sub_integration_path.go
> +	if err = rows.Err(); err != nil {
Can we add UT for row scan error scenario?

2024-10-11 06:35 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/cache/gocache/app_integration_path.go
> +		glog.Errorf("[PartialQueryFailure] for AppIntegrationPathMapQuery with err: %v", err)
You can create a constant for error string, if the log message is consistent and being frequently used.

2024-10-22 11:12 UTC, pm-priyanka-bagade commented on modules/pubmatic/openwrap/cache/gocache/adunit_config.go
> +		glog.Errorf("[PartialQueryFailure] for adunitConfigQuery with err: %v", err)
we should log at cache layer or else we need to log 2 times for 
1 - fetch timeout 
2 - query scan fail

2024-10-22 11:12 UTC, pm-priyanka-bagade commented on modules/pubmatic/openwrap/database/mysql/app_sub_integration_path.go
> +	if err = rows.Err(); err != nil {
done

2024-11-06 10:10 UTC, pm-priyanka-bagade commented on modules/pubmatic/openwrap/cache/gocache/slot_mappings.go
> +		glog.Errorf("[QueryFailure] for GetSlotNameHash with err: %v", err)
Done

2024-11-06 12:45 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/models/constants.go
> +	DBQueryFailure = `"[DBError] query:[%s] pubid:[%v] profileid:[%v] error:[%s]"`
Create new constant block for Error message Template.

2024-11-06 12:47 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/cache/gocache/adunit_config.go
> +		glog.Errorf(models.DBQueryFailure, "adunitConfigQuery", pubID, profileID, err)
Use constant available in constant.go for query names.
`glog.Errorf(models.DBQueryFailure, models.AdunitConfigQuery, pubID, profileID, err)`

2024-11-06 12:47 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/cache/gocache/adunit_config.go
> +		glog.Errorf(models.DBQueryFailure, "adunitConfigQuery", pubID, profileID, err)
Use constant available in constant.go for query names.
`glog.Errorf(models.DBQueryFailure, models.AdunitConfigQuery, pubID, profileID, err)`

2024-11-06 12:53 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/cache/gocache/app_integration_path.go
> +		glog.Errorf("DBQueryFailure", err)
The log format is incorrect, a format specifier is required here.
Can we just use the template here and pass empty values for `pubID` and `profileID`?

2024-11-06 12:55 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/database/mysql/adpod_config.go
> +		return nil, err
Add unit test for this function as well.

2024-11-06 13:05 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/models/constants.go
> +	DBQueryFailure = `"[DBError] query:[%s] pubid:[%v] profileid:[%v] error:[%s]"`
Nitpick: `ErrDBQueryFailed ="[DBError] query:[%s] pubid:[%v] profileid:[%v] error:[%s]"`

2024-11-07 01:59 UTC, pm-viral-vala requested changes

2024-11-07 01:59 UTC, pm-viral-vala commented on modules/pubmatic/openwrap/models/constants.go
> +	DBQueryFailure = `"[DBError] query:[%s] pubid:[%v] profileid:[%v] error:[%s]"`
Can we keep ErrDBQueryFailed constant with other error constants?

2024-11-07 08:19 UTC, pm-priyanka-bagade commented on modules/pubmatic/openwrap/cache/gocache/app_integration_path.go
> +		glog.Errorf("DBQueryFailure", err)
Done

2024-11-07 08:30 UTC, pm-priyanka-bagade commented on modules/pubmatic/openwrap/cache/gocache/adunit_config.go
> +		glog.Errorf(models.DBQueryFailure, "adunitConfigQuery", pubID, profileID, err)
Done

2024-11-07 08:50 UTC, pm-priyanka-bagade commented on modules/pubmatic/openwrap/database/mysql/adpod_config.go
> +		return nil, err
Done

2024-11-07 10:44 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/cache/gocache/adpod_config.go
> +		glog.Errorf(models.ErrDBQueryFailed, models.LiveVersionInnerQuery+"/"+models.DisplayVersionInnerQuery, pubID, profileID, err)
Incorrect Query Name in log.
`glog.Errorf(models.ErrDBQueryFailed, models.GetAdpodConfig, pubID, profileID, err)`

2024-11-07 10:52 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/models/constants.go
> +	LiveVersionInnerQuery              = "LiveVersionInnerQuery"
Keeps this commented or remove it as its not being used.

2024-11-08 12:34 UTC, pm-priyanka-bagade commented on modules/pubmatic/openwrap/cache/gocache/adpod_config.go
> +		glog.Errorf(models.ErrDBQueryFailed, models.LiveVersionInnerQuery+"/"+models.DisplayVersionInnerQuery, pubID, profileID, err)
Done

2024-11-08 12:34 UTC, pm-priyanka-bagade commented on modules/pubmatic/openwrap/models/constants.go
> +	LiveVersionInnerQuery              = "LiveVersionInnerQuery"
Done

2024-11-19 11:09 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/database/mysql/adpod_config.go
> +			return nil, fmt.Errorf("Unmarshal Error: %w", err)
Error wrap should provide Query name context
`fmt.Errorf("GetAdpodConfigQuery Failure Error: %w", err)`

2024-11-19 11:09 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/database/mysql/adpod_config.go
> +		return nil, fmt.Errorf("Row scan Failure Error: %w", err)
Error wrap should provide Query name context
fmt.Errorf("GetAdpodConfigQuery Failure Error: %w", err)

2024-11-19 11:14 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/database/mysql/adpod_config.go
Can we create a private function for `getAdpodConfig` and then wrap the error from that function?

2024-11-19 11:19 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/database/mysql/partner_config.go
> +	return partnerConfigMap, fmt.Errorf("GetParterConfigQuery Failure Error: %w", err)
Error should be in else block.

2024-11-19 11:41 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/database/mysql/adpod_config_test.go
> +		},
Can we add assertion on error?

2024-11-19 11:50 UTC, pm-priyanka-bagade commented on modules/pubmatic/openwrap/cache/gocache/partner_config.go
> +			glog.Errorf("No rows found for partner config query for pubID %d, profileID %d: %v", pubID, profileID, err)
done

2024-11-19 12:01 UTC, pm-priyanka-bagade commented on modules/pubmatic/openwrap/database/mysql/adpod_config.go
> +			return nil, fmt.Errorf("Unmarshal Error: %w", err)
done

2024-11-19 12:01 UTC, pm-priyanka-bagade commented on modules/pubmatic/openwrap/database/mysql/adpod_config.go
> +		return nil, fmt.Errorf("Row scan Failure Error: %w", err)
done

2024-11-19 12:02 UTC, pm-priyanka-bagade commented on modules/pubmatic/openwrap/database/mysql/adpod_config.go
done

2024-11-19 12:06 UTC, pm-priyanka-bagade commented on modules/pubmatic/openwrap/database/mysql/partner_config.go
> +	return partnerConfigMap, fmt.Errorf("GetParterConfigQuery Failure Error: %w", err)
done

2024-11-20 09:34 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/cache/gocache/slot_mappings.go
> +	}
Don't return error from here.

2024-11-20 09:43 UTC, Pubmatic-Dhruv-Sonone requested changes

2024-11-20 09:43 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/cache/gocache/slot_mappings.go
> +		return err
Don't return error from here.

2024-11-25 05:31 UTC, pm-viral-vala requested changes

2024-11-25 05:31 UTC, pm-viral-vala commented on modules/pubmatic/openwrap/beforevalidationhook.go
> +		glog.Errorf("getProfileData error %s with Invalid pubid: %v profile id: %v version id : %v combination", err, rCtx.PubID, rCtx.ProfileID, rCtx.DisplayVersionID)
please rename the message with
`glog.Errorf("status:[invalid_profile_data] pubid:[%v] profileid:[%v] versionid:[%v] error:[%v]", rCtx.PubID, rCtx.ProfileID, rCtx.DisplayVersionID, err)`

2024-11-25 05:31 UTC, pm-viral-vala commented on modules/pubmatic/openwrap/cache/gocache/adpod_config.go
> +		glog.Errorf(models.ErrDBQueryFailed, models.GetAdpodConfig, pubID, profileID, err)
GetAdpodConfig reads version details from DB, Please add similar changes here which we did for PartnerConfigMap

2024-11-25 05:31 UTC, pm-viral-vala commented on modules/pubmatic/openwrap/database/mysql/adpod_config.go
> +		return nil, fmt.Errorf("LiveVersionInnerQuery/DisplayVersionInnerQuery Failure Error: %w", err)
Do we need to wrap error?

2024-11-25 05:31 UTC, pm-viral-vala commented on modules/pubmatic/openwrap/database/mysql/adpod_config.go
> +	}
Do we need to wrap error?

2024-11-25 05:31 UTC, pm-viral-vala commented on modules/pubmatic/openwrap/database/mysql/partner_config.go
> +		return nil, fmt.Errorf("LiveVersionInnerQuery/DisplayVersionInnerQuery Failure Error: %w", err)
Do we need to wrap up the error?

2024-11-25 05:31 UTC, pm-viral-vala commented on modules/pubmatic/openwrap/database/mysql/partner_config.go
> +		return partnerConfigMap, fmt.Errorf("GetParterConfigQuery Failure Error: %w", err)
Do we need to wrap the error?

2024-11-25 05:57 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/cache/gocache/slot_mappings.go
> +		glog.Errorf(models.ErrDBQueryFailed, models.WrapperSlotMappingsQuery+"/"+models.WrapperLiveVersionSlotMappings, pubID, profileID, err)
Can we remove this log, its already being logged in `getActivePartnerConfigAndPopulateWrapperMappings` after calling `populateCacheWithWrapperSlotMappings`?

2024-11-25 06:01 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/cache/gocache/adunit_config.go
> +		glog.Errorf(models.ErrDBQueryFailed, models.AdunitConfigQuery, pubID, profileID, err)
Can we remove this log, its already being logged in `getActivePartnerConfigAndPopulateWrapperMappings`?

2024-11-25 06:11 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/beforevalidationhook_test.go
>  					Errors:  []string{"failed to get profile data: received empty data"},
The `Errors: []string{"failed to get profile data: received empty data"}` update needs to be reflected according to the changes in the `handleBeforeValidationHook`. Currently, the unit tests are not failing because we aren't asserting the hookResult.Errors

2024-11-25 06:50 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/beforevalidationhook.go
> +		glog.Errorf("getProfileData error %s with Invalid pubid: %v profile id: %v version id : %v combination", err, rCtx.PubID, rCtx.ProfileID, rCtx.DisplayVersionID)
We can remove the log stats. 
Return a generic error message` errors.New("invalid profile data")`

2024-11-25 13:55 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/cache/gocache/adpod_config.go
> +		if errors.Is(err, sql.ErrNoRows) {
Can you add stat for `GetAdpodConfig` as well?
```
		if errors.Is(err, sql.ErrNoRows) {
			c.metricEngine.RecordDBQueryFailure(models.LiveVersionInnerQuery, strconv.Itoa(pubID), strconv.Itoa(profileID))
		} else {
			c.metricEngine.RecordDBQueryFailure(models.GetAdpodConfig, strconv.Itoa(pubID), strconv.Itoa(profileID))
		}
```

2024-11-25 14:05 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/cache/gocache/adpod_config.go
> +			c.cache.Set(cacheKey, adpodConfig, getSeconds(c.cfg.CacheDefaultExpiry))
@pm-viral-vala 
I don't think we should cache empty or nil values in case of a failure, as an empty or nil value is considered a valid ad pod configuration. The request will only return an `InvalidAdpodConfiguration` error if there is a query failure, not because of an empty value.

The behavior here is different from the `PartnerConfig` query. If the goal is to avoid multiple database calls in the event of a query failure by caching an empty value, this would require changes at the cache layer to return an error when nil data is cached.

What are your thoughts?

2024-11-26 06:07 UTC, Pubmatic-Dhruv-Sonone approved these changes

2024-11-26 11:34 UTC, pm-viral-vala commented on modules/pubmatic/openwrap/cache/gocache/adpod_config.go
> +			c.cache.Set(cacheKey, adpodConfig, getSeconds(c.cfg.CacheDefaultExpiry))
I think we should directly read pubID, profileID, displayVersion, and versionID which were read from partnerconfig query instead of re-query for version details here.

Let's see if that's easy to do in the same PR then good, otherwise create a separate ticket.

2024-11-27 08:52 UTC, merged