UOE-11322: Forward displaymanager and displaymanagerver from app extension to pubmatic ssp
PubMatic-OpenWrap/prebid-server pull request #935
Opened 2024-10-08 09:49 UTC by AvinashKapre

2024-10-09 11:36 UTC, Pubmatic-Dhruv-Sonone requested changes

2024-10-09 11:36 UTC, Pubmatic-Dhruv-Sonone commented on adapters/pubmatic/pubmatic_test.go
> +			assert.Equal(t, tt.want.displayManager, tt.args.imp.DisplayManager)
Can we add following assertion?
`assert.Equal(t, tt.want.displayManagerVer, tt.args.imp.DisplayManagerVer)`

2024-10-09 11:48 UTC, pm-isha-bharti commented on adapters/pubmatic/pubmatic.go
> +	if source, err := jsonparser.GetString(req.App.Ext, openrtb_ext.PrebidExtKey, "source"); err == nil {
Add empty source and version check also.

2024-10-09 11:53 UTC, pm-isha-bharti commented on adapters/pubmatic/pubmatic.go
> +	if req.App == nil {
Return if app.ext not present or empty

2024-10-10 04:59 UTC, pm-jaydeep-mohite commented on adapters/pubmatic/pubmatic.go
> +	displayManager, displayManagerVer := getDisplayManagerAndVer(request)
Can we check App and App.Ext not nil  before calling this function 


         
    var displayManager, displayManagerVer string
	if request.App != nil && request.App.Ext != nil {
		displayManager, displayManagerVer = getDisplayManagerAndVer(request)
	}

2024-10-10 05:01 UTC, pm-jaydeep-mohite commented on adapters/pubmatic/pubmatic.go
> +		wrapperExtFromImp, pubIDFromImp, floors, err := parseImpressionObject(&request.Imp[i], extractWrapperExtFromImp, extractPubIDFromImp, displayManager, displayManagerVer)
Do we really need to pass displayManager, displayManagerVer in this function ? 

Instead can we  have below assignment here ? 




```go
	// Populate imp.displaymanager and imp.displaymanagerver if the SDK failed to do it.
	if imp.DisplayManager == "" && imp.DisplayManagerVer == "" && displayManager != "" && displayManagerVer != "" {
		imp.DisplayManager = displayManager
		imp.DisplayManagerVer = displayManagerVer
	}
```

2024-10-10 05:02 UTC, Pubmatic-Dhruv-Sonone commented on adapters/pubmatic/pubmatic.go
> +func getDisplayManagerAndVer(req *openrtb2.BidRequest) (string, string) {
Pass only request.App object instead of passing the entire request.

2024-10-10 05:19 UTC, AvinashKapre commented on adapters/pubmatic/pubmatic.go
> +		wrapperExtFromImp, pubIDFromImp, floors, err := parseImpressionObject(&request.Imp[i], extractWrapperExtFromImp, extractPubIDFromImp, displayManager, displayManagerVer)
// parseImpressionObject parse the imp to get it ready to send to pubmatic
kept it there so that we can have everything related to imp in a single function

2024-10-10 06:51 UTC, Pubmatic-Dhruv-Sonone approved these changes

2024-10-10 06:58 UTC, pm-isha-bharti approved these changes

2024-10-10 07:33 UTC, merged