UOE-11339: Bug fix- Default Bid is not getting formed for Prebid S2S
PubMatic-OpenWrap/prebid-server pull request #941
Opened 2024-10-14 10:24 UTC by AvinashKapre

2024-10-15 10:36 UTC, pm-viral-vala submitted a review, later dismissed

2024-10-15 10:42 UTC, pm-isha-bharti commented on modules/pubmatic/openwrap/defaultbids.go
> +	if rctx.Endpoint == models.EndpointWebS2S {
Can we add UTs for Web S2S endpoint?

2024-10-15 10:50 UTC, pm-isha-bharti commented on modules/pubmatic/openwrap/defaultbids.go
> +	if rctx.Endpoint == models.EndpointWebS2S {
If possible can we have test cases in the logger flow as well for the Endpoint Web s2s for the default bids?

2024-10-15 16:17 UTC, Pubmatic-Dhruv-Sonone requested changes

2024-10-15 16:17 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/nonbids_test.go
> +			)
Can you check if you can use below code here instead of using this library?
`assert.ElementsMatch(t, gotSetaNonBid, tt.wantSeatNonBid)`

2024-10-15 17:50 UTC, AvinashKapre commented on modules/pubmatic/openwrap/nonbids_test.go
> +			)
No, this can not be used, here we have a slice inside a slice, and the order of which can not be guaranteed.

2024-10-16 06:33 UTC, ShriprasadM commented on modules/pubmatic/openwrap/defaultbids.go
> +	//Do not add nobids in default bids for throttled adapter and non-mapped bidders in case of web-s2s
@AvinashKapre : is it irrelevant of throttling percentage? For example, if I have throttled bidder only 1% then 99% I will call that bidder. in that case if bidder not responds with bids then are we not going to add nobids?

2024-10-16 06:33 UTC, ShriprasadM commented on modules/pubmatic/openwrap/nonbids.go
> +	for impID, noSeatBid := range rctx.DefaultBids {
@AvinashKapre :  rename `noSeatBid` to `defaultBid`.  Let us keep variable context consistent.

2024-10-16 08:33 UTC, Pubmatic-Dhruv-Sonone approved these changes

2024-10-16 08:41 UTC, pm-isha-bharti approved these changes

2024-10-16 08:43 UTC, merged