UOE-11360: Use sessionduration and impdepth from signal only, ignore if present in request user extension
PubMatic-OpenWrap/prebid-server pull request #947
Opened 2024-10-17 07:09 UTC by Pubmatic-Supriya-Patil

UOE-11360: Use sessionduration and impdepth from signal only, ignore if present in request user extension

2024-10-17 10:51 UTC, Pubmatic-Dhruv-Sonone requested changes

2024-10-17 10:51 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/applovinmax.go
> +				}
Can we move this check to top of this function?

2024-10-17 10:51 UTC, Pubmatic-Dhruv-Sonone submitted a review, later dismissed

2024-10-23 10:39 UTC, AvinashKapre commented on modules/pubmatic/openwrap/applovinmax.go
> +				}
can we move this check to line no 192

2024-10-23 11:54 UTC, AvinashKapre submitted a review, later dismissed

2024-10-24 06:15 UTC, pm-viral-vala requested changes

2024-10-24 06:15 UTC, pm-viral-vala commented on modules/pubmatic/openwrap/applovinmax.go
> +				maxRequest.User.Ext, _ = jsonparser.Set(maxRequest.User.Ext, field, key)
What if an error occurs, this will make the User.Ext empty string, Please check error and if there is no error then only update user.ext

2024-10-25 07:04 UTC, AvinashKapre approved these changes

2024-10-25 07:15 UTC, Pubmatic-Dhruv-Sonone approved these changes

2024-10-25 07:30 UTC, pm-viral-vala approved these changes

2024-10-25 07:31 UTC, merged