OTT-58: Added empty function getBidDuration. Added unit tests  around it
PubMatic-OpenWrap/prebid-server pull request #95
Opened 2020-12-18 11:58 UTC by ShriprasadM

2020-12-22 12:02 UTC, ShriprasadM commented on adapters/tagbidder/vast_tag_response_handler.go
> +		BidVideo: &openrtb_ext.ExtBidPrebidVideo{},
Initialize with `openrtb_ext.ExtBidPrebidVideo` to allow storing `duration`

2020-12-22 12:07 UTC, ShriprasadM commented on adapters/tagbidder/vast_tag_response_handler.go
> +		}
1. Iterates over each creative provided in the VAST
2. Converting from `float64` to `int`. Because Prebid Server expects video duration in `int`
> if d = "0:0:30.5"  => 30 seconds and 5 milliseconds
   `getDuration` will return `30.005` seconds
   But, `typedBid.BidVideo.Duration` will be set to `30` seconds (0.005 seconds will be dropped)
3. Errors are ignored. If `getDuration` failed then `dur` will be `0.0`. Hence, `typedBid.BidVideo.Duration` will be `0`

2020-12-22 12:08 UTC, ShriprasadM commented on adapters/tagbidder/vast_tag_response_handler.go
> +	node := creative.FindElement("./Linear/Duration")
1. Always looks for `Creative` with `Linear` type.
2. If any other type is present, an error will be returned as `Invalid Duration`

2020-12-22 12:08 UTC, ShriprasadM commented on adapters/tagbidder/vast_tag_response_handler.go
> +	}
1. Always looks for `Creative` with `Linear` type.
2. If any other type is present, an error will be returned as `Invalid Duration`

2020-12-22 12:27 UTC, ShriprasadM commented on adapters/tagbidder/vast_tag_response_handler.go
> +	pattern := `^([01]?\d|2[0-3]):([0-5]?\d):([0-5]?\d)(\.(\d+))?$`
Regular Expressions works as follows

1. `^` start with
2. `([01]?\d|2[0-3])` - Expect hours value ranging from 0 to 23 (Mandatory)
3. `:` - Separated by `:`
4. `([0-5]?\d)` - Expect minutes value ranging from 0 to 59 (Mandatory)
5. `:` - Separated by `:`
6. `([0-5]?\d)` - Expect seconds value ranging from 0-59 (Mandatory)
7. `(\.(\d+))?` - Expect Milliseconds value prefixed with dot (.) (Optional)

2020-12-22 12:29 UTC, ShriprasadM commented on adapters/tagbidder/vast_tag_response_handler.go
> +	}
1. Check if `milliseconds` are present in the matcher. If present the append `${5}ms`
2. `repl` is the string compatible with `time.ParseDuration`. e.g. `0h0m45s5ms`

2020-12-22 12:31 UTC, ShriprasadM commented on adapters/tagbidder/vast_tag_response_handler.go
> +	dur, err := time.ParseDuration(duration)
1. `re.ReplaceAllString` will convert `duration` value into `time.ParseDuration` by expanding the duration value with `h`, `m`, `s` and `ms` as applicable
2.`time.ParseDuration` will finally parse the input duration which will return `Duration` object

2020-12-22 12:32 UTC, ShriprasadM commented on adapters/tagbidder/vast_tag_response_handler.go
> +	return dur.Seconds(), err
1. Function will return `duration in seconds` which will also contain `milliseconds` converted to `seconds`
2. For Example, if the input is `0:0:45.5` then this function will return `45.005 seconds`

2020-12-22 12:38 UTC, ShriprasadM commented on adapters/tagbidder/vast_tag_response_handler_test.go
> +							BidVideo: &openrtb_ext.ExtBidPrebidVideo{},
1. Fix for test failure
2. In actual implementation `BidVideo` is not initialized with `openrtb_ext.ExtBidPrebidVideo{}`. Hence this is required here

2020-12-22 12:40 UTC, ShriprasadM commented on adapters/tagbidder/vast_tag_response_handler_test.go
> +		{name: "duration = a:b:c.d (no numbers)", want: want{err: errors.New("Invalid Duration")}, args: args{creativeTag: `<Creative sequence="1"> <Linear> <Duration>a:b:c.d</Duration> </Linear> </Creativ
Vast File Duration validation checks

2020-12-22 12:40 UTC, ShriprasadM commented on adapters/tagbidder/vast_tag_response_handler_test.go
> +		{name: "Multiple Linear Ads within Creative", want: want{duration: 25, durationInt: 25}, args: args{creativeTag: `<Creative><Linear><Duration>0:0:25<Duration></Linear><Linear><Duration>0:0:30<Durat
A vast tag containing a creative tag with multiple linear tags

2020-12-22 12:40 UTC, ShriprasadM commented on adapters/tagbidder/vast_tag_response_handler_test.go
> +		{name: "Nil Creative tag", want: want{err: errors.New("Invalid Creative")}, args: args{creativeTag: ""}},
Tag validations

2020-12-22 12:49 UTC, ShriprasadM commented on adapters/tagbidder/vast_tag_response_handler_test.go
> +			}
1.  1st assert checks if `float` duration values are computed as expected
2. 2nd assert checks if `float` is converted to `int` values are computed as expected
3. 3rd assert checks error condition. 
4. 4th assert checks, the duration is `0` when there is an error

2020-12-22 13:22 UTC, ShriprasadM commented on adapters/tagbidder/vast_tag_response_handler.go
> +	pattern := `^([01]?\d|2[0-3]):([0-5]?\d):([0-5]?\d)(\.(\d{1,3}))?$`
Regular Expressions works as follows

1. `^` start with
2. `([01]?\d|2[0-3])` - Expect hours value ranging from 0 to 23 (Mandatory)
3. `:` - Separated by `:`
4. `([0-5]?\d)` - Expect minutes value ranging from 0 to 59 (Mandatory)
5. `:` - Separated by `:`
6. `([0-5]?\d)` - Expect seconds value ranging from 0-59 (Mandatory)
7. `(\.(\d{1,3}))?` - Expect Milliseconds value between 0-999 prefixed with dot (.) (Optional)

2020-12-23 09:06 UTC, pm-viral-vala commented on adapters/tagbidder/vast_tag_response_handler.go
> +		return ""
the creative id is mandatory for a prebid response. if it is not present then we have to create a random creative id. it would be just for verification purposes.

2021-01-04 06:04 UTC, ShriprasadM commented on adapters/tagbidder/vast_tag_response_handler.go
> +		return ""
`creative.SelectAttrValue` will now accept random id generated using `getRandomID()` function. If the `id` attribute is not found then the generated random number will be returned as  creative id.

If creative tag is not present this function will return empty creative id

2021-01-04 06:05 UTC, ShriprasadM commented on adapters/tagbidder/vast_tag_response_handler.go
> +
@pm-viral-vala : duration regexp will not be compiled once and resused

2021-01-04 06:17 UTC, pm-viral-vala requested changes

2021-01-04 06:17 UTC, pm-viral-vala commented on adapters/tagbidder/vast_tag_response_handler.go
>  	bidResponse := &adapters.BidderResponse{
use random creative id if typedBid.Bid.CrID not present.

2021-01-04 06:57 UTC, ShriprasadM commented on adapters/tagbidder/vast_tag_response_handler.go
> +		return ""
Reverted changes for getCreativeID as discussed. It will now return an empty string to creative id is not present.
Instead, caller will generate the random creative id with cr as the prefix

2021-01-04 06:59 UTC, ShriprasadM commented on adapters/tagbidder/vast_tag_response_handler.go
> +		typedBid.Bid.CrID = "cr_" + getRandomID()
Addressed the required changes for  https://github.com/PubMatic-OpenWrap/prebid-server/pull/95/files#r551133656. 
Creative ID will be generated with **cr_** as prefix

2021-01-04 07:05 UTC, pm-viral-vala approved these changes

2021-01-04 07:09 UTC, merged