UOE-11215 : modify stats so that i can have better monitoring
PubMatic-OpenWrap/prebid-server pull request #952
Opened 2024-10-24 08:02 UTC by pm-priyanka-bagade

2024-10-25 10:56 UTC, pm-viral-vala requested changes

2024-10-25 10:56 UTC, pm-viral-vala commented on modules/pubmatic/openwrap/beforevalidationhook.go
> +			m.metricEngine.RecordBadRequests(rCtx.PubIDStr, rCtx.Endpoint, getPubmaticErrorCode(openrtb3.NoBidReason(result.NbrCode)))
Can we have endpoint as first argument and pubid as 2nd argument?

2024-10-25 10:56 UTC, Pubmatic-Dhruv-Sonone requested changes

2024-10-25 10:56 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/metrics/metrics.go
> +	RecordEndpointResponseSize(endpoint string, body float64)
Nitpick: Rename to` bodySizeBytes` or `bodySize`.

2024-10-25 10:56 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/entrypointhook.go
> +			m.metricEngine.RecordBadRequests(rCtx.PubIDStr, endpoint, getPubmaticErrorCode(openrtb3.NoBidReason(result.NbrCode)))
`rCtx.PubIDStr `will  be empty here in following scenarios:
1. InvalidRequestWrapperExtension
2. InvalidProfileID
3. InvalidPublisherID

Also in `DmbhServer.go`  publisherID will not be available  while logging this metric.
@AvinashKapre  Do we want still want to add PubID to this metrics?

2024-10-25 11:04 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/metrics/config/multimetrics.go
> +// RecordBidRecoveryStatus record failed parsing itune id
Nitpick:  Add relevant comment.

2024-10-25 11:12 UTC, pm-priyanka-bagade commented on modules/pubmatic/openwrap/beforevalidationhook.go
> +			m.metricEngine.RecordBadRequests(rCtx.PubIDStr, rCtx.Endpoint, getPubmaticErrorCode(openrtb3.NoBidReason(result.NbrCode)))
Done

2024-10-25 11:16 UTC, pm-priyanka-bagade commented on modules/pubmatic/openwrap/metrics/metrics.go
> +	RecordEndpointResponseSize(endpoint string, body float64)
Done

2024-10-25 11:17 UTC, pm-priyanka-bagade commented on modules/pubmatic/openwrap/entrypointhook.go
> +			m.metricEngine.RecordBadRequests(rCtx.PubIDStr, endpoint, getPubmaticErrorCode(openrtb3.NoBidReason(result.NbrCode)))
@pm-viral-vala  suggested add 0 in case if we don't have pubid

2024-10-25 11:18 UTC, pm-priyanka-bagade commented on modules/pubmatic/openwrap/metrics/config/multimetrics.go
> +// RecordBidRecoveryStatus record failed parsing itune id
Done

2024-10-30 03:13 UTC, pm-viral-vala approved these changes

2024-10-30 03:15 UTC, pm-viral-vala commented on modules/pubmatic/openwrap/entrypointhook.go
> +			m.metricEngine.RecordBadRequests(rCtx.PubIDStr, endpoint, getPubmaticErrorCode(openrtb3.NoBidReason(result.NbrCode)))
Yes, If checks are failing before pubID parsing, then we should log pubid=0, otherwise after that we can get publisher id from the request then we should log that publisher id.

2024-11-06 06:12 UTC, AvinashKapre approved these changes
LGTM

2024-11-06 06:15 UTC, merged