UOE-10971: Send correct multiBidMultiFLoor records to analytics
PubMatic-OpenWrap/prebid-server pull request #962
Opened 2024-11-17 15:21 UTC by AvinashKapre

2024-11-22 06:18 UTC, AvinashKapre commented on modules/pubmatic/openwrap/defaultbids.go
> +		if seatBid.Seat == models.BidderPubMatic || seatBid.Seat == models.BidderPubMaticSecondaryAlias {
it should work for pubmatic alias

2024-11-22 07:17 UTC, pm-jaydeep-mohite commented on adapters/pubmatic/pubmatic_ow.go
> +	requestData := []*adapters.RequestData{}
Can we add Len as we did it for errs ?

2024-11-22 07:29 UTC, pm-jaydeep-mohite commented on modules/pubmatic/openwrap/defaultbids.go
> +		NetECPM:                 0,
Do we really need this reset ?

2024-11-25 05:49 UTC, AvinashKapre commented on adapters/pubmatic/pubmatic_ow.go
> +	requestData := []*adapters.RequestData{}
Done

2024-11-25 05:53 UTC, AvinashKapre commented on modules/pubmatic/openwrap/defaultbids.go
> +		NetECPM:                 0,
Done

2024-11-25 07:48 UTC, pm-isha-bharti commented on modules/pubmatic/openwrap/defaultbids.go
> +			if bidderCode, ok := rctx.PrebidBidderCode[bidder]; ok && (bidderCode != models.BidderPubMatic && bidderCode != models.BidderPubMaticSecondaryAlias) {
Rename it to prebidBidderCode to avoid confusion

2024-11-25 08:01 UTC, pm-isha-bharti commented on modules/pubmatic/openwrap/defaultbids.go
> +	seatBidsMultiFloor := make(map[string]map[string]int, len(bidResponse.SeatBid))
Can we rename this to be more aligned with the purpose like `bidderImpBidCounts`

2024-11-25 08:06 UTC, pm-isha-bharti commented on modules/pubmatic/openwrap/defaultbids.go
> +	defaultBidFloors := make(map[string][]float64, len(bidResponse.SeatBid)) //per bidder floors for default bids
Rename `defaultbidFloors`to `bidderDefaultbidFloors`

2024-11-25 08:57 UTC, pm-isha-bharti submitted a review, later dismissed

2024-11-25 09:16 UTC, Pubmatic-Dhruv-Sonone requested changes

2024-11-25 09:16 UTC, Pubmatic-Dhruv-Sonone commented on adapters/pubmatic/pubmatic_ow.go
> +	reqBodyMap := getMapFromJSON(reqBody)
We can unmarshal body to `openrtb2.BidRequest` instead of  map.

2024-11-25 09:20 UTC, Pubmatic-Dhruv-Sonone commented on adapters/pubmatic/pubmatic_ow.go
> +	if len(updatedBidExt) > 2 {
Can we  check if `updatedBidExt != '{}'` instead of length check?

2024-11-25 09:23 UTC, pm-saurabh-narkhede commented on modules/pubmatic/openwrap/defaultbids.go
> +		return defaultBids
can we directly return `rctx.DefaultBids` and create new variable `defaultbids` below?

2024-11-25 09:29 UTC, pm-saurabh-narkhede commented on modules/pubmatic/openwrap/defaultbids.go
> +				if bid.Ext != nil {
can we avoid nesting here?
```
if bid.Ext == nil {
	continue
}

var bidExt models.BidExt
if err := json.Unmarshal(bid.Ext, &bidExt); err != nil || bidExt.MultiBidMultiFloorValue == 0 {
	continue
}

bidderExcludeFloors[seat] = append(bidderExcludeFloors[seat], bidExt.MultiBidMultiFloorValue)
```

2024-11-25 09:43 UTC, Pubmatic-Dhruv-Sonone commented on adapters/pubmatic/pubmatic_ow.go
> +	appLovinMaxImpressionPattern = "_mf.*"
`appLovinMaxImpressionPattern = "_mf.*"` Can we change the regex only to allow integers? 
`_mf\d+`

2024-11-25 09:56 UTC, pm-jaydeep-mohite reviewed
LGTM

2024-11-25 10:02 UTC, Pubmatic-Dhruv-Sonone requested changes

2024-11-25 10:11 UTC, AvinashKapre commented on modules/pubmatic/openwrap/defaultbids.go
> +		return defaultBids
We are initializing variable here itself.

2024-11-25 10:30 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/defaultbids.go
> +	bidderExcludeFloors := make(map[string][]float64, len(bidResponse.SeatBid))    //exclude floors which are already present in bidresponse
Can we change this to `map[string]map[float64]bool`? for faster checks?

2024-11-25 11:08 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/defaultbids.go
> +			if defaultBidsCount = len(adunitFloors) - bidderImpBidCounts[impID][bidder]; defaultBidsCount <= 0 {
`defaultBidsCount` We can remove this.

2024-11-25 12:16 UTC, Pubmatic-Dhruv-Sonone approved these changes

2024-11-25 12:31 UTC, pm-isha-bharti approved these changes

2024-11-25 12:32 UTC, merged