UOE-11332: validate bids as per imp.video.protocols for all the bidders
PubMatic-OpenWrap/prebid-server pull request #963
Opened 2024-11-19 09:01 UTC by Pubmatic-Supriya-Patil

# Description

Please add change description or link to ticket, docs, etc.

# Checklist:

- [ ] PR commit list is unique (rebase/pull with the origin branch to keep master clean).
- [ ] JIRA number is added in the PR title and the commit message.
- [ ] Updated the `header-bidding` repo with appropiate commit id.
- [ ] Documented the new changes.

For Prebid upgrade, refer: https://inside.pubmatic.com:8443/confluence/display/Products/Prebid-server+upgrade

2024-11-19 11:58 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/util.go
> +func UpdateImpProtocols(impProtocols []adcom1.MediaCreativeSubtype) []adcom1.MediaCreativeSubtype {
This should be a private function.

2024-11-19 11:58 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/util.go
> +	protocols := []adcom1.MediaCreativeSubtype{adcom1.CreativeVAST30, adcom1.CreativeVAST30Wrapper, adcom1.CreativeVAST40, adcom1.CreativeVAST40Wrapper}
Can we make this constant instead of creating this for each function call?

2024-11-19 12:07 UTC, Pubmatic-Dhruv-Sonone requested changes

2024-11-19 12:09 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/beforevalidationhook.go
> +		}
Can we move this inside the existing if block at line 297?

2024-11-19 14:38 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/util_test.go
> +func Test_UpdateImpProtocols(t *testing.T) {
Nitpick:
`TestUpdateImpProtocols`

2024-11-19 14:53 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/openwrap/util.go
> +func UpdateImpProtocols(impProtocols []adcom1.MediaCreativeSubtype) []adcom1.MediaCreativeSubtype {
This function is also used in header bidding, so it has been made public.

2024-11-19 15:26 UTC, Pubmatic-Dhruv-Sonone commented on exchange/exchange_ow.go
> +	return adapterBids, errs
`adapterBids` is a map with pointer values that are being updated. Do we need to return `adapterBids` from the function? Won't all the updates be reflected outside the function without returning it?

2024-11-19 15:30 UTC, Pubmatic-Dhruv-Sonone commented on exchange/exchange_ow.go
> +func filterBidsByVastVersion(adapterBids map[openrtb_ext.BidderName]*entities.PbsOrtbSeatBid, seatNonBid *openrtb_ext.NonBidCollection) (map[openrtb_ext.BidderName]*entities.PbsOrtbSeatBid, []error)
Nitpick:  `filterBidsByVastVersion(adapterBids map[openrtb_ext.BidderName]*entities.PbsOrtbSeatBid, seatNonBid *openrtb_ext.NonBidCollection) (errs []error)`

2024-11-19 15:43 UTC, Pubmatic-Dhruv-Sonone commented on exchange/exchange_ow.go
> +	return validVastVersions[vastVersionInt], matches[1]
Nitpick:` return validVastVersions[int(vastVersionFloat)], matches[1]`

2024-11-19 15:45 UTC, Pubmatic-Dhruv-Sonone commented on exchange/exchange_test.go
> +func TestFilterBidsByVastVersions(t *testing.T) {
Nitpick:  Can we rename this UT? ex: `TestHoldAuction_FilterBidsByVastVersions`

2024-11-19 15:49 UTC, Pubmatic-Dhruv-Sonone commented on exchange/exchange_ow.go
> +func updateSeatNonBidsInvalidVastVersion(seatNonBids *openrtb_ext.NonBidCollection, rejectedBids []*entities.PbsOrtbSeatBid) {
Can you add UT for this function?

2024-11-21 06:59 UTC, Pubmatic-Supriya-Patil commented on exchange/exchange_ow_test.go
> +		{
Added

2024-11-21 08:10 UTC, Pubmatic-Supriya-Patil commented on exchange/exchange_ow.go
> +func updateSeatNonBidsInvalidVastVersion(seatNonBids *openrtb_ext.NonBidCollection, rejectedBids []*entities.PbsOrtbSeatBid) {
Added

2024-11-21 08:10 UTC, Pubmatic-Supriya-Patil commented on exchange/exchange_ow.go
> +func validateVastVersion(adM string) (bool, string) {
Done

2024-11-21 08:11 UTC, Pubmatic-Supriya-Patil commented on openrtb_ext/openwrap.go
> +	StrictVastMode  bool                   `json:"strict_vast_mode,omitempty"`
Updated

2024-11-21 08:11 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/openwrap/util_test.go
> +			name: "Additional Protocols Present",
Done

2024-11-21 08:12 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/openwrap/beforevalidationhook.go
> +		}
This should be in the mutation

2024-11-21 08:12 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/openwrap/util.go
> +		if !chechIfProtocolPresent(impProtocols, protocol) {
Done

2024-11-21 08:12 UTC, Pubmatic-Supriya-Patil commented on modules/pubmatic/openwrap/util.go
> +	protocols := []adcom1.MediaCreativeSubtype{adcom1.CreativeVAST30, adcom1.CreativeVAST30Wrapper, adcom1.CreativeVAST40, adcom1.CreativeVAST40Wrapper}
Done

2024-11-21 10:11 UTC, pm-jaydeep-mohite commented on exchange/exchange_ow_test.go
> +			args: args{
Add below test cases 
1. Banner + Valid VAST version 
2. Banner + Invalid VAST Version

2024-11-21 10:29 UTC, Pubmatic-Supriya-Patil commented on exchange/exchange_ow_test.go
> +			args: args{
Done

2024-11-22 08:02 UTC, pm-jaydeep-mohite commented on exchange/exchange.go
> +			validationErrs = filterBidsByVastVersion(adapterBids, &seatNonBid)
validationErrs := filterBidsByVastVersion(adapterBids, &seatNonBid)

2024-11-22 08:03 UTC, Pubmatic-Dhruv-Sonone commented on exchange/exchange_ow.go
> +					rejectedBid = append(rejectedBid, &entities.PbsOrtbSeatBid{
The seat remains constant within this loop, and the Currency and HTTPCalls are unnecessary. Instead, we can simply use a slice of []*entities.PbsOrtbBid{} to hold the rejected bids.
```
func updateSeatNonBidsInvalidVastVersion(seatNonBids *openrtb_ext.NonBidCollection, seat string, rejectedBids []*entities.PbsOrtbBid) {
	for _, pbsRejBid := range rejectedBids {
		nonBidParams := entities.GetNonBidParamsFromPbsOrtbBid(pbsRejBid, seat)
		nonBidParams.NonBidReason = int(nbr.LossBidLostInVastVersionValidation)
		seatNonBids.AddBid(openrtb_ext.NewNonBid(nonBidParams), seat)
	}
}

func filterBidsByVastVersion(adapterBids map[openrtb_ext.BidderName]*entities.PbsOrtbSeatBid, seatNonBid *openrtb_ext.NonBidCollection) []error {
	errs := []error{}
	for _, seatBid := range adapterBids {
		rejectedBid := []*entities.PbsOrtbBid{}
		validBids := make([]*entities.PbsOrtbBid, 0, len(seatBid.Bids))
		for _, pbsBid := range seatBid.Bids {
			if pbsBid.BidType == openrtb_ext.BidTypeVideo && pbsBid.Bid.AdM != "" {
				isValid, vastVersion := validateVastVersion(pbsBid.Bid.AdM)
				if !isValid {
					errs = append(errs, &errortypes.Warning{
						Message:     fmt.Sprintf("%s Bid %s was filtered for Imp %s with Vast Version %s: Incompatible with GAM unwinding requirements", seatBid.Seat, pbsBid.Bid.ID, pbsBid.Bid.ImpID, vastVersion),
						WarningCode: errortypes.InvalidVastVersionWarningCode,
					})
					rejectedBid = append(rejectedBid, pbsBid)
					continue
				}
			}
			validBids = append(validBids, pbsBid)
		}
		updateSeatNonBidsInvalidVastVersion(seatNonBid, seatBid.Seat, rejectedBid)
		seatBid.Bids = validBids
	}
	return errs
}
```

2024-11-22 08:04 UTC, Pubmatic-Dhruv-Sonone commented on exchange/exchange_ow.go
> +	rejectedBid := []*entities.PbsOrtbSeatBid{}
`rejectedBid` should be declared inside the for loop?

2024-11-22 08:06 UTC, Pubmatic-Dhruv-Sonone commented on exchange/exchange_ow_test.go
> +			name: "valid_vast_version_banner",
Can we add UT for native?

2024-11-22 08:08 UTC, Pubmatic-Supriya-Patil commented on exchange/exchange_ow_test.go
> +			name: "valid_vast_version_banner",
Looks like we are trying to check if we are validating non video bids or not. this is already done with banner. I dont think it will change anything , works same as banner and return as it is because of video check

2024-11-22 08:10 UTC, Pubmatic-Supriya-Patil commented on exchange/exchange_ow.go
> +					rejectedBid = append(rejectedBid, &entities.PbsOrtbSeatBid{
Previously in all function we used to have PbsOrtbSeatBid and to have inline with that I used the same struct. I will update it to PbsOrtbBid

2024-11-22 08:13 UTC, Pubmatic-Supriya-Patil commented on exchange/exchange_ow.go
> +					rejectedBid = append(rejectedBid, &entities.PbsOrtbSeatBid{
I think this will also work without adding new parameter seat in function call.
rejectedBid = append(rejectedBid, &entities.PbsOrtbSeatBid{
						Seat:      seatBid.Seat,
						Bids:      []*entities.PbsOrtbBid{pbsBid},
					})

2024-11-22 08:35 UTC, Pubmatic-Dhruv-Sonone commented on exchange/exchange_ow.go
> +					rejectedBid = append(rejectedBid, &entities.PbsOrtbSeatBid{
> I think this will also work without adding new parameter seat in function call. rejectedBid = append(rejectedBid, &entities.PbsOrtbSeatBid{ Seat: seatBid.Seat, Bids: []*entities.PbsOrtbBid{pbsBid}, })

With this approach, we are creating multiple `entities.PbsOrtbSeatBid` objects for a single seat. I would prefer creating a single `entities.PbsOrtbSeatBid` and adding the `PbsOrtbBid` objects to it instead.

However, if you still prefer not to modify `updateSeatNonBidsInvalidVastVersion` and want to keep `rejectedBid` as `[]*entities.PbsOrtbSeatBid` , I suggest moving the rejectedBid initialization logic to the beginning of the function and calling `updateSeatNonBidsInvalidVastVersion` before the function exits

2024-11-22 08:39 UTC, Pubmatic-Supriya-Patil commented on exchange/exchange.go
> +			validationErrs = filterBidsByVastVersion(adapterBids, &seatNonBid)
Done

2024-11-22 08:40 UTC, Pubmatic-Supriya-Patil commented on exchange/exchange_ow.go
> +					rejectedBid = append(rejectedBid, &entities.PbsOrtbSeatBid{
Done

2024-11-22 08:42 UTC, Pubmatic-Supriya-Patil commented on exchange/exchange_ow.go
> +func filterBidsByVastVersion(adapterBids map[openrtb_ext.BidderName]*entities.PbsOrtbSeatBid, seatNonBid *openrtb_ext.NonBidCollection) (map[openrtb_ext.BidderName]*entities.PbsOrtbSeatBid, []error)
Done

2024-11-22 09:42 UTC, pm-jaydeep-mohite approved these changes
LGTM

2024-11-22 10:07 UTC, pm-viral-vala approved these changes

2024-11-22 10:07 UTC, merged