UOE-11665: Fix-panic for AppLovin Request when multi-bid-multi-floor feature is enabled and no adunit config in DB for that publisher and profile
PubMatic-OpenWrap/prebid-server pull request #977
Opened 2024-12-09 12:27 UTC by AvinashKapre

2024-12-09 13:08 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/defaultbids.go
> +		adunitFloors, ok := rctx.AppLovinMax.MultiFloorsConfig.Config[impCtx.TagID]
Can you also add `len(adunitFloors) > 0` check here?

2024-12-09 13:11 UTC, Pubmatic-Dhruv-Sonone requested changes

2024-12-09 13:11 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/defaultbids.go
> +		if !ok {
Can we change this condition to `if !ok  || len(adunitFloors) == 0 {` ?

2024-12-09 13:11 UTC, Pubmatic-Dhruv-Sonone commented on modules/pubmatic/openwrap/defaultbids_test.go
> +		{
Add UT for empty floors array

2024-12-09 13:16 UTC, AvinashKapre commented on modules/pubmatic/openwrap/defaultbids_test.go
> +		{
Done

2024-12-09 13:31 UTC, Pubmatic-Dhruv-Sonone submitted a review, later dismissed

2024-12-09 13:50 UTC, pm-jaydeep-mohite commented on analytics/pubmatic/helper.go
> +	if rctx.Endpoint != models.EndpointAppLovinMax || rctx.AppLovinMax.Reject {
Can we add check for `len(ao.Response.SeatBid[0]) > 0 && len(ao.Response.SeatBid[0].Bid[0]) > 0` at line 88 ?

2024-12-10 05:43 UTC, AvinashKapre commented on analytics/pubmatic/helper.go
> +	if rctx.Endpoint != models.EndpointAppLovinMax || rctx.AppLovinMax.Reject {
Done

2024-12-10 05:58 UTC, Pubmatic-Dhruv-Sonone approved these changes

2024-12-10 06:02 UTC, pm-viral-vala approved these changes

2024-12-10 06:05 UTC, merged